project:
  type: book
  output-dir: "docs"

lang: es

book:
  title: "Bitácoras Grupo #<su número>, CA-204 (II-2024)"
  author: "Estudiante A, Estudiante B, Estudiante C"
  date: today
  repo-actions: [edit]
  site-url: # Vacío por el momento
  chapters:
    - "index.qmd"

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
  cache: true

from: markdown+tex_math_single_backslash+emoji
link-external-newwindow: true
