---

---

# Bitácora 1

## Comandos de git

## Planificación

### Definición

**Idea:** Quisieramos determinar diferentes cálculos estadísticos derivados de los casos sobre desapariciones o muertes de migrantes en todo el mundo.

**Tensiones:** Podrían existir casos sin resolver, incluso de años anteriores. El estado de desaparecido no proporciona tanta información, pues se desconoce el paradero de la persona, si ha fallecido y cuál podría haber sido la posible causa de su muerte o desaparición, además de la zona exacta donde desapareció.

### Conceptualización

Determinar
: Decidir algo o despejar la incertidumbre sobre ello.

Cálculos estadísticos
: Son operaciones matemáticas que se realizan sobre un conjunto de datos para analizarlos y entenderlos mejor, como por ejemplo moda, desviación estándar, media, etc.

Desaparición
: Se refiere a la situación en la que una persona se ausenta de su residencia habitual sin motivo conocido o aparente, generando preocupación sobre su paradero y seguridad. Existen diferentes tipos como desaparición forzada, voluntaria e involuntaria.

Migrante
: Persona que se desplaza de un lugar a otro, ya sea dentro de su propio país o cruzando fronteras internacionales, con el objetivo de residir temporal o permanentemente en un nuevo lugar.

## Pregunta

Se reformula la idea en forma de preguntas, con el fin de encontrar ciertos argumentos que ayuden a resolverlas.

3. ¿Qué determina que un migrante se considere desaparecido?

4. ¿Qué países son los que contienen el mayor porcentaje de migrantes desaparecidos por año?

### Argumentación de la pregunta

**3. Pregunta: ¿Qué determina que un migrante se considere desaparecido?**

**Contraargumentos**

**Lógica:** Es difícil precisar si una persona se encuentra desaparecida mientras migra, pues existe un periodo de tiempo extenso donde no se sabe nada de la persona, incluso si logra llegar a su destino existe la posibilidad de que no se comunique con nadie y continue con su vida.

**Ética:** La dificultad que presenta buscar y encontrar a las personas reportadas desaparecidas en lugares tan amplios y con poca población o incluso deshabitados genera poco margen de éxito, por lo que muchos de estos casos quedan inconclusos y etiquetados como “desaparecidos” (que como se mencionó antes, no aporta mucho al análisis).

**Emocional:** Debido a la gran cantidad de migrantes que existen y el tiempo que implica cada viaje hasta llegar al destino final, se dificulta la investigación de cada caso y tener éxito en su búsqueda, por lo que no se refleja la realidad sobre el estado de cada migrante, si se encuentra con vida, perdido o tuvo éxito migrando. Finalmente, ante la incertidumbre simplemente se clasifica como desaparición.

**Argumentos**

**Lógica:** Existen diferentes causas por las que las personas migran, pero se tiene el objetivo encontrarse en mejores condiciones de vida que en su actual residencia. Por lo tanto, se espera que luego de un tiempo la persona tenga éxito, o en caso contrario vuelva a su país de origen. Al no tener conocimiento pronto de la situación del migrante, se sospecha la desaparición de dicha persona. Al iniciar la investigación existen diferentes factores que indican el posible paradero de la persona desaparecida, ya sea que la ruta es peligrosa, existe demasiada seguridad fronteriza para pasar, que se diera un evento catastrófico cerca de la ruta, etc. Si al final de la investigación se encuentran sobrevivientes o, en caso de muerte, el cuerpo de la persona desaparecida, se concluye el caso. De otro modo se mantiene el estado de desaparición.

**Ética:** Existen diferentes artículos que hablan sobre la desaparición de migrantes, cómo realizan la investigación de cada una y cómo mejoran con el paso de los años. Además, se cuenta con una base de datos con casos a partir del 2014, con lo que se puede analizar la evolución de los casos con el paso de los años.

**Emoción:** Debido a que la problemática tiene mayor relevancia actualmente, además de las familias preocupadas por el paradero de sus seres queridos, se cuenta con organizaciones que estudian los diferentes casos, donde se señalan las diferentes causas y aspectos que indican cuando un migrante se encuentra desaparecido, incluso en que situaciones es más probable que grupos de migrantes no tengan éxito en su viaje.

**Concluya:** El cómo se determina el estado de desaparecido de una persona migrante depende directamente del tiempo que tome tener conocimiento acerca de su paradero donde se analiza la evolución de cada caso con las investigaciones de diferentes organizaciones y finalmente se logre explicar la situación en que se encuentran los migrantes a sus familias. Todo lo anterior permitiría tener una descripción del estado de desaparecido para tener un mayor entendimiento sobre lo que ocurre con las personas que no han confirmado su llegada a su lugar de destino.

**Pregunta 4: ¿Qué países son los que contienen el mayor porcentaje de migrantes desaparecidos por año?**

**Contraargumentos**

**Lógica:** Debido a la dificultad de tener la certeza de que un migrante se encuentra desaparecido, muerto o en buen estado durante su trayecto, no se puede asegurar que determinados países presentan un mayor número migrantes que el resto. Además, depende mucho de cómo cada país realiza sus investigaciones sobre migrantes desaparecidos, pues los métodos son distintos al igual que la eficacia al realizar las búsquedas.

**Ética:** Se recolectan datos de diferentes fuentes, por lo que la calidad de la información puede variar demasiado. También se depende mucho de las instituciones de los países donde ocurren las desapariciones, por lo que la información obtenida está ligada a lo que dichas instituciones desean revelar.

**Emoción:**  Se trata de una gran cantidad de casos de los cuales muchos no han concluido hoy en día, además de que otros no se actualizan con el paso de los años, por lo que no se podría representar la realidad sobre los diferentes países.

**Argumentos**

**Lógica:** Se tiene información del lugar de origen de donde parten los migrantes, hacia donde se dirigían, rutas que tomarían para llegar e incluso coordenadas de donde se encontraron en caso sobrevivencia o muerte. De esta forma se puede analizar de qué países provienen la mayor cantidad de desaparecidos al migrar e incluso cuáles son los países que son normalmente el destino de los migrantes.

**Ética:** Se tiene diversas fuentes que contienen toda la información antes mencionada, incluso con causa de muerte (si fuera el caso) o en algunos casos el motivo de la desaparición. Además, los datos para el análisis de este proyecto se recolectaron desde el 2014, lo que sirve para determinar patrones sobre qué países resaltan en diferentes aspectos durante los últimos 10 años.

**Emoción:** Es importante reconocer qué países presentan el mayor número de personas desaparecidas, para poder predecir casos futuros y que las instituciones responsables tomen las respectivas medidas para reducir dicho número. Se puede identificar países tanto que presenten el mayor número de emigrantes como de inmigrantes.

**Concluya:** Para determinar qué países tienen más migrantes desaparecidos por año se requiere de la recolección de información de diferentes instituciones que se enfocan en encontrar a dichos migrantes, que con los datos de los últimos años se puede representar la realidad sobre cuáles de estos países presentan un mayor problema de desaparecidos que implica un problema de personas que intentaron buscar mejores oportunidades sin éxitos.



@wadiai
