---
title: "Enlace:Salud"
author: "Pablo Chaves"
date: "2024-10-07"
---

## Enlace: Salud

### Textos a estudiar

- **“More than 50,000 migrants ‘die in search of a better life’”** 13
- **“Psychology of Immigration”** 2

## Resumen

El segundo texto: **“Psychology of Immigration”** recopila una serie de información médica y psicológica en aras de apoyar a servicios de apoyo a personas migrantes. La mayor parte del artículo consiste -además de proporcionar información precisa sobre trastornos mentales que pueden padecer personas inmigrantes- en señalar y enfatizar el tenso ambiente que pueden sufrir las personas que se enmarcan en la migración, ambiente que puede incluir: discriminación, xenofobia y violencia.

Curiosamente, aporta también datos y desmiente mitos acerca de lo que significa la migración mundialmente hoy en día. Uno de estos mitos sería que la migración está en alza, lo cual no es cierto; sucede lo contrario.

Con una relación que dota de cierto paralelismo, el texto número 13: **“More than 50,000 migrants ‘die in search of a better life’”** resulta en un texto ampliamente periodístico que critica las pobres circunstancias de los migrantes. Este texto generalmente trata de exponer datos, criticar circunstancias y plantear soluciones a las consecuencias de la migración.

## Contraste

La diferencia que presentan ambos artículos, si bien ambos están ampliamente entrelazados bajo una óptica de salud, reside en el foco de dar la información.

Es un hecho que ambos artículos discuten los problemas que enfrentan los migrantes al hacer sus travesías, también ambos artículos estudian datos y elaboran una narrativa que pone en alerta las dificultades que enfrentan todas las personas que se desplazan de un país a otro (sobre todo ilegalmente). Sin embargo, un texto tiene un texto tiene sobre todo un enfoque periodístico, y el otro: académico-médico. 

Ejemplificando, el texto número 13 que fue escrito por la Organización de las Naciones Unidas, no ofrece de manera directa recursos médicos y/o psicológicos para solucionar estas situaciones, se trata más bien de mostrar qué está ocurriendo en el mundo y hace una llamada de alerta al final. 
Por otro lado, Psychology of Immigration no es un texto repleto de datos e información real que ofrezca una visión integral acerca de la realidad de la inmigración. Este pretende educar a las personas, profesionales y educadores para que se concienticen, así como también, de brindar una colección de herramientas.
A manera de conclusión y de resolución, el contraste no es sutil para nada, pero si tiene el matiz de que ambos textos abogan por interesarse por las personas inmigrantes e intentar dar una visión esperanzadora.


## Contribución propia

Se consideran ambos textos/artículos de fundamental importancia para el desarrollo teórico del trabajo investigativo. Como se señaló, ambos abordan la psicología/salud de las personas inmigrantes de maneras no directamente paralelas, sin embargo, la colección de información junta brinda al proyecto, por un lado, una serie de recomendaciones y prácticas para contribuir a los peligros de la migración, y por otro, un texto totalmente periodístico que de la necesaria parte real/cotidiana que dota del trabajo un sentido de realidad. 
Puesto que el presente trabajo de investigación no se trata en sí de teorizar acerca de los peligros y recomendaciones acerca de las personas inmigrantes, la información no estará directamente en los resultados del proyecto; lo cual estará será esencialmente resultados y cálculos estadísticos derivados de ciertos análisis. Aún así, este tipo de información dota al equipo investigativo de un enfoque aún más amplia de cómo entender y abordar toda la información obtenida. 

