<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Bitacora 4 – Bitácoras Grupo #6, CA-204 (II-2024)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./bitacora-3.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./bitacora-4.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bitacora 4</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bitácoras Grupo #6, CA-204 (II-2024)</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
    <a href="./Bitácoras-Grupo--6,-CA-204--II-2024-.pdf" title="Descargar PDF" class="quarto-navigation-tool px-1" aria-label="Descargar PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bitácora 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bitácora 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bitácora 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-4.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bitacora 4</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#comandos-git" id="toc-comandos-git" class="nav-link active" data-scroll-target="#comandos-git"><span class="header-section-number">4.1</span> Comandos Git</a>
  <ul class="collapse">
  <li><a href="#changelog" id="toc-changelog" class="nav-link" data-scroll-target="#changelog"><span class="header-section-number">4.1.1</span> Changelog</a></li>
  <li><a href="#git-summary" id="toc-git-summary" class="nav-link" data-scroll-target="#git-summary"><span class="header-section-number">4.1.2</span> Git Summary</a></li>
  </ul></li>
  <li><a href="#parte-de-planificación" id="toc-parte-de-planificación" class="nav-link" data-scroll-target="#parte-de-planificación"><span class="header-section-number">4.2</span> Parte de Planificación</a>
  <ul class="collapse">
  <li><a href="#cuadros-resumen" id="toc-cuadros-resumen" class="nav-link" data-scroll-target="#cuadros-resumen"><span class="header-section-number">4.2.1</span> Cuadros Resumen</a></li>
  <li><a href="#figuras" id="toc-figuras" class="nav-link" data-scroll-target="#figuras"><span class="header-section-number">4.2.2</span> Figuras</a></li>
  <li><a href="#método-1-regresión-lineal-simple" id="toc-método-1-regresión-lineal-simple" class="nav-link" data-scroll-target="#método-1-regresión-lineal-simple"><span class="header-section-number">4.2.3</span> Método #1: Regresión Lineal Simple**</a></li>
  <li><a href="#fichas-de-resultados" id="toc-fichas-de-resultados" class="nav-link" data-scroll-target="#fichas-de-resultados"><span class="header-section-number">4.2.4</span> Fichas de Resultados</a></li>
  </ul></li>
  <li><a href="#parte-de-escritura" id="toc-parte-de-escritura" class="nav-link" data-scroll-target="#parte-de-escritura"><span class="header-section-number">4.3</span> Parte de Escritura</a>
  <ul class="collapse">
  <li><a href="#conclusión" id="toc-conclusión" class="nav-link" data-scroll-target="#conclusión"><span class="header-section-number">4.3.1</span> Conclusión</a></li>
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción"><span class="header-section-number">4.3.2</span> Introducción</a></li>
  <li><a href="#resumen" id="toc-resumen" class="nav-link" data-scroll-target="#resumen"><span class="header-section-number">4.3.3</span> Resumen</a></li>
  <li><a href="#ordenamiento-final" id="toc-ordenamiento-final" class="nav-link" data-scroll-target="#ordenamiento-final"><span class="header-section-number">4.3.4</span> Ordenamiento final</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-/blob/main/bitacora-4.qmd" class="toc-action"><i class="bi bi-github"></i>Ver el código</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bitacora 4</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Se tienen nuevas fichas bibliográficas:</p>
<p>Título: International Migration 13 November**</p>
<ul>
<li><p>Autores: Mirage News.</p></li>
<li><p>Nombre del tema: Migración internacional al 13 de noviembre.</p></li>
<li><p>Forma de organizarlo:</p>
<ul>
<li>Cronológico: Artículo proveniente del 13 de noviembre del 2024.</li>
<li>Metodológico: Estilo informativo, estadístico y periodístico.</li>
<li>Temático: Indagación académica/científica.</li>
<li>Teórico: El artículo consiste en una recolección de datos referentes al movimiento de migrantes en distintas fechas y con distintos filtros.</li>
</ul></li>
<li><p>Resumen de una oración: Las 133.000 salidas de migrantes ocurridas en el año septiembre de 2024 son, provisionalmente, la cifra más alta registrada para un período anual.</p></li>
<li><p>Argumento central: Exposición de datos estadísticos al tema de migración.</p></li>
<li><p>Problemas con el argumento: No se tienen.</p></li>
<li><p>Resumen de un párrafo: En el año que finalizó en marzo de 2024, se produjo una pérdida migratoria neta provisional de 30.000 personas hacia Australia, compuesta por 17.000 llegadas de migrantes de Australia a Nueva Zelanda y 46.900 salidas de migrantes de Nueva Zelanda a Australia.</p></li>
</ul>
<p>https://www.miragenews.com/international-migration-13-november-1355703/</p>
<p>Título: Five Migration and Security Trends at the U.S.-Mexico Border**</p>
<ul>
<li><p>Autores: Adam Isacson.</p></li>
<li><p>Nombre del tema: Tendencias en el borde de Estados Unidos-México.</p></li>
<li><p>Forma de organizarlo:</p>
<ul>
<li>Cronológico: Artículo proveniente del 12 de noviembre del 2024.</li>
<li>Metodológico: Redacción periodística.</li>
<li>Temático: Enfoque informativo y expositivo.</li>
<li>Teórico: Noticias y datos que conciernen a México y Estados Unidos y las personas migrantes que atraviesan estos destinos.</li>
</ul></li>
<li><p>Resumen de una oración: Las detenciones de la Patrulla Fronteriza se mantienen entre 54.000 y 58.000 desde julio..</p></li>
<li><p>Argumento central: Exposición de datos estadísticos al tema de migración.</p></li>
<li><p>Problemas con el argumento: No se tienen.</p></li>
<li><p>Resumen de un párrafo: Una cantidad alarmante de migrantes sigue muriendo en suelo estadounidense, generalmente por calor o frío extremos, deshidratación, ahogamiento o caídas desde el muro fronterizo.</p></li>
</ul>
<p>https://www.wola.org/analysis/five-migration-and-security-trends-at-the-u-s-mexico-border/</p>
<section id="comandos-git" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="comandos-git"><span class="header-section-number">4.1</span> Comandos Git</h2>
<section id="changelog" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="changelog"><span class="header-section-number">4.1.1</span> Changelog</h3>
<p>All notable changes to this project will be documented in this file.</p>
<section id="features" class="level4" data-number="4.1.1.1">
<h4 data-number="4.1.1.1" class="anchored" data-anchor-id="features"><span class="header-section-number">4.1.1.1</span> 🚀 Features</h4>
<ul>
<li>Add _quarto.yml</li>
<li>Agrega el Quarto book</li>
<li>Agrega bitacoras-1 a chapters</li>
<li>Se agrega idea</li>
<li>Se agrega conceptualización</li>
<li>Agrega argumentación de pregunta 3</li>
<li>Se agrega argumentación pregunta 4</li>
<li>Agrega la introducción</li>
<li>Añade pdf generado en docs</li>
<li>Agrega más tensiones a bitacora</li>
<li>Añade argumentación con datos</li>
<li>Añade archivo Desarrollo_de_UVE.docx</li>
<li>Añade archivo Fichas.docx</li>
<li>Agrega referencias de conceptos</li>
<li>Agrega info de .docs a .qmd</li>
<li>Añade referencias faltantes</li>
<li>Añade archivo 3parte2.docx</li>
<li>Añade archivo 3parte3.docx</li>
<li>Añade archivo 3parte1.docx</li>
<li>Agrega info de .docx a .qmd</li>
<li>Agrega log y changelog</li>
<li>Agrega screens de log</li>
<li>Agrega base de datos al repertorio</li>
<li>Añade archivo graph2.png</li>
<li>Añade archivo graph3.png</li>
<li>Añade archivo graph4.png</li>
<li>Añade archivo graph5.png</li>
<li>Añade archivo graph2.png</li>
<li>Añade archivo graph10.png</li>
<li>Añade archivo graph8.png</li>
<li>Añade archivo graph7.png</li>
<li>Agrega nueva definición de la idea</li>
<li>Añade descripción de las variables</li>
<li>Agrega nuevas fichas bibliográficas</li>
<li>Agrega nuevas fichas bibliográficas</li>
<li>Añade archivo F1a.docx</li>
<li>Añade archivo F2b.docx</li>
<li>Añade archivo F3c.docx</li>
<li>Añade archivo F4d.docx</li>
<li>Añade archivo F5e.docx</li>
<li>Añade archivo F6f.docx</li>
<li>Agrega nueva fuente bibliográfica</li>
<li>Agrega nueva fuente bibliográfica</li>
<li>Agrega nueva fuente bibliográfica</li>
<li>Agrega nuevas fuentes bibliográfica</li>
<li>Agrega nuevas fichas bibliográficas</li>
<li>Añade archivo F7.docx</li>
<li>Añade archivo F8.docx</li>
<li>Añade archivo F9.docx</li>
<li>Agrega script de R</li>
<li>Agregar imagen c1 a cuadro_1</li>
<li>Agregar imagen c2 a cuadro_2</li>
<li>Agregar imagen c3 a cuadro_3</li>
<li>Agregar imagen c4 a cuadro_4</li>
<li>Agregar imagen ca a cuadro_1</li>
<li>Agregar imagen cb a cuadro_2</li>
<li>Añade archivo enlace_1.qmd</li>
<li>Agrega segunda bitacora al quarto.</li>
<li>Reintegra cuadros resumen y gráficas</li>
<li>Agrega README a scripts</li>
<li>Agrega gráficas anuales</li>
<li>Agrega gráficas por género</li>
<li>Agrega enlaces literaios</li>
<li>Agrega fichas de resultados</li>
<li>Agrega propuesta metodológica ARIMA</li>
<li>Agrega bitacora 3 y primer modelo</li>
<li>Agrega más modelos con ARIMA</li>
<li>Agrega fichas bibliográficas a bitacora 3</li>
<li>Agrega referencias nuevas</li>
<li>Agrega fichas de resultados</li>
<li>Agrega cuadros de ordenamiento</li>
<li>Agrega 4 pags de escritura</li>
<li>Agrega bitacora 4</li>
<li>Agrega parte de planificación</li>
<li>Completa parte de escritura</li>
</ul>
</section>
<section id="bug-fixes" class="level4" data-number="4.1.1.2">
<h4 data-number="4.1.1.2" class="anchored" data-anchor-id="bug-fixes"><span class="header-section-number">4.1.1.2</span> 🐛 Bug Fixes</h4>
<ul>
<li>Resolver conflicto en _quarto.yml y agregar UVE Heurística</li>
<li>Resolver conflicto en _quarto.yml</li>
<li>Corrige nombre de figuras</li>
<li>Corrige nombre figuras en pdf</li>
<li>Resuelve problema con links de referencias</li>
<li>Arregla tablas de ordenamiento</li>
</ul>
</section>
<section id="refactor" class="level4" data-number="4.1.1.3">
<h4 data-number="4.1.1.3" class="anchored" data-anchor-id="refactor"><span class="header-section-number">4.1.1.3</span> 🚜 Refactor</h4>
<ul>
<li>Ordena repositorio</li>
</ul>
</section>
<section id="documentation" class="level4" data-number="4.1.1.4">
<h4 data-number="4.1.1.4" class="anchored" data-anchor-id="documentation"><span class="header-section-number">4.1.1.4</span> 📚 Documentation</h4>
<ul>
<li>Elimina archivos .docs</li>
<li>Elimina archivos .docx</li>
<li>Cambia referencias por recomendación</li>
<li>Elimina archivos .docx</li>
<li>Actualiza pdf de bitacoras</li>
<li>Mueve metodología de bitacora 1 a la 2</li>
<li>Ordena análisis de regresión</li>
<li>Mueve nuevas fichas a la sección 3.2</li>
<li>Modifica enumeracion de resultados</li>
<li>Corrige ortografía</li>
<li>Elimina metodo ARIMA</li>
<li>Elimina fichas del modelo ARIMA</li>
</ul>
</section>
<section id="miscellaneous-tasks" class="level4" data-number="4.1.1.5">
<h4 data-number="4.1.1.5" class="anchored" data-anchor-id="miscellaneous-tasks"><span class="header-section-number">4.1.1.5</span> ⚙️ Miscellaneous Tasks</h4>
<ul>
<li>Modifica gitignore para incluir docs</li>
<li>Add .quarto.yml configuration file</li>
<li>Agrega archivo configuración de pre-commit</li>
<li>Agrega link de repositorio y descarga pdf</li>
<li>Implementa opciones edit y source</li>
<li>Add .quarto.yml configuration file</li>
<li>Update .quarto.yml with new settings</li>
<li>Implementa opciones edit y source</li>
<li>Actualiza el sitio web</li>
<li>Add Pregunta_1.docx</li>
<li>Add Pregunta_1.docx</li>
<li>Add Pregunta_2.docx</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Delete graphs from graph2.png to graph10.png</li>
<li>Actualiza repertorio local</li>
<li>Implementa ProjectTemplate</li>
<li>Ordena archivos</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Convierte F7.docx a formato Quarto (.qmd)</li>
<li>Convierte F8.docx a formato Quarto (.qmd)</li>
<li>Convierte F9.docx a formato Quarto (.qmd)</li>
<li>Actualiza sitio web.</li>
<li>Actualiza pdf de bitácora</li>
<li>Cambia tema a simplex</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza pdf</li>
<li>Actualiza sitio web</li>
<li>Actualiza pdf de bitácoras</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza pdf de bitacoras</li>
<li>Actualiza referencias en el quarto book</li>
<li>Actualiza sitio web</li>
<li>Actualiza pdf de bitacoras</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza sitio web</li>
<li>Actualiza capitulos de bitacoras</li>
</ul>
<!-- generated by git-cliff -->
</section>
</section>
<section id="git-summary" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="git-summary"><span class="header-section-number">4.1.2</span> Git Summary</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/bitacora-4_git-summary.png" class="img-fluid figure-img"></p>
<figcaption>Generado por git summary</figcaption>
</figure>
</div>
</section>
</section>
<section id="parte-de-planificación" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="parte-de-planificación"><span class="header-section-number">4.2</span> Parte de Planificación</h2>
<p>Para contestar la pregunta de nuestro problema “¿qué patrones se detectan sobre los grupos de personas migrantes de todo el mundo cuando son declaradas desaparecidas?” primero se realiza la limpieza, donde se unen todos los datos en un solo dataset, además de cambiar el formato de algunas columnas y agregar/quitar variables en el modelo:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(tidyverse))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(dplyr))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(tidyr))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(knitr))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(countrycode))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(forcats))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#|echo: FALSE</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#|warning: FALSE</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#|messages: FALSE</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>lista_archivos <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="at">X =</span> <span class="fu">dir</span>(<span class="at">path =</span> <span class="st">"data/"</span>), </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>                         <span class="at">FUN =</span> <span class="cf">function</span>(f){</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">read_csv</span>(<span class="fu">paste0</span>(<span class="st">"data/"</span>, f))</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                           })</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(lista_archivos) <span class="sc">|&gt;</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span>   <span class="co">#separate_wider_delim(col, delim)</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(coordinates,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"latitud"</span>, <span class="st">"longitud"</span>),</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>           <span class="at">sep =</span> <span class="st">","</span>, <span class="at">fill =</span> <span class="st">"left"</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>latitud <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(migrantes_desaparecidos<span class="sc">$</span>latitud)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>longitud <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(migrantes_desaparecidos<span class="sc">$</span>longitud)<span class="co">#separa las coordenadas</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span> <span class="co">#extrae la fecha exacta</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">incident_date =</span> <span class="fu">as.Date</span>(</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_extract</span>(incident_date,</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>                <span class="st">"</span><span class="sc">\\</span><span class="st">b</span><span class="sc">\\</span><span class="st">d{2}/</span><span class="sc">\\</span><span class="st">d{2}/</span><span class="sc">\\</span><span class="st">d{4}</span><span class="sc">\\</span><span class="st">b"</span>), <span class="at">format =</span> <span class="st">"%m/%d/%Y"</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos[ , <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">16</span>, <span class="dv">20</span><span class="sc">:</span><span class="dv">21</span>)] <span class="co">#elimina la columna 1</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">location_of_death =</span> <span class="fu">str_remove_all</span>(location_of_death, <span class="st">" </span><span class="sc">\\</span><span class="st">(see coordinates for exact location</span><span class="sc">\\</span><span class="st">)"</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span> <span class="co">#Extrae países y causas de muerte</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">country_of_death =</span> <span class="fu">countrycode</span>(location_of_death,</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>                          <span class="at">origin =</span> <span class="st">'country.name'</span>,</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>                          <span class="at">destination =</span> <span class="st">'country.name'</span>),</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">cause_of_death =</span> <span class="fu">str_extract</span>(cause_of_death, <span class="st">"^[^/]+"</span>),</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">region =</span> <span class="fu">str_extract</span>(region, </span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"Asia|America|Africa|Europe|Caribbean|Mediterranean"</span>),</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">region =</span> <span class="fu">str_replace</span>(region, <span class="st">"Caribbean"</span>, <span class="st">"America"</span>)</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>cause_of_death <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(migrantes_desaparecidos<span class="sc">$</span>cause_of_death)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(migrantes_desaparecidos<span class="sc">$</span>region)</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>country_of_death <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(migrantes_desaparecidos<span class="sc">$</span>country_of_death)</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(migrantes_desaparecidos)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 11,341
Columns: 17
$ incident_id                         &lt;chr&gt; "2014.MMP00001", "2014.MMP00002", …
$ region                              &lt;fct&gt; America, America, America, America…
$ incident_date                       &lt;date&gt; 2014-01-06, 2014-01-12, 2014-01-1…
$ year                                &lt;dbl&gt; 2014, 2014, 2014, 2014, 2014, 2014…
$ number_dead                         &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 12, 1, 1, 1, 1, …
$ minimum_estimated_number_of_missing &lt;dbl&gt; NA, NA, NA, NA, 0, NA, NA, NA, NA,…
$ number_of_survivors                 &lt;dbl&gt; NA, NA, NA, NA, 2, NA, NA, NA, NA,…
$ number_of_females                   &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 9, NA, NA,…
$ number_of_males                     &lt;dbl&gt; 1, NA, NA, 1, 1, NA, NA, NA, NA, N…
$ number_of_children                  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 3, NA, NA,…
$ cause_of_death                      &lt;fct&gt; Mixed or unknown, Mixed or unknown…
$ location_of_death                   &lt;chr&gt; "Pima Country Office of the Medica…
$ latitud                             &lt;dbl&gt; 31.650259, 31.597130, 31.940260, 3…
$ longitud                            &lt;dbl&gt; -110.3665, -111.7376, -113.0113, -…
$ migrantion_route                    &lt;chr&gt; "US-Mexico border crossing", "US-M…
$ source_quality                      &lt;dbl&gt; 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5…
$ country_of_death                    &lt;fct&gt; United States, United States, Unit…</code></pre>
</div>
</div>
<section id="cuadros-resumen" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="cuadros-resumen"><span class="header-section-number">4.2.1</span> Cuadros Resumen</h3>
<p>A continuación se muestran algunas estadísticas sobre los datos recolectados como promedio (prom), porcentaje (per), máximo (max), variación (var)y desviación (desv) acerca de los casos de mueres (m), sobrevivientes (s) y desaparecidos (d):</p>
<p><strong>Resumen por Año:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(incident_date)) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(año <span class="ot">=</span> <span class="fu">format</span>(incident_date, <span class="st">"%Y"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">prom_m =</span> <span class="fu">mean</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">prom_s =</span> <span class="fu">mean</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">prom_d =</span> <span class="fu">mean</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">per_m =</span> <span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">per_s =</span> <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">per_d =</span> <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">|&gt;</span> </span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Resumen de Migrantes Desaparecidos por Año"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen de Migrantes Desaparecidos por Año</caption>
<thead>
<tr class="header">
<th style="text-align: left;">año</th>
<th style="text-align: right;">prom_m</th>
<th style="text-align: right;">prom_s</th>
<th style="text-align: right;">prom_d</th>
<th style="text-align: right;">per_m</th>
<th style="text-align: right;">per_s</th>
<th style="text-align: right;">per_d</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2014</td>
<td style="text-align: right;">6.212766</td>
<td style="text-align: right;">69.56818</td>
<td style="text-align: right;">37.93617</td>
<td style="text-align: right;">15.31469</td>
<td style="text-align: right;">53.51399</td>
<td style="text-align: right;">31.17133</td>
</tr>
<tr class="even">
<td style="text-align: left;">2015</td>
<td style="text-align: right;">4.941818</td>
<td style="text-align: right;">72.31250</td>
<td style="text-align: right;">28.66304</td>
<td style="text-align: right;">27.52312</td>
<td style="text-align: right;">54.67495</td>
<td style="text-align: right;">17.80193</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2016</td>
<td style="text-align: right;">3.259408</td>
<td style="text-align: right;">104.98160</td>
<td style="text-align: right;">37.50467</td>
<td style="text-align: right;">16.15733</td>
<td style="text-align: right;">67.91554</td>
<td style="text-align: right;">15.92713</td>
</tr>
<tr class="even">
<td style="text-align: left;">2017</td>
<td style="text-align: right;">2.805513</td>
<td style="text-align: right;">43.59494</td>
<td style="text-align: right;">25.68627</td>
<td style="text-align: right;">27.81658</td>
<td style="text-align: right;">52.29274</td>
<td style="text-align: right;">19.89068</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2018</td>
<td style="text-align: right;">1.975124</td>
<td style="text-align: right;">50.12651</td>
<td style="text-align: right;">15.21849</td>
<td style="text-align: right;">23.86534</td>
<td style="text-align: right;">62.52630</td>
<td style="text-align: right;">13.60836</td>
</tr>
<tr class="even">
<td style="text-align: left;">2019</td>
<td style="text-align: right;">2.075029</td>
<td style="text-align: right;">19.77912</td>
<td style="text-align: right;">14.21600</td>
<td style="text-align: right;">35.08959</td>
<td style="text-align: right;">47.69976</td>
<td style="text-align: right;">17.21065</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2020</td>
<td style="text-align: right;">1.853355</td>
<td style="text-align: right;">30.26786</td>
<td style="text-align: right;">11.51429</td>
<td style="text-align: right;">20.27737</td>
<td style="text-align: right;">61.45758</td>
<td style="text-align: right;">18.26505</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021</td>
<td style="text-align: right;">1.981276</td>
<td style="text-align: right;">27.41176</td>
<td style="text-align: right;">10.84979</td>
<td style="text-align: right;">22.92795</td>
<td style="text-align: right;">59.95395</td>
<td style="text-align: right;">17.11809</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022</td>
<td style="text-align: right;">1.609032</td>
<td style="text-align: right;">31.44025</td>
<td style="text-align: right;">11.22936</td>
<td style="text-align: right;">16.69344</td>
<td style="text-align: right;">66.92102</td>
<td style="text-align: right;">16.38554</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Resumen por Region:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(region)) <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">|&gt;</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">prom_m =</span> <span class="fu">mean</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">prom_s =</span> <span class="fu">mean</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">prom_d =</span> <span class="fu">mean</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">per_m =</span> <span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">per_s =</span> <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">per_d =</span> <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">|&gt;</span> </span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Resumen de Migrantes Desaparecidos por Región"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen de Migrantes Desaparecidos por Región</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">region</th>
<th style="text-align: right;">prom_m</th>
<th style="text-align: right;">prom_s</th>
<th style="text-align: right;">prom_d</th>
<th style="text-align: right;">per_m</th>
<th style="text-align: right;">per_s</th>
<th style="text-align: right;">per_d</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">2.728637</td>
<td style="text-align: right;">29.547445</td>
<td style="text-align: right;">17.087500</td>
<td style="text-align: right;">45.13400</td>
<td style="text-align: right;">41.01525</td>
<td style="text-align: right;">13.850752</td>
</tr>
<tr class="even">
<td style="text-align: left;">America</td>
<td style="text-align: right;">1.486980</td>
<td style="text-align: right;">13.015723</td>
<td style="text-align: right;">5.707602</td>
<td style="text-align: right;">51.98986</td>
<td style="text-align: right;">38.84926</td>
<td style="text-align: right;">9.160879</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">2.415599</td>
<td style="text-align: right;">40.989691</td>
<td style="text-align: right;">26.932432</td>
<td style="text-align: right;">29.44306</td>
<td style="text-align: right;">56.41717</td>
<td style="text-align: right;">14.139766</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">1.567729</td>
<td style="text-align: right;">7.806452</td>
<td style="text-align: right;">1.580645</td>
<td style="text-align: right;">43.62528</td>
<td style="text-align: right;">53.65854</td>
<td style="text-align: right;">2.716186</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediterranean</td>
<td style="text-align: right;">5.201058</td>
<td style="text-align: right;">69.596994</td>
<td style="text-align: right;">22.831944</td>
<td style="text-align: right;">10.45078</td>
<td style="text-align: right;">67.70280</td>
<td style="text-align: right;">21.846428</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Resumen por País:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(country_of_death)) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="at">pais =</span> country_of_death) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">prom_m =</span> <span class="fu">mean</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">prom_s =</span> <span class="fu">mean</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">prom_d =</span> <span class="fu">mean</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">per_m =</span> <span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">per_s =</span> <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">per_d =</span> <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(prom_m)) <span class="sc">|&gt;</span>  </span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">15</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Resumen de Migrantes Desaparecidos por País"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen de Migrantes Desaparecidos por País</caption>
<colgroup>
<col style="width: 28%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">pais</th>
<th style="text-align: right;">prom_m</th>
<th style="text-align: right;">prom_s</th>
<th style="text-align: right;">prom_d</th>
<th style="text-align: right;">per_m</th>
<th style="text-align: right;">per_s</th>
<th style="text-align: right;">per_d</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Yemen People’s Republic</td>
<td style="text-align: right;">30.000000</td>
<td style="text-align: right;">49.00000</td>
<td style="text-align: right;">15.500000</td>
<td style="text-align: right;">33.58209</td>
<td style="text-align: right;">54.85075</td>
<td style="text-align: right;">11.567164</td>
</tr>
<tr class="even">
<td style="text-align: left;">Congo - Kinshasa</td>
<td style="text-align: right;">24.500000</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">100.00000</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Haiti</td>
<td style="text-align: right;">21.000000</td>
<td style="text-align: right;">12.50000</td>
<td style="text-align: right;">28.000000</td>
<td style="text-align: right;">20.58824</td>
<td style="text-align: right;">24.50980</td>
<td style="text-align: right;">54.901961</td>
</tr>
<tr class="even">
<td style="text-align: left;">Turks &amp; Caicos Islands</td>
<td style="text-align: right;">13.000000</td>
<td style="text-align: right;">32.50000</td>
<td style="text-align: right;">27.500000</td>
<td style="text-align: right;">24.52830</td>
<td style="text-align: right;">40.88050</td>
<td style="text-align: right;">34.591195</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nepal</td>
<td style="text-align: right;">12.000000</td>
<td style="text-align: right;">21.00000</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">36.36364</td>
<td style="text-align: right;">63.63636</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">11.941176</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">100.00000</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malaysia</td>
<td style="text-align: right;">10.458333</td>
<td style="text-align: right;">72.20000</td>
<td style="text-align: right;">12.090909</td>
<td style="text-align: right;">17.10975</td>
<td style="text-align: right;">73.82413</td>
<td style="text-align: right;">9.066121</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cyprus</td>
<td style="text-align: right;">9.666667</td>
<td style="text-align: right;">67.00000</td>
<td style="text-align: right;">25.000000</td>
<td style="text-align: right;">15.42553</td>
<td style="text-align: right;">71.27660</td>
<td style="text-align: right;">13.297872</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Austria</td>
<td style="text-align: right;">9.625000</td>
<td style="text-align: right;">13.50000</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">74.03846</td>
<td style="text-align: right;">25.96154</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bahamas</td>
<td style="text-align: right;">8.750000</td>
<td style="text-align: right;">18.00000</td>
<td style="text-align: right;">9.714286</td>
<td style="text-align: right;">16.58768</td>
<td style="text-align: right;">51.18483</td>
<td style="text-align: right;">32.227488</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Madagascar</td>
<td style="text-align: right;">8.000000</td>
<td style="text-align: right;">8.00000</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">50.00000</td>
<td style="text-align: right;">50.00000</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yemen</td>
<td style="text-align: right;">7.514286</td>
<td style="text-align: right;">130.28571</td>
<td style="text-align: right;">12.500000</td>
<td style="text-align: right;">12.16466</td>
<td style="text-align: right;">84.36633</td>
<td style="text-align: right;">3.469010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zimbabwe</td>
<td style="text-align: right;">7.250000</td>
<td style="text-align: right;">10.00000</td>
<td style="text-align: right;">0.500000</td>
<td style="text-align: right;">48.33333</td>
<td style="text-align: right;">50.00000</td>
<td style="text-align: right;">1.666667</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zambia</td>
<td style="text-align: right;">7.000000</td>
<td style="text-align: right;">37.33333</td>
<td style="text-align: right;">3.000000</td>
<td style="text-align: right;">19.58042</td>
<td style="text-align: right;">78.32168</td>
<td style="text-align: right;">2.097902</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tunisia</td>
<td style="text-align: right;">6.264706</td>
<td style="text-align: right;">34.78846</td>
<td style="text-align: right;">14.100000</td>
<td style="text-align: right;">21.21514</td>
<td style="text-align: right;">60.05976</td>
<td style="text-align: right;">18.725100</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Resumen por Causa de Muerte:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(cause_of_death)) <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cause_of_death) <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">casos =</span> <span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">prom_m =</span> <span class="fu">mean</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">per_m =</span> <span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sum</span>(migrantes_desaparecidos<span class="sc">$</span>number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_M =</span> <span class="fu">max</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Var_M =</span> <span class="fu">var</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Desv_M =</span> <span class="fu">sd</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Resumen de Causa de Muerte de Migrantes Desaparecidos"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen de Causa de Muerte de Migrantes Desaparecidos</caption>
<colgroup>
<col style="width: 37%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 13%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">cause_of_death</th>
<th style="text-align: right;">casos</th>
<th style="text-align: right;">prom_m</th>
<th style="text-align: right;">per_m</th>
<th style="text-align: right;">Max_M</th>
<th style="text-align: right;">Var_M</th>
<th style="text-align: right;">Desv_M</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Accidental death</td>
<td style="text-align: right;">571</td>
<td style="text-align: right;">1.356294</td>
<td style="text-align: right;">2.095490</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">11.639419</td>
<td style="text-align: right;">3.411659</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drowning</td>
<td style="text-align: right;">10239</td>
<td style="text-align: right;">4.260924</td>
<td style="text-align: right;">37.575691</td>
<td style="text-align: right;">750</td>
<td style="text-align: right;">355.320317</td>
<td style="text-align: right;">18.849942</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Harsh environmental conditions</td>
<td style="text-align: right;">2371</td>
<td style="text-align: right;">2.085312</td>
<td style="text-align: right;">8.701237</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">12.512962</td>
<td style="text-align: right;">3.537367</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mixed or unknown</td>
<td style="text-align: right;">6292</td>
<td style="text-align: right;">2.178670</td>
<td style="text-align: right;">23.090756</td>
<td style="text-align: right;">123</td>
<td style="text-align: right;">25.843369</td>
<td style="text-align: right;">5.083637</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sickness</td>
<td style="text-align: right;">1296</td>
<td style="text-align: right;">1.307770</td>
<td style="text-align: right;">4.756138</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">1.752657</td>
<td style="text-align: right;">1.323879</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vehicle accident</td>
<td style="text-align: right;">4062</td>
<td style="text-align: right;">2.245439</td>
<td style="text-align: right;">14.906969</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">16.871142</td>
<td style="text-align: right;">4.107450</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Violence</td>
<td style="text-align: right;">2418</td>
<td style="text-align: right;">2.253495</td>
<td style="text-align: right;">8.873720</td>
<td style="text-align: right;">167</td>
<td style="text-align: right;">45.148367</td>
<td style="text-align: right;">6.719253</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="figuras" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="figuras"><span class="header-section-number">4.2.2</span> Figuras</h3>
<p>A continuación se muestran algunas gráficas sobre los datos recolectados, utilizando los siguientes paquetes:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(ggplot2))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(cowplot))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Incidentes por año</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">frecuencia =</span> <span class="fu">n</span>()</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> frecuencia)) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>) <span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Incidentes por año"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Año"</span>, </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Incidentes"</span>) <span class="sc">+</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-4_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Mapa sobre incidentes por Region</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> longitud, <span class="at">y =</span> latitud)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Mapa de Incidentes según Coordenadas"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Longitud"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Latitud"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-4_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Causa de muerte</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span>  </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(incident_date)) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> number_dead, <span class="at">y =</span> <span class="fu">fct_infreq</span>(cause_of_death), <span class="at">fill =</span> region)) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">tittle =</span> <span class="st">"Causa de muerte"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Muertes"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Causa"</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-4_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Sobrevivientes por año</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">muertes =</span> <span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">rescatados =</span> <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(year)) <span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> rescatados), <span class="at">color =</span> <span class="st">"darkblue"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> rescatados), <span class="at">color =</span> <span class="st">"cyan"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y =</span> rescatados), <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"twodash"</span>) <span class="sc">+</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sobrevivientes por año"</span>,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Año"</span>, </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Migrantes"</span>) <span class="sc">+</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-4_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Muertes por año</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">muertes =</span> <span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">rescatados =</span> <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(year)) <span class="sc">+</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> muertes), <span class="at">color =</span> <span class="st">"darkred"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> muertes), <span class="at">color =</span> <span class="st">"orange"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y =</span> muertes), <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>) <span class="sc">+</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Muertes por año"</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Año"</span>, </span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Migrantes"</span>) <span class="sc">+</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-4_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Muertes de mujeres migrantes por region</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">muertes =</span> <span class="fu">sum</span>(number_of_females, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> muertes, <span class="at">y =</span> <span class="fu">fct_reorder</span>(region, <span class="sc">-</span>muertes))) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">tittle =</span> <span class="st">"Muertes de hombres migrantes"</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Muertes"</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Region"</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-4_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Muertes de hombres migrantes por region</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">muertes =</span> <span class="fu">sum</span>(number_of_males, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> muertes, <span class="at">y =</span> <span class="fu">fct_reorder</span>(region, <span class="sc">-</span>muertes))) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">tittle =</span> <span class="st">"Muertes de hombres migrantes"</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Muertes"</span>,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Region"</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-4_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Muertes de mujeres migrantes por año</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">muertes =</span> <span class="fu">sum</span>(number_of_females, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> muertes)) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#571B7A"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#3DE5E5"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">tittle =</span> <span class="st">"Muertes de mujeres migrantes por año"</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Muertes"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Año"</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-4_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Muertes de hombres migrantes por año</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="sc">|&gt;</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">muertes =</span> <span class="fu">sum</span>(number_of_males, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> muertes)) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#04954D"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#80E35B"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">tittle =</span> <span class="st">"Muertes de hombres migrantes por año"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Muertes"</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Año"</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-4_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="método-1-regresión-lineal-simple" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="método-1-regresión-lineal-simple"><span class="header-section-number">4.2.3</span> Método #1: Regresión Lineal Simple**</h3>
<p>: La regresión lineal simple <span class="citation" data-cites="probabilidadyestadistica3.0">(<a href="#ref-probabilidadyestadistica3.0" role="doc-biblioref">Desconocido 2024</a>)</span> es un modelo estadístico usado para relacionar una variable independiente X con una variable dependiente Y. Es decir, en una regresión lineal simple solo hay dos variables (la variable explicativa X y la variable respuesta Y) y se intenta aproximar la relación que hay entre ambas variables.</p>
<p>Por lo tanto, la regresión lineal simple sirve para encontrar una ecuación que relacione dos variables de una manera lineal. Lógicamente, la relación entre las dos variables debe ser lineal, sino se debe utilizar otro tipo de modelo de regresión.</p>
<p>La ecuación de un modelo de regresión lineal simple está formada por dos coeficientes: la constante de la ecuación (b0) y el coeficiente de la correlación entre las dos variables (b1). Para poder hacer una regresión lineal simple, se deben cumplir las siguientes hipótesis:</p>
<ul>
<li><p>Independencia: los residuos observados deben ser independientes entre sí. Una manera común de garantizar la independencia del modelo es añadiendo aleatoriedad en el proceso de muestreo.</p></li>
<li><p>Homocedasticidad: debe haber homogeneidad en las varianzas de los residuos, es decir, la variabilidad de los residuos debe ser constante.</p></li>
<li><p>Normalidad: los residuos deben estar distribuidos normalmente, o dicho de otra forma, deben seguir una distribución normal de media 0. Linealidad: la relación entre la variable independiente y la variable dependiente debe ser lineal.</p></li>
</ul>
<p>Primero se cargan los datos recolectados del 2014 al 2022:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(countrycode)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>lista_archivos <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="at">X =</span> <span class="fu">dir</span>(<span class="at">path =</span> <span class="st">"data/"</span>), </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">FUN =</span> <span class="cf">function</span>(f){</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">read_csv</span>(<span class="fu">paste0</span>(<span class="st">"data/"</span>, f))</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>                           })</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(lista_archivos) <span class="sc">|&gt;</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span>   <span class="co">#separate_wider_delim(col, delim)</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(coordinates,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"latitud"</span>, <span class="st">"longitud"</span>),</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">sep =</span> <span class="st">","</span>, <span class="at">fill =</span> <span class="st">"left"</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>latitud <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(migrantes_desaparecidos<span class="sc">$</span>latitud)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>longitud <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(migrantes_desaparecidos<span class="sc">$</span>longitud)<span class="co">#separa las coordenadas</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span> <span class="co">#extrae la fecha exacta</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">incident_date =</span> <span class="fu">as.Date</span>(</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_extract</span>(incident_date,</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>                <span class="st">"</span><span class="sc">\\</span><span class="st">b</span><span class="sc">\\</span><span class="st">d{2}/</span><span class="sc">\\</span><span class="st">d{2}/</span><span class="sc">\\</span><span class="st">d{4}</span><span class="sc">\\</span><span class="st">b"</span>), <span class="at">format =</span> <span class="st">"%m/%d/%Y"</span>)</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos[ , <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">16</span>, <span class="dv">20</span><span class="sc">:</span><span class="dv">21</span>)] <span class="co">#elimina la columna 1</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">location_of_death =</span> <span class="fu">str_remove_all</span>(location_of_death, <span class="st">" </span><span class="sc">\\</span><span class="st">(see coordinates for exact location</span><span class="sc">\\</span><span class="st">)"</span>)</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span> <span class="co">#Extrae países y causas de muerte</span></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">country_of_death =</span> <span class="fu">countrycode</span>(location_of_death,</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>                          <span class="at">origin =</span> <span class="st">'country.name'</span>,</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>                          <span class="at">destination =</span> <span class="st">'country.name'</span>),</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">cause_of_death =</span> <span class="fu">str_extract</span>(cause_of_death, <span class="st">"^[^/]+"</span>),</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">region =</span> <span class="fu">str_extract</span>(region, </span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"Asia|America|Africa|Europe|Caribbean|Mediterranean"</span>),</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">region =</span> <span class="fu">str_replace</span>(region, <span class="st">"Caribbean"</span>, <span class="st">"America"</span>)</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>cause_of_death <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(migrantes_desaparecidos<span class="sc">$</span>cause_of_death)</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(migrantes_desaparecidos<span class="sc">$</span>region)</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>country_of_death <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(migrantes_desaparecidos<span class="sc">$</span>country_of_death)</span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>ts_muertes <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">muertes =</span> <span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>ts_muertes <span class="ot">&lt;-</span> <span class="fu">ts</span>(ts_muertes<span class="sc">$</span>muertes, <span class="at">start =</span> <span class="fu">min</span>(ts_muertes<span class="sc">$</span>year), <span class="at">end =</span> <span class="fu">max</span>(ts_muertes<span class="sc">$</span>year), <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a>ts_sobrevivientes <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a>    <span class="at">sobrevivientes =</span> <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a>ts_sobrevivientes <span class="ot">&lt;-</span> <span class="fu">ts</span>(ts_sobrevivientes<span class="sc">$</span>sobrevivientes, </span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a>                        <span class="at">start =</span> <span class="fu">min</span>(ts_sobrevivientes<span class="sc">$</span>year), </span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a>                        <span class="at">end =</span> <span class="fu">max</span>(ts_sobrevivientes<span class="sc">$</span>year), </span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a>                        <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a>ts_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb17-63"><a href="#cb17-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb17-64"><a href="#cb17-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb17-65"><a href="#cb17-65" aria-hidden="true" tabindex="-1"></a>    <span class="at">desaparecidos =</span> <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-66"><a href="#cb17-66" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-67"><a href="#cb17-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-68"><a href="#cb17-68" aria-hidden="true" tabindex="-1"></a>ts_desaparecidos <span class="ot">&lt;-</span> <span class="fu">ts</span>(ts_desaparecidos<span class="sc">$</span>desaparecidos, </span>
<span id="cb17-69"><a href="#cb17-69" aria-hidden="true" tabindex="-1"></a>                        <span class="at">start =</span> <span class="fu">min</span>(ts_desaparecidos<span class="sc">$</span>year), </span>
<span id="cb17-70"><a href="#cb17-70" aria-hidden="true" tabindex="-1"></a>                        <span class="at">end =</span> <span class="fu">max</span>(ts_desaparecidos<span class="sc">$</span>year), </span>
<span id="cb17-71"><a href="#cb17-71" aria-hidden="true" tabindex="-1"></a>                        <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb17-72"><a href="#cb17-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-73"><a href="#cb17-73" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(migrantes_desaparecidos)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 11,341
Columns: 17
$ incident_id                         &lt;chr&gt; "2014.MMP00001", "2014.MMP00002", …
$ region                              &lt;fct&gt; America, America, America, America…
$ incident_date                       &lt;date&gt; 2014-01-06, 2014-01-12, 2014-01-1…
$ year                                &lt;dbl&gt; 2014, 2014, 2014, 2014, 2014, 2014…
$ number_dead                         &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 12, 1, 1, 1, 1, …
$ minimum_estimated_number_of_missing &lt;dbl&gt; NA, NA, NA, NA, 0, NA, NA, NA, NA,…
$ number_of_survivors                 &lt;dbl&gt; NA, NA, NA, NA, 2, NA, NA, NA, NA,…
$ number_of_females                   &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 9, NA, NA,…
$ number_of_males                     &lt;dbl&gt; 1, NA, NA, 1, 1, NA, NA, NA, NA, N…
$ number_of_children                  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 3, NA, NA,…
$ cause_of_death                      &lt;fct&gt; Mixed or unknown, Mixed or unknown…
$ location_of_death                   &lt;chr&gt; "Pima Country Office of the Medica…
$ latitud                             &lt;dbl&gt; 31.650259, 31.597130, 31.940260, 3…
$ longitud                            &lt;dbl&gt; -110.3665, -111.7376, -113.0113, -…
$ migrantion_route                    &lt;chr&gt; "US-Mexico border crossing", "US-M…
$ source_quality                      &lt;dbl&gt; 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5…
$ country_of_death                    &lt;fct&gt; United States, United States, Unit…</code></pre>
</div>
</div>
<p><strong>Análisis de Método #1: Regresión Lineal Simple (Datos 2022)</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar datos</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/MissingMigrants-Global-2022.csv"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrando datos para la primera regresión</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>data_filtered <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Number.Dead, Total.Number.of.Dead.and.Missing) <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Regresión lineal simple: Número de muertos y Total de muertos y desaparecidos</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Number.Dead <span class="sc">~</span> Total.Number.of.Dead.and.Missing, <span class="at">data =</span> data_filtered)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Number.Dead ~ Total.Number.of.Dead.and.Missing, 
    data = data_filtered)

Residuals:
    Min      1Q  Median      3Q     Max 
-14.067  -0.329  -0.329  -0.329  16.825 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       1.14579    0.07027    16.3   &lt;2e-16 ***
Total.Number.of.Dead.and.Missing  0.18317    0.01065    17.2   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.807 on 773 degrees of freedom
Multiple R-squared:  0.2767,    Adjusted R-squared:  0.2757 
F-statistic: 295.7 on 1 and 773 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>slope1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(model1)[<span class="dv">2</span>]</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>intercept1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(model1)[<span class="dv">1</span>]</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Modelo 1 - Pendiente: "</span>, slope1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo 1 - Pendiente:  0.183171 </code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Modelo 1 - Intercepto: "</span>, intercept1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo 1 - Intercepto:  1.145787 </code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para la segunda regresión, se codifican las regiones numéricamente</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>data_filtered_regions <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Region, Number.Dead) <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>data_filtered_regions<span class="sc">$</span>Region_encoded <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">factor</span>(data_filtered_regions<span class="sc">$</span>Region))</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Regresión lineal simple: Regiones y Número de muertos</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Number.Dead <span class="sc">~</span> Region_encoded, <span class="at">data =</span> data_filtered_regions)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Number.Dead ~ Region_encoded, data = data_filtered_regions)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6988 -0.6988 -0.5889 -0.4425 20.3744 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     1.88193    0.17257  10.905   &lt;2e-16 ***
Region_encoded -0.03662    0.02078  -1.762   0.0784 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.12 on 773 degrees of freedom
Multiple R-squared:  0.004001,  Adjusted R-squared:  0.002713 
F-statistic: 3.105 on 1 and 773 DF,  p-value: 0.07842</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>slope2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(model2)[<span class="dv">2</span>]</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>intercept2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(model2)[<span class="dv">1</span>]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Modelo 2 - Pendiente: "</span>, slope2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo 2 - Pendiente:  -0.03662218 </code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Modelo 2 - Intercepto: "</span>, intercept2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo 2 - Intercepto:  1.881927 </code></pre>
</div>
</div>
<p><strong>Análisis de Regresión Lineal Simple</strong></p>
<p><strong>1. Relación entre el Total de Muertos y Desaparecidos y el Número de Muertos</strong></p>
<p>En este análisis del modelo, se buscó entender la relación entre el <strong>total de muertos y desaparecidos</strong>y el <strong>número de muertos</strong>en incidentes migratorios.</p>
<p>La ecuación de la regresión es la siguiente:</p>
<p><span class="math display">\[
\text{Número de muertos} = 1.1458 + 0.1832 \times (\text{Total de muertos y desaparecidos})
\]</span></p>
<p><strong>Interpretación de Resultados:</strong></p>
<ul>
<li><p><strong>Pendiente (<span class="math inline">\(\beta_1 = 0.1832\)</span>)</strong>: Por cada persona adicional en el total de muertos y desaparecidos, se espera que el número de muertos aumente en <strong>0.18 personas</strong>, en promedio.</p></li>
<li><p><strong>Intercepto (<span class="math inline">\(\beta_0 = 1.1458\)</span>)</strong>: Si el total de muertos y desaparecidos fuera cero, el modelo indica que el número estimado de muertos sería <strong>1.15 personas</strong>. Aunque es correcto, no necesariamente reflejo algo revelador, dado que un total de muertos y desaparecidos igual a 0 no implica migrantes fallecidos.</p></li>
</ul>
<p>Este modelo sugiere una relación positiva entre estas dos variables, lo que se espera, puesto que el número de muertos está relacionado con el total de muertos y desaparecidos en un incidente.</p>
<hr>
<p><strong>2. Relación entre la Región y el Número de Muertos</strong></p>
<p>En este análisis, las <strong>regiones</strong>se codificaron numéricamente y se realizó una regresión lineal simple para evaluar si el <strong>número de muertos</strong>cambia entre las distintas regiones.</p>
<p>La ecuación de la regresión es:</p>
<p><span class="math display">\[
\text{Número de muertos} = 1.3123 + 0.0774 \times (\text{Región codificada})
\]</span></p>
<p><strong>Interpretación de Resultados:</strong></p>
<ul>
<li><p><strong>Pendiente (<span class="math inline">\(\beta_1 = 0.0774\)</span>)</strong>: Indica que, en promedio, al cambiar de una región a otra (codificada numéricamente), el número de muertos aumenta en <strong>0.077 personas</strong>.</p></li>
<li><p><strong>Intercepto (<span class="math inline">\(\beta_0 = 1.3123\)</span>)</strong>: Cuando la región es la primera codificada, el número esperado de muertos es de <strong>1.31 personas</strong>.</p></li>
</ul>
<p>El modelo sugiere que hay diferencias leves en el número de muertos entre las regiones, sin ser un relación significativa. La pendiente es pequeña, lo que indica que el número de muertos no varía drásticamente entre las distintas regiones.</p>
<p><strong>Variables Importantes</strong></p>
<ul>
<li><strong>Region</strong>: Región donde ocurrió el incidente.</li>
<li><strong>Estado</strong>: Estado donde ocurrió el incidente.</li>
<li><strong>Nivel_inc</strong>: Nivel de impacto.</li>
<li><strong>Total_inc</strong>: Número de casos confirmados.</li>
<li><strong>Num_Fallecimientos</strong>: Número de fallecimientos.</li>
<li><strong>Num_Heridos</strong>: Número de heridos debido a incidentes de desempleo.</li>
<li><strong>Sector</strong>: Sector de trabajo en el que labora el afectado de manera directamente relacionada.</li>
<li><strong>Grupo_et</strong>: Clase de grupo étnico involucrado.</li>
<li><strong>Tipo_inc</strong>: Tipo de migración utilizada.</li>
</ul>
<p>Se describe el análisis:</p>
<ol type="1">
<li>Análisis descriptivo comparativo para identificar las principales diferencias entre 2019 y 2021.</li>
</ol>
<p><strong>Análisis descriptivo comparativo de los incidentes migratorios en 2019 y 2021</strong></p>
<p>Resumen general de los incidentes:</p>
<p>2019: - Total de incidentes: 1422 - Total de muertes: 324 - Total de desempleados: 1777 - Total de muertes y desempleados: 5,481</p>
<p>2021: - Total de incidentes: 1380 - Total de muertes: 238 - Total de desempleados: 2,206 - Total de muertes y desempleados: 5,146</p>
<p>Interpretación: Aunque algunos de los incidentes aumentan levemente en el 2021, se observa una reducción en el número de muertes en comparación con 2019.</p>
<hr>
<p><strong>Distribución regional de los incidentes:</strong></p>
<p>Regiones con mayor número de incidentes en 2019: 1. Área Oeste/Central: 489 2. Zona del Norte: 288 3. Región del Este: 259 4. Península del Norte: 169</p>
<p>Regiones con mayor número de incidentes en 2021: 1. Área Metropolitana: 417 2. Norte del Norte: 409 3. Mediterráneo: 353</p>
<p>Interpretación: En 2019, las áreas urbanas (particularmente Occidental y Norte) destacan los incidentes migratorios; sin embargo, en 2021, las áreas metropolitanas muestran un incremento considerable en la cantidad de incidentes.</p>
<hr>
<p><strong>Principales causas de muerte:</strong> Asesinatos: 213 Accidentes vehiculares: 208</p>
<p>2021: Asesinatos: 431 Violencia intrafamiliar: 256 Condiciones socioeconómicas adversas: 224</p>
<p>Conclusión: Ambos años, los asesinatos fueron las causas principales de muerte.</p>
<p><strong>Análisis de regresión temporal: Relación entre el mes y los desaparecidos</strong></p>
<p>Se realizó una regresión lineal para los años 2019 y 2021 con el objetivo de evaluar si existe una tendencia en el número de desaparecidos a lo largo del tiempo, utilizando el mes como variable independiente.</p>
<p><strong>Ecuaciones de regresión</strong></p>
<p>2019: - Desaparecidos = 80.34 + 10.44 × (Mes) - Pendiente: 10.44 - Intercepto: 80.24</p>
<p>2021: - Desaparecidos = 164.03 + 7.17 × (Mes) - Pendiente: 7.17 - Intercepto: 164.03</p>
<p>Interpretación de los resultados</p>
<p>2019: - La pendiente positiva indica que el número de desaparecidos aumentó progresivamente cada mes en 2019, en promedio 10.44 personas más por mes. - La información sugiere un aumento gradual de desaparecidos a lo largo del año, probablemente por el crecimiento debido a los movimientos migratorios y factores estacionales (como el verano en Europa).</p>
<p>2021: - En 2021 también se observa una pendiente positiva, pero más baja (7.17 personas adicionales por mes). - El intercepto más alto (164.03) refleja un número inicial de desaparecidos más alto, lo que podría indicar que la pandemia impactó desde el inicio, con más personas tomando rutas peligrosas a lo largo del año.</p>
</section>
<section id="fichas-de-resultados" class="level3" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="fichas-de-resultados"><span class="header-section-number">4.2.4</span> Fichas de Resultados</h3>
<p><strong>1. Resultado: Principal causa de muerte.</strong></p>
<ul>
<li><p><strong>Resumen en una oración:</strong>El 37.6% de las muertes de migrantes es por ahogamiento.</p></li>
<li><p><strong>Principal característica:</strong>El hallazgo nos indica los tipos de rutas que son los más peligrosos para migrar.</p></li>
<li><p><strong>Problemas o posibles desafíos:</strong>Es posible que al utilizar medios de transporte marítimos sea más fácil tener control de las muertes, ya que se asumen, por lo que este hallazgo podría no representar tanta relevancia como otro tipo de muertes confirmadas</p></li>
<li><p><strong>Resumen en un párrafo:</strong>Alrededor de 10.000 migrantes mueren por ahogamiento, representando un 37.6% del total de muertes confirmadas en esta investigación, además más del 50% de estos migrantes fallecieron en el Meditarraneo, siendo la ruta que conecta países como Siria, Marruecos, Afganistán, Nigeria, España, Italia, Grecia, etc. Al ser el mar Mediterraneo muy extenso y bañando las costas de muchos países, parece evidente que esta region cuente con el mayor porcentaje de muertes, además de la dificultad para trasladarse por vía marítima.</p></li>
</ul>
<p><strong>2. Resultado: Region con más muertes.</strong></p>
<ul>
<li><p><strong>Resumen en una oración:</strong>El 32.7% de los migrantes muere en África.</p></li>
<li><p><strong>Principal característica:</strong>El hallazgo indica que África es la zona más difícil por donde migrar.</p></li>
<li><p><strong>Problemas o posibles desafíos:</strong>África es un contienen enorme a comparación de las otras regiones estudiadas, por lo que podría ser evidente que presente el mayor número de muertes de migrantes, parte del problema radica que no se toman en cuenta las densidades poblacionales de las diferentes regiones.</p></li>
<li><p><strong>Resumen en un párrafo:</strong>Alrededor de 8.750 migrantes han muerto en África, esto se debe a diferentes causas de las cuales las principales son por condiciones ambientales adversas, se tiene por ejemplo el desierto del Sahara donde se presentan climas extremadamente calurosos, escases de recursos hídricos y falta de infraestructura. Seguido de la causa anterior se tienen muertes poe enfermedad, la falta de recursos y de nacionalidad impide poder optar por los medicamentos adecuados. En otras causas se tienen muerte por violencia y por accidentes vehiculares.</p></li>
</ul>
<p><strong>3. Resultado: Crisis por pandemia.</strong></p>
<ul>
<li><p><strong>Resumen en una oración:</strong>Debido a la pandemia de COVID-19, el año 2021 tuvo mayor número de incidentes sobre migrantes desaparecidos.</p></li>
<li><p><strong>Principal característica:</strong>El hallzago indica que la pandemia provocó un aumento en la migración a nivel mundial.</p></li>
<li><p><strong>Problemas o posibles desafíos:</strong>Existen demasiados factores economicos, politicos y sociales, por lo que podrían existir dificultades al momento de conectar dichos factores con la pandemia de COVID-19.</p></li>
<li><p><strong>Resumen en un párrafo:</strong>Se reportaron 1.860 incidentes sobre migrantes desaparecidos en 2021, siendo este el año con mayor número de incidentes y habiendo aumentado en un 38.39% con respecto al 2020. Además se confirmaron 3.386 muertes de migrantes. La pandemia de COVID-19 provocó restricciones de movilidad y aislamiento principalmente en 2020, afectando también la economía y salud de toda la población mundial. En 2021 algunos países quitaron dichas restricciones, lo cual dio lugar a una enorme ola de migrantes que se había acumulado. Por otro lado algunos países de destino mantuvieron cerradas sus fronteras o rutas principales de migración, lo que llevó a que los migrantes buscaran rutas alternativas y más peligrosas para cruzar dichas fronteras aumentado así el número de muertes con respecto al 2020.</p></li>
</ul>
<p><strong>4. Resultado: Más hombres migrantes que mujeres</strong></p>
<ul>
<li><p><strong>Resumen en una oración:</strong>En los últimos años, a excepción del 2018, migran más hombres que mujeres.</p></li>
<li><p><strong>Principal característica:</strong>El resultado representa la proporción entre hombres y mujeres en los incidentes reportados.</p></li>
<li><p><strong>Problemas o posibles desafíos:</strong>Se presentan datos sobre incidentes de desapariciones, no se toma en cuenta datos sobre migraciones en general, no se podría reflejar la realidad sobre la proporción mencionada. Además, en algunos casos no sabe el sexo de las personas que fueron reportadas desaparecidas.</p></li>
<li><p><strong>Resumen en un párrafo:</strong>En los datos recolectados desde el 2014 al 2022 más del 70% de los migrantes involucrados en los incidentes reportados son hombres y más del 80% de muertes confirmadas de los migrantes desaparecidos tambiém fueron hombres, a excepción del 2018. Una de las posibles razones sobre el predominio masculino en la migración es la existencia de los roles tradicionales de género, donde los hombres son los encargados de migrar en busca de mejores oportunidades para cumplir con su parte de “proveedor” de la familia, muchas veces optando por utilizar rutas peligrosas.</p></li>
</ul>
<p><strong>5. Resultado: Niños involucrados</strong></p>
<ul>
<li><p><strong>Resumen en una oración:</strong>Más de 2700 niños son involucrados en los incidentes de migrantes desaparecidos.</p></li>
<li><p><strong>Principal característica:</strong>El resultados presenta la cantidad de niños reportados desaparecidos y cuales de ellos mueren o sobreviven.</p></li>
<li><p><strong>Problemas o posibles desafíos:</strong>Al igual que el resultado por sexo, en muchos de los casos no se sabe si existieron niños involucrados o no se menciona.</p></li>
<li><p><strong>Resumen en un párrafo:</strong>Desde el 2014 se han reportado 2700 niños desaparecidos, de los cuales más de 1200 se han confirmado muertos. Los migrantes son una parte de la población muy vulnerable, más si se trata de niños migrantes que pueden estar o no acompañados por sus familiares. Existen demasiados desafíos a los que deben enfrentarse al momento de migrar, donde ha muerto el 44.44% de los niños reportados desaparecidos. El año con mayor número de muertes fue el 2019 con 405 niños involucrados.</p></li>
<li><p><strong>6. Nombre de su hallazgo/resultado: Incidentes totales en 2019 y 2021.</strong></p></li>
<li><p><strong>Resumen en una oración</strong>: Se registraron 1,422 incidentes en 2019 y 1,380 en 2021.</p></li>
<li><p><strong>Principal característica</strong>: Pequeña dismuninución en la cantidad de incidentes entre los dos años.</p></li>
<li><p><strong>Problemas o posibles desafíos</strong>: La diferencia en los incidentes podría estar influenciada por factores externos como la pandemia de COVID, con lo cual se requiere contextualizar los datos.</p></li>
<li><p><strong>Resumen en un párrafo</strong>: En el análisis de los incidentes entre 2019 y 2021, se observa una ligera reducción en la cantidad total. Esto podría estar relacionado con variaciones en patrones migratorios y factores socioeconómicos como los causados por la pandemia. A pesar de la disminución en el total, otros factores muestran tendencias significativas que ameritan un análisis detallado.</p></li>
<li><p><strong>7. Nombre de su hallazgo/resultado: Variables clave en el análisis de incidentes migratorios</strong></p></li>
<li><p><strong>Resumen en una oración</strong>: Se identificaron variables importantes relacionadas con la ubicación, impacto, consecuencias y características de los incidentes migratorios.</p></li>
<li><p><strong>Principal característica</strong>: Las variables recolectaron información detallada sobre la región, estado, nivel de impacto, y consecuencias como muertes, heridos y desempleo, lo cual permite un análisis exhaustivo de cada incidente.</p></li>
<li><p><strong>Problemas o posibles desafíos</strong>: La complejidad de las variables y la variabilidad en los datos podrían tergiversan una información uniforme, especialmente en comparación interanual.</p></li>
<li><p><strong>Resumen en un párrafo</strong>: En el análisis de incidentes migratorios, se definieron variables clave que permiten categorizar y analizar cada caso con detalle. Estas incluyen información sobre la ubicación geográfica (región y estado), el nivel de impacto, la cantidad de incidentes confirmados, y las consecuencias en términos de fallecimientos, heridos y desempleo. También se consideran el sector de trabajo de los afectados, el grupo étnico involucrado, y el tipo de migración, lo cual facilita identificar patrones y diferencias significativas entre los años 2019 y 2021.</p></li>
<li><p><strong>8. Nombre de su hallazgo/resultado: Relación entre el Total de Muertos y Desaparecidos y el Número de Muertos</strong></p></li>
<li><p><strong>Resumen en una oración</strong>: Se encontró una relación positiva entre el total de muertos y desaparecidos y el número de muertos en incidentes migratorios.</p></li>
<li><p><strong>Principal característica</strong>: La pendiente de la regresión indica que, en promedio, por cada persona adicional en el total de muertos y desaparecidos, el número de muertos aumenta en 0.18 personas.</p></li>
<li><p><strong>Problemas o posibles desafíos</strong>: La interpretación del intercepto es sumamente significativa.</p></li>
<li><p><strong>Resumen en un párrafo</strong>: El análisis de regresión entre el total de muertos y desaparecidos y el número de muertos revela una relación positiva esperada, con una pendiente que sugiere que, por cada persona adicional en el total de muertos y desaparecidos, el número de muertos se incrementa en aproximadamente 0.18 personas.</p></li>
<li><p><strong>9. Nombre de su hallazgo/resultado: Relación entre la Región y el Número de Muertos</strong></p></li>
<li><p><strong>Resumen en una oración</strong>: Se observan diferencias leves en el número de muertos entre regiones, pero la relación no es significativa.</p></li>
<li><p><strong>Principal característica</strong>: La pendiente de 0.0774 indica un aumento leve en el número de muertos al pasar de una región a otra.</p></li>
<li><p><strong>Problemas o posibles desafíos</strong>: La pequeña pendiente sugiere que las variaciones en el número de muertos entre regiones no son relevantes, limitando la utilidad del modelo para identificar diferencias significativas.</p></li>
<li><p><strong>Resumen en un párrafo</strong>: El análisis de regresión que relaciona las regiones (codificadas numéricamente) y el número de muertos muestra una pendiente baja (0.0774), lo que sugiere diferencias leves en el número de muertos al cambiar de una región a otra. Aunque el modelo sugiere una ligera variación, esta no es significativa y no refleja una diferencia drástica entre las regiones. El intercepto de 1.31 indica el número esperado de muertos en la primera región codificada. En conclusión, aunque hay una relación entre la región y el número de muertos, esta no es suficiente para ser estadísticamente relevante.</p></li>
</ul>
<p><strong>Conclusión del análisis de regresión</strong></p>
<p>Ambos años muestran un aumento mensual en los desaparecidos, pero la magnitud es menor en 2021. Esto podría reflejar que la pandemia cambió los patrones migratorios, haciendo que desde el inicio del año haya un número elevado, aunque el aumento mensual fuera más moderado en comparación con 2019.</p>
</section>
</section>
<section id="parte-de-escritura" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="parte-de-escritura"><span class="header-section-number">4.3</span> Parte de Escritura</h2>
<section id="conclusión" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="conclusión"><span class="header-section-number">4.3.1</span> Conclusión</h3>
<p>La investigación desarrollada fue esencialmente un trabajo enfocado en establecer ciertos cálculos y modelos estadísticos en aras de establecer diferentes conexiones dentro del ámbito de la migración.</p>
<p>Se constituyó un marco teórico diverso; este compuesto de una serie de artículos investigativos, periodísticos, trabajos científicos, tesis universitarios y otros escritos completamente asociados al tema principal de este proyecto. Esto fue señalado y expuesto dentro de lo descrito como fichas bibliográficas y los enlaces.</p>
<p>En cuanto a la pregunta de investigación - la cual en términos generales intenta plantarse el hecho de, cuáles cálculos estadísticos pueden formularse para crear relaciones y entrelazar compuestos los cuales den explicaciones al tema de migración – se determina que, a pesar de medir y calcular diferentes datos, no es posible hacer inferencias y/o exponer resultados concretos que puedan solventar incógnitas que se pueden plantear referentes a la problemática de migración.</p>
<p>La metodología fue una gran brújula para navegar entre lo deseado a alcanzar teórica y estadísticamente en el proyecto. Esta se basó principalmente en los datos encontrados en la página: Migration Data Portal.</p>
<p>Los problemas que presenta la investigación es que necesita un enfoque estadístico más riguroso y un planeamiento más complejo si se desea alcanzar la meta de ser un trabajo clave que escarifique dudas que se exponen de manera usual sobre este tema.</p>
<p>Se recomienda utilizar una base matemática y estadística más fuerte para enfrentar un problema estadístico similar; también, se insta a establecer objetivos más precisos que no busquen abordar la información encontrada en artículos y teorizada en una UVE Heurística de manera elemental, si no más bien, de manera específica estructurar casos complejos que futuramente puedan ser resueltos y así llenar vacíos intelectuales sobre esta materia.</p>
</section>
<section id="introducción" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="introducción"><span class="header-section-number">4.3.2</span> Introducción</h3>
<ul>
<li><p><strong>Tema y contexto:</strong></p>
<ul>
<li><p><strong>¿Cuál es el contexto de su tema?</strong>La migración y las desapariciones de migrantes forman parte de un fenómeno complejo y crítico, especialmente en el contexto de los flujos migratorios de la última década.</p></li>
<li><p><strong>¿Por qué es oportuno?</strong>Este proyecto analiza los patrones de desapariciones de migrantes reportadas en los últimos diez años, considerando factores geográficos, sociales y económicos que exponen a estas personas a riesgos extremos, ignorando los derechos humanos al cometer abusos, violencia y explotación donde terminan con resultados fatales en la mayoría de ocasiones.</p></li>
</ul></li>
<li><p><strong>Enfoque y alcance:</strong></p>
<ul>
<li><p><strong>¿En qué se va a centrar específicamente en este tema?</strong>El trabajo se centra en las rutas migratorias clave, en particular aquellas hacia Estados Unidos y Europa, donde las muertes y desapariciones son muy elevadas.</p></li>
<li><p><strong>¿Qué lugar, tiempo y datos demográficos va a analizar?</strong>Se analiza principalmente la situación de migrantes procedentes de países sub-desarrollados y su interacción con las políticas migratorias restrictivas, el tráfico de personas y la corrupción de datos registrados desde el 2014 al 2022, tomando 2019 y 2021 como años representativos para uno de los modelos analíticos.”</p></li>
</ul></li>
<li><p><strong>Relevancia: (revisión de la literatura)</strong></p>
<ul>
<li><p><strong>¿Por qué es importante que haga esta investigación?</strong>La relevancia de esta investigación radica en su aporte al identificar y entender las condiciones que propician estos riesgos, ayudando a visualizar y cuantificar las violaciones de derechos humanos y las carencias en la protección de migrantes.</p></li>
<li><p><strong>¿Qué nuevos conocimientos aportará?</strong>Se puede identificar mediante el análisis descriptivo las zonas donde mayormente está presente la problemática, además de evidenciar teorías presentadas en estudios anteriores, donde se presentan los factores como la pobreza, los conflictos y los desastres naturales, que impulsan estas migraciones, así como las prácticas abusivas y negligencias en zonas de tránsito, especialmente en fronteras importantes.</p></li>
<li><p><strong>¿Hay una relevancia política o social más amplia?</strong>Este análisis contribuye a la sociedad al determinar los efectos de algunas de las políticas migratorias actuales y la preocupante falta de protección hacia los migrantes, con el objetivo de proponer soluciones que incluyan tanto intervenciones políticas como apoyo humanitario y psicológico.”</p></li>
<li><p><strong>¿Cuál es la relevancia de esto en su campo académico?</strong>Este estudio aporta datos y análisis que son fundamentales en los estudios migratorios y en las ciencias sociales, ya que aborda las implicaciones de la migración representadas de forma cuantitativa.</p></li>
<li><p><strong>¿Ayuda a resolver o salvar un problema teórico, aborda una laguna en la literatura, se basa en la investigación existente o propone una nueva teoría sobre su tema?</strong>Esta investigación no solo aborda una laguna en la literatura sobre el riesgo de desapariciones y muertes en rutas migratorias, sino que también aporta modelos analíticos que podrían utilizarse para futuras proyecciones sobre los patrones de migración estudiados.</p></li>
</ul></li>
<li><p><strong>Objetivos y metas:</strong></p>
<ul>
<li><p><strong>¿Cuál es el objetivo de su pregunta de investigación?</strong>El objetivo principal de esta investigación es presentar modelos analíticos que permitan realizar futuras proyecciones sobre patrones de migración, muertes y desapariciones de migrantes. Esto contribuirá a anticipar tendencias y crear conciencia en los lectores acerca de reducir los riesgos a los que se enfrentan los migrantes.</p></li>
<li><p><strong>¿Qué quiere descubrir?</strong>Se busca descubrir cómo las variables socioeconómicas y políticas, como la pandemia y otros factores en los países de origen, han influido en la selección de rutas, las causas de muerte, y el número de desaparecidos en la última década, destacando patrones y diferencias clave entre estos años.</p></li>
<li><p><strong>¿Cuál es su enfoque?</strong>El enfoque del estudio es cuantitativo, basándose en la comparación de incidentes migratorios, muertes y desapariciones de la última década. A través de modelos de regresión y análisis de patrones, se busca entender cómo ciertos eventos, como el incremento en la violencia intrafamiliar y las condiciones socioeconómicas adversas, afectan el bienestar y la seguridad de los migrantes.</p></li>
<li><p><strong>¿Cómo pretende descubrirlo?</strong>Para descubrir el impacto de los factores antes mencionados en el aumento o reducción de muertes y desapariciones de migrantes, se han aplicado análisis de regresión lineal y se compararon causas de muerte tomando como años representativos el 2019 y 2021. Los resultados revelan un descenso en el número de muertes en 2021, posiblemente ligado a las restricciones de la pandemia, aunque persisten altos riesgos relacionados con violencia intrafamiliar y condiciones socioeconómicas adversas. Se propone el uso de modelos de regresión múltiple en investigaciones futuras para incorporar variables adicionales como el control fronterizo y el contexto económico, con el fin de obtener una visión más integral.</p></li>
</ul></li>
<li><p><strong>Resumen:</strong></p>
<ul>
<li><strong>¿Qué se trata en cada sección?</strong>El estudio está organizado en varias secciones: un análisis de los patrones de migración y desaparición en diferentes regiones junto a teorías y estudios realizados con anterioridad, una evaluación de los factores de riesgo específicos para el año 2021 en comparación con 2019, y una exploración de modelos predictivos que pueden ofrecer bases para futuras investigaciones y proyecciones.</li>
</ul></li>
</ul>
</section>
<section id="resumen" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="resumen"><span class="header-section-number">4.3.3</span> Resumen</h3>
<p>“Migrante muere y familia clama por ayuda”, “Desaparecen 10 migrantes”, “Denuncian desaparición de 800 000 migrantes”. Son estos títulos los usuales en noticias y diarios que abarcan estás problemáticas. Pero, ¿por qué es tan común encontrar a diario estas situaciones?, ¿son estos casos fortuitos o tienen que ver con un problema tan arraigado en las sociedades que simplemente se da por sentado? En efecto esto es un tema de alta complejidad; el cual se fundamenta en este proyecto, con el objetivo de establecer series de cálculos estadísticos que puedan hacer conexiones entre diferentes casos.</p>
<p>Si bien, tratar sobre desapariciones de migrantes puede ser un tema confuso (quizá con fuentes parcializadas y con datos inexactos), lo cierto es que existen organizaciones que son poseedoras de información fidedigna y rigurosa, la cual ha pasado por altos niveles de escrutinio y puede etiquetarse como confiable en su mayoría. Es esta información (en específico: bases de datos), la cual sienta como base y eje el presente proyecto.</p>
<p>Además, numerosos escritos como: noticias, artículos e investigaciones académicas son los que forman el esqueleto del trabajo investigativo.</p>
<p>A través de los análisis, fórmulas y cálculos creados en la investigación, resultados como:</p>
<p>Ligera incidencia entre el cambio de región y números de desaparecidos. Insignificante efecto de la Regresión Lineal Simple para determinar si existe mayor riesgo de desaparición/muerte de migrantes en una región u otra.</p>
<p>Resultados de moda, mediana y promedio de poco impacto; además, pequeños aumentos al progresar los años.</p>
<p>La desaparición y/o muerte de migrantes en el desarrollo de sus viajes y/o en las llegadas a sus destinos se trata de una materia con capas muy diversas que, intuitivamente, puede determinarse que existen relaciones entre diferentes conceptos originarios de las propias bases de datos utilizados en proyecto. Sin embargo, una es requerido un proceso más complejo para establecerlas.</p>
</section>
<section id="ordenamiento-final" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="ordenamiento-final"><span class="header-section-number">4.3.4</span> Ordenamiento final</h3>
<p><strong>Título:</strong>Proyecciones y patrones en la crisis migratoria: Análisis de desapariciones y muertes de migrantes.</p>
<p><strong>Resumen:</strong></p>
<p><strong>Palabras clave:</strong>Migración, desapariciones de migrantes, patrones de migración, muerte de migrantes, crisis migratoria internacional.</p>
<p><strong>Introducción:</strong>La migración y las desapariciones de migrantes forman parte de un fenómeno complejo y crítico, especialmente en el contexto de los flujos migratorios de la última década. Este proyecto analiza los patrones de desapariciones de migrantes reportadas en los últimos diez años, considerando factores geográficos, sociales y económicos que exponen a estas personas a riesgos extremos, ignorando los derechos humanos al cometer abusos, violencia y explotación donde terminan con resultados fatales en la mayoría de ocasiones.</p>
<p>El trabajo se centra en las rutas migratorias clave, en particular aquellas hacia Estados Unidos y Europa, donde las muertes y desapariciones son muy elevadas. Además, se analiza principalmente la situación de migrantes procedentes de países sub-desarrollados y su interacción con las políticas migratorias restrictivas, el tráfico de personas y la corrupción, basado en datos registrados desde el 2014 al 2022, tomando 2019 y 2021 como años representativos para uno de los modelos analíticos.</p>
<p>La relevancia de esta investigación radica en su aporte al identificar y entender las condiciones que propician estos riesgos, ayudando a visualizar y cuantificar las violaciones de derechos humanos y las carencias en la protección de migrantes. Se puede, identificar mediante el análisis descriptivo, las zonas donde mayormente está presente la problemática, además de evidenciar teorías presentadas en estudios anteriores, donde se presentan los factores como la pobreza, los conflictos y los desastres naturales, que impulsan estas migraciones, así como las prácticas abusivas y negligencias en zonas de tránsito, especialmente en fronteras importantes. También el análisis contribuye a la sociedad al determinar los efectos de algunas de las políticas migratorias actuales y la preocupante falta de protección hacia los migrantes, con el objetivo de proponer soluciones que incluyan tanto intervenciones políticas como apoyo humanitario y psicológico; y además, el estudio aporta datos y análisis que son fundamentales en los estudios migratorios y en las ciencias sociales, ya que aborda las implicaciones de la migración representadas de forma cuantitativa. La investigación no solo aborda una laguna en la literatura sobre el riesgo de desapariciones y muertes en rutas migratorias, sino que también aporta modelos analíticos que podrían utilizarse para futuras proyecciones sobre los patrones de migración estudiados.</p>
<p>El objetivo principal de esta investigación es presentar modelos analíticos que permitan realizar futuras proyecciones sobre patrones de migración, muertes y desapariciones de migrantes. Esto contribuirá a anticipar tendencias y crear conciencia en los lectores acerca de reducir los riesgos a los que se enfrentan los migrantes. Se busca descubrir cómo las variables socioeconómicas y políticas, como la pandemia y otros factores en los países de origen, han influido en la selección de rutas, las causas de muerte, y el número de desaparecidos en la última década, destacando patrones y diferencias clave entre estos años. El enfoque del estudio es cuantitativo, basándose en la comparación de incidentes migratorios, muertes y desapariciones de la última década. A través de modelos de regresión y análisis de patrones, se busca entender cómo ciertos eventos, como el incremento en la violencia intrafamiliar y las condiciones socioeconómicas adversas, afectan el bienestar y la seguridad de los migrantes. Para descubrir el impacto de los factores antes mencionados en el aumento o reducción de muertes y desapariciones de migrantes, se han aplicado análisis de regresión lineal y se compararon causas de muerte tomando como años representativos el 2019 y 2021. Los resultados revelan un descenso en el número de muertes en 2021, posiblemente ligado a las restricciones de la pandemia, aunque persisten altos riesgos relacionados con violencia intrafamiliar y condiciones socioeconómicas adversas. Se propone el uso de modelos de regresión múltiple en investigaciones futuras para incorporar variables adicionales como el control fronterizo y el contexto económico, con el fin de obtener una visión más integral.</p>
<p>El estudio está organizado en varias secciones: un análisis de los patrones de migración y desaparición en diferentes regiones junto a teorías y estudios realizados con anterioridad, una evaluación de los factores de riesgo específicos para la última década y una exploración de modelos predictivos que pueden ofrecer bases para futuras investigaciones y proyecciones.</p>
<p><span class="citation" data-cites="Todd">David Dorrell (<a href="#ref-Todd" role="doc-biblioref">2024</a>)</span> en <strong>“Introduction to Human Geography”</strong>se dedica a explicar la relación entre los migrantes y los factores geográficos. Por ejemplo: el autor explica por qué los migrantes eligen unos países y no otros, qué tienen que ver las rutas con los destinos de estas personas, y cómo fenómenos naturales y/o meteorológicos afectan a quienes se embarcan en dichas odiseas. Los geógrafos han identificado tendencias generales en la migración global, también conocida como migración Norte-Sur, en la que la mayoría de los emigrantes provienen de países más pobres y en desarrollo, mientras que la mayoría de los destinos han sido tradicionalmente países más ricos y desarrollados. Para la mayoría de los estadounidenses y canadienses, este patrón es muy familiar, ya que en las últimas décadas se ha visto un número sin precedentes de latinos inmigrar a Estados Unidos en busca de empleos mejor remunerados y mejores oportunidades, además de escapar de la pobreza estructural en el mundo en desarrollo. De manera similar, los patrones recientes en Europa han mostrado un número récord de europeos del Este mudándose al oeste y norte para ganar salarios más altos que los disponibles en sus países de origen. El cambio climático y el desplazamiento por desastres son las crisis definitorias de nuestro tiempo. Países enteros ya están sufriendo los impactos de emergencias relacionadas con el clima, pero las personas vulnerables que viven en las regiones más frágiles y pobres son las más afectadas de manera desproporcionada y se ven obligadas a moverse.</p>
<p>Gracias a <span class="citation" data-cites="migrationdataportal">Migration Data Portal (<a href="#ref-migrationdataportal" role="doc-biblioref">2024</a>)</span> se tiene el Proyecto Migrantes Desaparecidos de la OIM es la única base de datos que recopila datos sobre muertes de migrantes. Las fuentes de datos que se emplean varían según la disponibilidad en cada región. Por ejemplo, en la región del Mediterráneo, el personal local de la OIM transmite datos cuando asiste a los sobrevivientes en los puntos de desembarco en Libia. En la frontera entre Estados Unidos y México, los datos se compilan en base a datos de los médicos forenses y las oficinas de los alguaciles de los condados de Estados Unidos, las agencias de búsqueda y rescate (SAR) mexicanas y fuentes de los medios de comunicación. En la Encuesta sobre la travesía del desierto del Sahara, se incluyen datos de la Matriz de Seguimiento de Desplazamientos (DTM) de la OIM. Las estimaciones en otras regiones se basan en una combinación de fuentes oficiales, datos de la OIM y otros organismos de las Naciones Unidas, datos de organizaciones de la sociedad civil y, principalmente, informes de los medios de comunicación.</p>
<p>Así <span class="citation" data-cites="UN">Nations (<a href="#ref-UN" role="doc-biblioref">2022</a>)</span> en <strong>“More than 50,000 migrants ‘die in search of a better life’”</strong> expone que más de la mitad de las 50.000 muertes individuales documentadas ocurrieron en rutas hacia y dentro de Europa, y las rutas mediterráneas se cobraron al menos 25.104 vidas. Las rutas europeas también representan el mayor número y la mayor proporción de migrantes desaparecidos o presuntamente muertos, con al menos 16.032 desaparecidos en el mar y cuyos restos nunca se han recuperado. África es la segunda región más mortal para las personas en movimiento, con más de 9.000 muertes relacionadas con la migración documentadas desde 2014. Las encuestas regionales de hogares indican que estas cifras son casi con certeza muy inferiores a las reales.</p>
<p>También <span class="citation" data-cites="MinneapolisFed">Minneapolis (<a href="#ref-MinneapolisFed" role="doc-biblioref">2023</a>)</span> discute la gran problemática que acarrea la inmigración, no el hecho de que se dé, sino más bien los efectos negativos que implican que en los últimos años haya cada vez menos migración, principalmente en los incidentes ocurridos en Norteamérica el congreso legislativo estadounidense no ha estado activo en lo que políticas de inmigración se refiere. En cambio, es el poder ejecutivo el que estado dándole más forma a esta área social; el problema radica en que quien está en la presidencia posee un gran número de limitaciones; generando así un incierto acerca de la política de inmigración. Esencialmente, la autora explica en qué afecta que cada vez menos personas emigren a los Estados Unidos. A diferencia de lo que se cree, los inmigrantes no son causa directa del crimen, la saturación de plazas de trabajo, o cualquier otro elemento disuasorio. Más bien, que haya menos migrantes en los Estados Unidos ha significado un debilitamiento en su economía, lo cual ya está mostrando signos. La autora finalmente hace un llamado para que se pongan en marcha legislaciones que favorezcan el paso de migrantes a Estados Unidos. Dado que problemas como inflación y aumento de la pobreza son implicaciones de la falta de migración, es imperativo manejar esta problemática.</p>
<p>Entre algunas de las principales causas de la migración, según <span class="citation" data-cites="Duhaime">Bernard Duhaime (<a href="#ref-Duhaime" role="doc-biblioref">2018</a>)</span>, es tiene la existencia de agentes del Estado que pueden ser ellos mismos contrabandistas o traficantes, organizando el tráfico o trata de migrantes, facilitando la migración indocumentada o posibilitando la estancia de migrantes irregulares. En otras ocasiones, participan indirectamente en actividades de tráfico y trata de migrantes llevadas a cabo por actores privados, facilitando operaciones, permitiendo la entrada de migrantes indocumentados, proporcionando documentos fraudulentos o simplemente haciendo la vista gorda. Las actividades de tráfico y trata de migrantes a menudo se llevan a cabo con la participación o colaboración de funcionarios estatales corruptos, y la corrupción y la colusión son generalmente una parte crítica de dichas operaciones. Además <span class="citation" data-cites="Brito">Renata Brito (<a href="#ref-Brito" role="doc-biblioref">2024</a>)</span> en <strong>““A decade of documenting more than 63,000 migrant deaths shows that fleeing is more lethal than ever”“</strong>indica que los guardacostas libios, formados y financiados por la UE, han sido vinculados con traficantes de personas que explotan a migrantes que son interceptados y devueltos a precarios centros de detención. Un grupo de expertos respaldado por la ONU ha concluido que los abusos cometidos contra los migrantes en el Mediterráneo y en Libia pueden constituir crímenes contra la humanidad.</p>
<p>Por otro lado <span class="citation" data-cites="APA">Association (<a href="#ref-APA" role="doc-biblioref">2024</a>)</span> en <strong>“Psychology of Immigration”</strong>presenta una serie de información médica y psicológica en aras de apoyar a servicios de apoyo a personas migrantes. La mayor parte del artículo consiste -además de proporcionar información precisa sobre trastornos mentales que pueden padecer personas inmigrantes- en señalar y enfatizar el tenso ambiente que pueden sufrir las personas que se enmarcan en la migración, ambiente que puede incluir: discriminación, xenofobia y violencia. Curiosamente, aporta también datos y desmiente mitos acerca de lo que significa la migración mundialmente hoy en día. Uno de estos mitos sería que la migración está en alza, lo cual no es cierto; sucede lo contrario. La <span class="citation" data-cites="WHO">Organization (<a href="#ref-WHO" role="doc-biblioref">2022</a>)</span> en <strong>““Act now to save lives and prevent migrants from going missing”“</strong>expone la importancia y/o necesidad de proteger a las personas migrantes de los peligros a los que se enfrentan a diario. No es solo una invitación ligera, sino una crítica directa a la situación actual, exigiendo mayor justicia por parte de los gobiernos y organizaciones sin fines de lucro. También expresa que existen práctica, conocimientos y orientación que pueden orientar los esfuerzos coordinados para hacer realidad los compromisos contraídos en virtud del derecho internacional y los objetivos del Pacto Mundial para la Migración. Los organismos internacionales, regionales y subregionales pueden desempeñar un papel importante para facilitar esos esfuerzos, junto con los agentes y las comunidades locales.</p>
<p><strong>Metodología:</strong>Inicialmente en <strong>“Introducción a la Estadística”</strong>de <span class="citation" data-cites="Zabala">Zabala (<a href="#ref-Zabala" role="doc-biblioref">2007</a>)</span>, aunque se presenta un estilo sumamente didáctico, se prioriza su contenido relativo a la exposición de conceptos de la matemática y estadística. Las medidas de centralización (o medidas de posición central) son métricas estadísticas que se encargan de mostrar el valor central distributivo. Por lo cual, se dedican a rastrear valores representativos del centro de un conjunto de datos. Las medidas a utilizar son:</p>
<ul>
<li><p>Media: Es el promedio de todos los datos de la muestra.</p></li>
<li><p>Mediana: Es el valor del medio de todos los datos ordenados de menor a mayor.</p></li>
<li><p>Moda: Valor más repetido del conjunto de datos.</p></li>
</ul>
<p>Desglosadas individualmente:</p>
<dl>
<dt>Media</dt>
<dd>
<p>Para calcular la media se deben sumar todos los valores y luego dividir entre el número total de datos. La media también se conoce como media aritmética o promedio. Además, la media de una distribución estadística es equivalente a su esperanza matemática.</p>
</dd>
<dt>Mediana</dt>
<dd>
<p>La mediana es el valor del medio de todos los datos ordenados de menor a mayor. Es decir, la mediana divide todo el conjunto de datos ordenados en dos partes iguales. El cálculo de la mediana depende de si el número total de datos es par o impar:</p>
</dd>
</dl>
<ul>
<li><p>Si el número total de datos es impar, la mediana será el valor que está justo en el medio de los datos. Es decir, el valor que está en la posición (n+1)/2 de los datos ordenados.</p></li>
<li><p>Si el número total de datos es par, la mediana será la media de los dos datos que están en el centro. Esto es, la media aritmética de los valores que están en la posiciones n/2 y n/2+1 de los datos ordenados.</p></li>
</ul>
<dl>
<dt>Moda</dt>
<dd>
<p>La moda (o moda estadística o valor modal) es el valor del conjunto de datos que tiene una mayor frecuencia absoluta, esto es, el valor que más se repite de un conjunto de datos. Así que, para calcular la moda de un conjunto de datos estadísticos basta con contar el número de veces que aparece cada dato en la muestra. Se pueden distinguir tres tipos de modas según el número de valores que están más repetidos:</p>
</dd>
</dl>
<ul>
<li><p>Moda unimodal: solo hay un valor con el máximo número de repeticiones. Por ejemplo, <span class="math display">\[1, 4, 2, 4, 5, 3\]</span>.</p></li>
<li><p>Moda bimodal: el máximo número de repeticiones se produce en dos valores diferentes y ambos valores se repiten el mismo número de veces. Por ejemplo, <span class="math display">\[2, 6, 7, 2, 3, 6, 9\]</span>.</p></li>
</ul>
<p>Moda multimodal: tres o más valores tienen el mismo número máximo de repeticiones. Por ejemplo, <span class="math display">\[3, 3, 4, 1, 3, 4, 2, 1, 4, 5, 2, 1\]</span>.</p>
<p><strong>Resultados: </strong>Al realizar una comparación entre el total de muertes en 2019 y 2021, se obtiene que en el 2019 el número total de incidentes migratorios fue de 1,422, con un total de 324 muertes reportadas. En contraste, para el año 2021, se documentaron 1,380 incidentes y 238 muertes. Aunque el número de incidentes no cambió sustancialmente, se subraya la información.</p>
<p>El descenso en el número de muertes en 2021 podría deberse a varios factores. Por ejemplo: medidas adoptadas debido a la pandemia que hayan afectado el comportamiento de los flujos migratorios. Por otro lado, el número de personas desempleadas aumentó de 1,777 en 2019 a 2,206 en 2021, lo que indica una mayor precarización de las condiciones laborales y sociales en los países de origen.</p>
<p>En este punto se observan patrones distintos entre los dos años. En 2019, las regiones con mayor número de incidentes fueron el Área Oeste/Central, la Zona del Norte y la Región del Este, con 489, 288, y 259 incidentes, respectivamente. En cuanto al 2021, los incidentes mostraron marcas en áreas metropolitanas, con 417 incidentes en la capital y 409 en el Norte del Norte, seguido por el Mediterráneo con 353 incidentes.</p>
<p>Como es también reflejado en las fichas bibliográficas, este tipo de problemáticas puede que signifique la intensificación de ciertos conflictos y condiciones socioeconómicas adversas en áreas urbanas, que atraen a más migrantes o son zonas de paso forzoso. Además de que usualmente estás áreas son tanto las más pobladas como las que suelen presentar eventos sociopolíticos. La elección de las rutas migratorias en 2021 podría haber sido impulsada por la búsqueda de empleo y seguridad.</p>
<p>En el 2019, las causas de muerte principales fueron asesinatos y accidentes vehiculares, con 213 y 208 casos respectivamente. Para 2021, las principales causas de muerte incluyeron asesinatos (431 casos), violencia intrafamiliar (256 casos), y condiciones socioeconómicas adversas (224 casos).</p>
<p>En 2019, como se describe, los accidentes vehiculares fueron una causa mayoritaria; con alta probabilidad podría determinarse que se debería a los medios de trasporte ilegales de los migrantes, (que carecen de poca seguridad), o accidentes de tránsito derivados de persecuciones. Para 2021, el aumento en casos de violencia intrafamiliar y condiciones socioeconómicas adversas podría estar relacionado con el impacto de la pandemia, que exacerbó las desigualdades y aumentó la vulnerabilidad de los migrantes.</p>
<p>Se observan unas tendencias en el número de migrantes desaparecidos, para comprender la variación en el número de desaparecidos a lo largo del tiempo, se llevó a cabo una regresión con el mes como variable independiente en los años 2019 y 2021.</p>
<p>En 2019, la pendiente positiva de 10.44 indica que el número de desaparecidos aumentaba en promedio en 10.44 personas cada mes, quizás impulsado por los flujos migratorios estacionales, como el verano en Europa. En 2021, aunque la pendiente fue menor (7.17 personas adicionales por mes), el número inicial de desaparecidos era considerablemente más alto (164.03), lo que sugiere que la pandemia podría haber incrementado la cifra base de desaparecidos.</p>
<p>Por lo que se generan ciertas implicaciones de las diferencias en causas de muerte y desaparecidos, los cambios en las causas de muerte entre el 2019 y 2021, especialmente el incremento en violencia intrafamiliar y condiciones socioeconómicas adversas, muestran una triste metamorfosis en los riesgos que enfrentan los migrantes en sus países de origen y durante su tránsito.</p>
<p>Estos fenómenos complejos pueden ser intensificados en contextos de crisis económica y social. Los migrantes suelen enfrentar situaciones de gran precariedad, que los exponen a una doble vulnerabilidad: por un lado, los riesgos inherentes a las rutas migratorias y, por otro, la posibilidad de enfrentar situaciones de violencia doméstica tanto en su país de origen como al país en que se trasladaron. Esto pone de relieve la importancia de las políticas públicas para la prevención de la violencia intrafamiliar y el apoyo psicosocial a migrantes en tránsito, en especial en tiempos de crisis.</p>
<p>Además, el incremento en el número de desaparecidos en los primeros meses de 2021 sugiere que, aunque se redujeron las muertes, los migrantes pueden estar enfrentando más riesgos asociados con el tráfico de personas o meramente la ilegalidad con la que se mueven.</p>
<p>El análisis de regresión lineal simple utilizado para explorar la relación entre el total de muertos y desaparecidos y el número de muertos, así como entre la región y el número de muertos, ha permitido identificar patrones básicos en los datos migratorios. Sin embargo, estos modelos lineales presentan numerosas limitaciones, ya que los procesos migratorios y sus riesgos son fenómenos altamente multifactoriales que interactúan con diversas variables sociales, económicas y políticas.</p>
<p>Estos hallazgos invitan a considerar la aplicación de modelos de regresión múltiple o análisis de varianza que incorporen factores adicionales, como políticas de control fronterizo, nivel socioeconómico, y condiciones climáticas, para obtener una perspectiva más robusta. A nivel social, la implementación de estos modelos puede contribuir a la creación de políticas que protejan a los migrantes y minimicen los riesgos inherentes a sus trayectorias.</p>
<p><strong>Conclusiones: </strong></p>
<p>La investigación desarrollada fue esencialmente un trabajo enfocado en establecer ciertos cálculos y modelos estadísticos en aras de establecer diferentes conexiones dentro del ámbito de la migración.</p>
<p>Se constituyó un marco teórico diverso; este compuesto de una serie de artículos investigativos, periodísticos, trabajos científicos, tesis universitarios y otros escritos completamente asociados al tema principal de este proyecto. Esto fue señalado y expuesto dentro de lo descrito como fichas bibliográficas y los enlaces.</p>
<p>En cuanto a la pregunta de investigación - la cual en términos generales intenta plantarse el hecho de, cuáles cálculos estadísticos pueden formularse para crear relaciones y entrelazar compuestos los cuales den explicaciones al tema de migración – se determina que, a pesar de medir y calcular diferentes datos, no es posible hacer inferencias y/o exponer resultados concretos que puedan solventar incógnitas que se pueden plantear referentes a la problemática de migración.</p>
<p>La metodología fue una gran brújula para navegar entre lo deseado a alcanzar teórica y estadísticamente en el proyecto. Esta se basó principalmente en los datos encontrados en la página: Migration Data Portal.</p>
<p>Los problemas que presenta la investigación es que necesita un enfoque estadístico más riguroso y un planeamiento más complejo si se desea alcanzar la meta de ser un trabajo clave que escarifique dudas que se exponen de manera usual sobre este tema.</p>
<p>Se recomienda utilizar una base matemática y estadística más fuerte para enfrentar un problema estadístico similar; también, se insta a establecer objetivos más precisos que no busquen abordar la información encontrada en artículos y teorizada en una UVE Heurística de manera elemental, si no más bien, de manera específica estructurar casos complejos que futuramente puedan ser resueltos y así llenar vacíos intelectuales sobre esta materia.</p>
<p><strong>Agradecimientos: </strong>Agradecimientos especiales a Maikol Solis, profesor del curso Herramientas para el Análisis de Datos, por su guía y dedicación a lo largo del semestre, así como a Ana Laura Lopez, asistente del curso, por su enorme apoyo en cada etapa del proceso. También se agradece a la Universidad de Costa Rica por asegurar un entorno académico que ha permitido el desarrollo de este proyecto.</p>
<p><strong>Referencias: </strong></p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-APA" class="csl-entry" role="listitem">
Association, American Psychological. 2024. <span>«Psychology of Immigration 101»</span>. <a href="https://www.apa.org/topics/immigration/immigration-psychology">https://www.apa.org/topics/immigration/immigration-psychology</a>.
</div>
<div id="ref-Duhaime" class="csl-entry" role="listitem">
Bernard Duhaime, Andréanne Thibault. 2018. <span>«Protection of migrants from enforced disappearance: A human rights perspective»</span>. <em>International Review of the Red Cross</em> 99 (2): 569-87. <a href="https://doi.org/10.1017/S1816383118000097">https://doi.org/10.1017/S1816383118000097</a>.
</div>
<div id="ref-Todd" class="csl-entry" role="listitem">
David Dorrell, Joseph Henderson, Georgeta Connor. 2024. <span>«Capítulo 3: Migration»</span>. En <em>Introduction to Human Geography</em>, editado por LOUIS: The Louisiana Library Network, 57-82. <a href="https://louis.pressbooks.pub/humangeography/chapter/3/">https://louis.pressbooks.pub/humangeography/chapter/3/</a>.
</div>
<div id="ref-probabilidadyestadistica3.0" class="csl-entry" role="listitem">
Desconocido, Autor. 2024. <span>«Regresión Lineal Simple»</span>. <a href="https://www.probabilidadyestadistica.net/regresion-lineal-simple/">https://www.probabilidadyestadistica.net/regresion-lineal-simple/</a>.
</div>
<div id="ref-migrationdataportal" class="csl-entry" role="listitem">
Migration Data Portal. 2024. <span>«Muertes y Desapariciones de Migrantes»</span>. <a href="https://www.migrationdataportal.org/es/themes/muertes-y-desapariciones-de-migrantes">https://www.migrationdataportal.org/es/themes/muertes-y-desapariciones-de-migrantes</a>.
</div>
<div id="ref-MinneapolisFed" class="csl-entry" role="listitem">
Minneapolis, Federal Reserve Bank of. 2023. <span>«The Causes and Consequences of the Missing Immigrants»</span>. <a href="https://www.minneapolisfed.org/article/2023/the-causes-and-consequences-of-the-missing-immigrants">https://www.minneapolisfed.org/article/2023/the-causes-and-consequences-of-the-missing-immigrants</a>.
</div>
<div id="ref-UN" class="csl-entry" role="listitem">
Nations, United. 2022. <span>«More than 50,000 migrants ’die in search of a better life’»</span>. <a href="https://news.un.org/en/story/2022/11/1130997">https://news.un.org/en/story/2022/11/1130997</a>.
</div>
<div id="ref-WHO" class="csl-entry" role="listitem">
Organization, World Health. 2022. <span>«Act now to save lives and prevent migrants from going missing»</span>. <a href="https://www.who.int/news/item/07-03-2022-act-now-to-save-lives-and-prevent-migrants-from-going-missing">https://www.who.int/news/item/07-03-2022-act-now-to-save-lives-and-prevent-migrants-from-going-missing</a>.
</div>
<div id="ref-Brito" class="csl-entry" role="listitem">
Renata Brito, Kerstin Sopke. 2024. <span>«A decade of documenting more than 63,000 migrant deaths shows that fleeing is more lethal than ever»</span>. <a href="https://apnews.com/article/migration-global-deaths-united-nations-9fba1b7019e6b1113b7e3e9ce751c0bb">https://apnews.com/article/migration-global-deaths-united-nations-9fba1b7019e6b1113b7e3e9ce751c0bb</a>.
</div>
<div id="ref-Zabala" class="csl-entry" role="listitem">
Zabala, Martín Andonegui. 2007. <span>«Las medidas de tendencia central»</span>. En <em>Introducción a la Estadística</em>, editado por Federación Internacional de Fe y Alegría, 18-26. <a href="https://scioteca.caf.com/bitstream/handle/123456789/527/69.pdf?sequence=1&amp;isAllowed=y">https://scioteca.caf.com/bitstream/handle/123456789/527/69.pdf?sequence=1&amp;isAllowed=y</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("google\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./bitacora-3.html" class="pagination-link" aria-label="Bitácora 3">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bitácora 3</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-/blob/main/bitacora-4.qmd" class="toc-action"><i class="bi bi-github"></i>Ver el código</a></li></ul></div></div></div></footer></body></html>