<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Bitácora 3 – Bitácoras Grupo #6, CA-204 (II-2024)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./bitacora-4.html" rel="next">
<link href="./bitacora-2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./bitacora-3.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bitácora 3</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bitácoras Grupo #6, CA-204 (II-2024)</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
    <a href="./Bitácoras-Grupo--6,-CA-204--II-2024-.pdf" title="Descargar PDF" class="quarto-navigation-tool px-1" aria-label="Descargar PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bitácora 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bitácora 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bitácora 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bitacora 4</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#parte-de-planificación" id="toc-parte-de-planificación" class="nav-link active" data-scroll-target="#parte-de-planificación"><span class="header-section-number">3.1</span> Parte de Planificación</a>
  <ul class="collapse">
  <li><a href="#análisis-de-modelación" id="toc-análisis-de-modelación" class="nav-link" data-scroll-target="#análisis-de-modelación"><span class="header-section-number">3.1.1</span> Análisis de Modelación</a></li>
  <li><a href="#construcción-de-fichas-de-resultados" id="toc-construcción-de-fichas-de-resultados" class="nav-link" data-scroll-target="#construcción-de-fichas-de-resultados"><span class="header-section-number">3.1.2</span> Construcción de fichas de resultados</a></li>
  <li><a href="#ordenamiento-de-los-elementos-del-reporte" id="toc-ordenamiento-de-los-elementos-del-reporte" class="nav-link" data-scroll-target="#ordenamiento-de-los-elementos-del-reporte"><span class="header-section-number">3.1.3</span> Ordenamiento de los elementos del reporte</a></li>
  </ul></li>
  <li><a href="#parte-de-escritura" id="toc-parte-de-escritura" class="nav-link" data-scroll-target="#parte-de-escritura"><span class="header-section-number">3.2</span> Parte de Escritura</a></li>
  <li><a href="#parte-de-reflexión" id="toc-parte-de-reflexión" class="nav-link" data-scroll-target="#parte-de-reflexión"><span class="header-section-number">3.3</span> Parte de reflexión</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-/blob/main/bitacora-3.qmd" class="toc-action"><i class="bi bi-github"></i>Ver el código</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bitácora 3</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<hr>
<hr>
<p>Para esta bitácora se añade un nuevo método: el modelo autorregresivo integrado de media móvil (ARIMA), además de nuevas fichas bibliográficas respecto al nuevo método.</p>
<p><strong>Título: ARIMA para la previsión de series temporales: Guía completa. <span class="citation" data-cites="Saadeddin">(<a href="#ref-Saadeddin" role="doc-biblioref">Saadeddin 2024</a>)</span></strong></p>
<ul>
<li><p>Autora: Zaina Saadeddin</p></li>
<li><p>Nombre del tema: “Cómo utilizar el modelo ARIMA”.</p></li>
<li><p>Forma de organizarlo:</p>
<ul>
<li><p>Cronológico: Sitio web actualizado el 2024.</p></li>
<li><p>Metodológico: El texto presenta un método cuantitativo para obtener previsiones de series temporales.</p></li>
<li><p>Temático: Estadístico</p></li>
<li><p>Teórico: Método matemático para el análisis de series temporales.</p></li>
</ul></li>
<li><p>Resumen en una oración: Qué es, cómo se compone y cómo utilizar el modelo ARIMA.</p></li>
<li><p>Argumento central: Se presentan el modelo ARIMA junto a sus componentes, además de explicar el código de cómo construir dicho modelo en R.</p></li>
<li><p>Problema con el argumento: Ninguno.</p></li>
<li><p>Resumen de un párrafo: El modelo autorregresivo integrado de media móvil (ARIMA) permite analizar series temporales para detectar ciertos patrones o tendencias que permitan formar previsiones exactas de series futuras, dicho modelo es principalmente de utilidad en áreas como las finanzas, la economía y en ciencias centradas en el medio ambiente. Además, se explican las series temporales en R y del paquete forecast y la función auto.arima()</p></li>
</ul>
<p><strong>Título: Modelos ARIMA para la predicción del gasto conjunto de oxígeno de vuelo y otros gases en el Ejército del Aire. <span class="citation" data-cites="SanidadMilitar">(<a href="#ref-SanidadMilitar" role="doc-biblioref">Gallego-Nicasio Moraleda 2018</a>)</span></strong></p>
<ul>
<li><p>Autores: Gallego-Nicasio Moraleda, Rodríguez Aranda, Mínguez Novella, Jiménez Pérez</p></li>
<li><p>Nombre del tema: “Análisis del gasto de oxígeno y otros gases para previsiones futuras”</p></li>
<li><p>Forma de organizarlo:</p>
<ul>
<li><p>Cronológico: Artículo publicado en el 2018.</p></li>
<li><p>Metodológico: El texto utiliza el método cuantitativo del modelo ARIMA.</p></li>
<li><p>Temático: Estadístico</p></li>
<li><p>Teórico: Ánálisis del gasto de diferentes gases del ejército aéreo de España para prever futuros gastos.</p></li>
</ul></li>
<li><p>Resumen en una oración: Se presenta una estimación matemática para la predicción económica del gasto en gases.</p></li>
<li><p>Argumento central: Se explica cómo se utilizó el modelo ARIMA para obtener previsiones sobre el gasto en gases, incluyendo la ecuación general y los diferentes componentes.</p></li>
<li><p>Problema con el argumento: Ninguno.</p></li>
<li><p>Resumen de un párrafo: El ejército aéreo de España ha presentado notables gastos en gases y elementos relacionados sen los últimos años, lo cual se debe a la falta de algún tipo de análisis matemático que presente un manejo óptimo del presupuesto asignado. Además este artículo presenta la ecuación general del modelo ARIMA, donde se explican diferentes componentes utilizados como el autorregresivo, el de media móvily el integrado junto el operador de retardo y sus coeficientes respectivos, además de tomar en cuenta el componente aleatorio.</p></li>
</ul>
<section id="parte-de-planificación" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="parte-de-planificación"><span class="header-section-number">3.1</span> Parte de Planificación</h2>
<section id="análisis-de-modelación" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="análisis-de-modelación"><span class="header-section-number">3.1.1</span> Análisis de Modelación</h3>
<p>Primero se cargan los datos recolectados del 2014 al 2022:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(countrycode)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>lista_archivos <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="at">X =</span> <span class="fu">dir</span>(<span class="at">path =</span> <span class="st">"data/"</span>), </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">FUN =</span> <span class="cf">function</span>(f){</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">read_csv</span>(<span class="fu">paste0</span>(<span class="st">"data/"</span>, f))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                           })</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(lista_archivos) <span class="sc">|&gt;</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span>   <span class="co">#separate_wider_delim(col, delim)</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(coordinates,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"latitud"</span>, <span class="st">"longitud"</span>),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">sep =</span> <span class="st">","</span>, <span class="at">fill =</span> <span class="st">"left"</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>latitud <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(migrantes_desaparecidos<span class="sc">$</span>latitud)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>longitud <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(migrantes_desaparecidos<span class="sc">$</span>longitud)<span class="co">#separa las coordenadas</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span> <span class="co">#extrae la fecha exacta</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">incident_date =</span> <span class="fu">as.Date</span>(</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_extract</span>(incident_date,</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>                <span class="st">"</span><span class="sc">\\</span><span class="st">b</span><span class="sc">\\</span><span class="st">d{2}/</span><span class="sc">\\</span><span class="st">d{2}/</span><span class="sc">\\</span><span class="st">d{4}</span><span class="sc">\\</span><span class="st">b"</span>), <span class="at">format =</span> <span class="st">"%m/%d/%Y"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos[ , <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">16</span>, <span class="dv">20</span><span class="sc">:</span><span class="dv">21</span>)] <span class="co">#elimina la columna 1</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">location_of_death =</span> <span class="fu">str_remove_all</span>(location_of_death, <span class="st">" </span><span class="sc">\\</span><span class="st">(see coordinates for exact location</span><span class="sc">\\</span><span class="st">)"</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span> <span class="co">#Extrae países y causas de muerte</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">country_of_death =</span> <span class="fu">countrycode</span>(location_of_death,</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>                          <span class="at">origin =</span> <span class="st">'country.name'</span>,</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>                          <span class="at">destination =</span> <span class="st">'country.name'</span>),</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">cause_of_death =</span> <span class="fu">str_extract</span>(cause_of_death, <span class="st">"^[^/]+"</span>),</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">region =</span> <span class="fu">str_extract</span>(region, </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"Asia|America|Africa|Europe|Caribbean|Mediterranean"</span>),</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">region =</span> <span class="fu">str_replace</span>(region, <span class="st">"Caribbean"</span>, <span class="st">"America"</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>cause_of_death <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(migrantes_desaparecidos<span class="sc">$</span>cause_of_death)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(migrantes_desaparecidos<span class="sc">$</span>region)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>migrantes_desaparecidos<span class="sc">$</span>country_of_death <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(migrantes_desaparecidos<span class="sc">$</span>country_of_death)</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>ts_muertes <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">muertes =</span> <span class="fu">sum</span>(number_dead, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>ts_muertes <span class="ot">&lt;-</span> <span class="fu">ts</span>(ts_muertes<span class="sc">$</span>muertes, <span class="at">start =</span> <span class="fu">min</span>(ts_muertes<span class="sc">$</span>year), <span class="at">end =</span> <span class="fu">max</span>(ts_muertes<span class="sc">$</span>year), <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>ts_sobrevivientes <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>    <span class="at">sobrevivientes =</span> <span class="fu">sum</span>(number_of_survivors, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>ts_sobrevivientes <span class="ot">&lt;-</span> <span class="fu">ts</span>(ts_sobrevivientes<span class="sc">$</span>sobrevivientes, </span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>                        <span class="at">start =</span> <span class="fu">min</span>(ts_sobrevivientes<span class="sc">$</span>year), </span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>                        <span class="at">end =</span> <span class="fu">max</span>(ts_sobrevivientes<span class="sc">$</span>year), </span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>                        <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>ts_desaparecidos <span class="ot">&lt;-</span> migrantes_desaparecidos <span class="sc">|&gt;</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>    <span class="at">desaparecidos =</span> <span class="fu">sum</span>(minimum_estimated_number_of_missing, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>ts_desaparecidos <span class="ot">&lt;-</span> <span class="fu">ts</span>(ts_desaparecidos<span class="sc">$</span>desaparecidos, </span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>                        <span class="at">start =</span> <span class="fu">min</span>(ts_desaparecidos<span class="sc">$</span>year), </span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>                        <span class="at">end =</span> <span class="fu">max</span>(ts_desaparecidos<span class="sc">$</span>year), </span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>                        <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(migrantes_desaparecidos)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 11,341
Columns: 17
$ incident_id                         &lt;chr&gt; "2014.MMP00001", "2014.MMP00002", …
$ region                              &lt;fct&gt; America, America, America, America…
$ incident_date                       &lt;date&gt; 2014-01-06, 2014-01-12, 2014-01-1…
$ year                                &lt;dbl&gt; 2014, 2014, 2014, 2014, 2014, 2014…
$ number_dead                         &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 12, 1, 1, 1, 1, …
$ minimum_estimated_number_of_missing &lt;dbl&gt; NA, NA, NA, NA, 0, NA, NA, NA, NA,…
$ number_of_survivors                 &lt;dbl&gt; NA, NA, NA, NA, 2, NA, NA, NA, NA,…
$ number_of_females                   &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 9, NA, NA,…
$ number_of_males                     &lt;dbl&gt; 1, NA, NA, 1, 1, NA, NA, NA, NA, N…
$ number_of_children                  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 3, NA, NA,…
$ cause_of_death                      &lt;fct&gt; Mixed or unknown, Mixed or unknown…
$ location_of_death                   &lt;chr&gt; "Pima Country Office of the Medica…
$ latitud                             &lt;dbl&gt; 31.650259, 31.597130, 31.940260, 3…
$ longitud                            &lt;dbl&gt; -110.3665, -111.7376, -113.0113, -…
$ migrantion_route                    &lt;chr&gt; "US-Mexico border crossing", "US-M…
$ source_quality                      &lt;dbl&gt; 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5…
$ country_of_death                    &lt;fct&gt; United States, United States, Unit…</code></pre>
</div>
</div>
<section id="método-1-regresión-lineal-simple-datos-2022" class="level4" data-number="3.1.1.1">
<h4 data-number="3.1.1.1" class="anchored" data-anchor-id="método-1-regresión-lineal-simple-datos-2022"><span class="header-section-number">3.1.1.1</span> Método #1: Regresión Lineal Simple (Datos 2022)</h4>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar datos</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/MissingMigrants-Global-2022.csv"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrando datos para la primera regresión</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>data_filtered <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Number.Dead, Total.Number.of.Dead.and.Missing) <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Regresión lineal simple: Número de muertos y Total de muertos y desaparecidos</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Number.Dead <span class="sc">~</span> Total.Number.of.Dead.and.Missing, <span class="at">data =</span> data_filtered)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Number.Dead ~ Total.Number.of.Dead.and.Missing, 
    data = data_filtered)

Residuals:
    Min      1Q  Median      3Q     Max 
-14.067  -0.329  -0.329  -0.329  16.825 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       1.14579    0.07027    16.3   &lt;2e-16 ***
Total.Number.of.Dead.and.Missing  0.18317    0.01065    17.2   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.807 on 773 degrees of freedom
Multiple R-squared:  0.2767,    Adjusted R-squared:  0.2757 
F-statistic: 295.7 on 1 and 773 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>slope1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(model1)[<span class="dv">2</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>intercept1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(model1)[<span class="dv">1</span>]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Modelo 1 - Pendiente: "</span>, slope1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo 1 - Pendiente:  0.183171 </code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Modelo 1 - Intercepto: "</span>, intercept1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo 1 - Intercepto:  1.145787 </code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para la segunda regresión, se codifican las regiones numéricamente</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>data_filtered_regions <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Region, Number.Dead) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>data_filtered_regions<span class="sc">$</span>Region_encoded <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">factor</span>(data_filtered_regions<span class="sc">$</span>Region))</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Regresión lineal simple: Regiones y Número de muertos</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Number.Dead <span class="sc">~</span> Region_encoded, <span class="at">data =</span> data_filtered_regions)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Number.Dead ~ Region_encoded, data = data_filtered_regions)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6988 -0.6988 -0.5889 -0.4425 20.3744 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     1.88193    0.17257  10.905   &lt;2e-16 ***
Region_encoded -0.03662    0.02078  -1.762   0.0784 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.12 on 773 degrees of freedom
Multiple R-squared:  0.004001,  Adjusted R-squared:  0.002713 
F-statistic: 3.105 on 1 and 773 DF,  p-value: 0.07842</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>slope2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(model2)[<span class="dv">2</span>]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>intercept2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(model2)[<span class="dv">1</span>]</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Modelo 2 - Pendiente: "</span>, slope2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo 2 - Pendiente:  -0.03662218 </code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Modelo 2 - Intercepto: "</span>, intercept2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo 2 - Intercepto:  1.881927 </code></pre>
</div>
</div>
<p><strong>Análisis de Regresión Lineal Simple</strong></p>
<p><strong>1. Relación entre el Total de Muertos y Desaparecidos y el Número de Muertos</strong></p>
<p>En este análisis del modelo, se buscó entender la relación entre el <strong>total de muertos y desaparecidos</strong> y el <strong>número de muertos</strong> en incidentes migratorios.</p>
<p>La ecuación de la regresión es la siguiente:</p>
<p><span class="math display">\[
\text{Número de muertos} = 1.1458 + 0.1832 \times (\text{Total de muertos y desaparecidos})
\]</span></p>
<p><strong>Interpretación de Resultados:</strong></p>
<ul>
<li><p><strong>Pendiente (<span class="math inline">\(\beta_1 = 0.1832\)</span>)</strong>: Por cada persona adicional en el total de muertos y desaparecidos, se espera que el número de muertos aumente en <strong>0.18 personas</strong>, en promedio.</p></li>
<li><p><strong>Intercepto (<span class="math inline">\(\beta_0 = 1.1458\)</span>)</strong>: Si el total de muertos y desaparecidos fuera cero, el modelo indica que el número estimado de muertos sería <strong>1.15 personas</strong>. Aunque es correcto, no necesariamente reflejo algo revelador, dado que un total de muertos y desaparecidos igual a 0 no implica migrantes fallecidos.</p></li>
</ul>
<p>Este modelo sugiere una relación positiva entre estas dos variables, lo que se espera, puesto que el número de muertos está relacionado con el total de muertos y desaparecidos en un incidente.</p>
<hr>
<p><strong>2. Relación entre la Región y el Número de Muertos</strong></p>
<p>En este análisis, las <strong>regiones</strong> se codificaron numéricamente y se realizó una regresión lineal simple para evaluar si el <strong>número de muertos</strong> cambia entre las distintas regiones.</p>
<p>La ecuación de la regresión es:</p>
<p><span class="math display">\[
\text{Número de muertos} = 1.3123 + 0.0774 \times (\text{Región codificada})
\]</span></p>
<p><strong>Interpretación de Resultados:</strong></p>
<ul>
<li><p><strong>Pendiente (<span class="math inline">\(\beta_1 = 0.0774\)</span>)</strong>: Indica que, en promedio, al cambiar de una región a otra (codificada numéricamente), el número de muertos aumenta en <strong>0.077 personas</strong>.</p></li>
<li><p><strong>Intercepto (<span class="math inline">\(\beta_0 = 1.3123\)</span>)</strong>: Cuando la región es la primera codificada, el número esperado de muertos es de <strong>1.31 personas</strong>.</p></li>
</ul>
<p>El modelo sugiere que hay diferencias leves en el número de muertos entre las regiones, sin ser un relación significativa. La pendiente es pequeña, lo que indica que el número de muertos no varía drásticamente entre las distintas regiones.</p>
<p><strong>Variables Importantes</strong></p>
<ul>
<li><strong>Region</strong>: Región donde ocurrió el incidente.</li>
<li><strong>Estado</strong>: Estado donde ocurrió el incidente.</li>
<li><strong>Nivel_inc</strong>: Nivel de impacto.</li>
<li><strong>Total_inc</strong>: Número de casos confirmados.</li>
<li><strong>Num_Fallecimientos</strong>: Número de fallecimientos.</li>
<li><strong>Num_Heridos</strong>: Número de heridos debido a incidentes de desempleo.</li>
<li><strong>Sector</strong>: Sector de trabajo en el que labora el afectado de manera directamente relacionada.</li>
<li><strong>Grupo_et</strong>: Clase de grupo étnico involucrado.</li>
<li><strong>Tipo_inc</strong>: Tipo de migración utilizada.</li>
</ul>
<p>Se describe el análisis:</p>
<ol type="1">
<li>Análisis descriptivo comparativo para identificar las principales diferencias entre 2019 y 2021.</li>
</ol>
<p><strong>Análisis descriptivo comparativo de los incidentes migratorios en 2019 y 2021</strong></p>
<p>Resumen general de los incidentes:</p>
<p>2019: - Total de incidentes: 1422 - Total de muertes: 324 - Total de desempleados: 1777 - Total de muertes y desempleados: 5,481</p>
<p>2021: - Total de incidentes: 1380 - Total de muertes: 238 - Total de desempleados: 2,206 - Total de muertes y desempleados: 5,146</p>
<p>Interpretación: Aunque algunos de los incidentes aumentan levemente en el 2021, se observa una reducción en el número de muertes en comparación con 2019.</p>
<hr>
<p><strong>Distribución regional de los incidentes:</strong></p>
<p>Regiones con mayor número de incidentes en 2019: 1. Área Oeste/Central: 489 2. Zona del Norte: 288 3. Región del Este: 259 4. Península del Norte: 169</p>
<p>Regiones con mayor número de incidentes en 2021: 1. Área Metropolitana: 417 2. Norte del Norte: 409 3. Mediterráneo: 353</p>
<p>Interpretación: En 2019, las áreas urbanas (particularmente Occidental y Norte) destacan los incidentes migratorios; sin embargo, en 2021, las áreas metropolitanas muestran un incremento considerable en la cantidad de incidentes.</p>
<hr>
<p><strong>Principales causas de muerte:</strong> Asesinatos: 213 Accidentes vehiculares: 208</p>
<p>2021: Asesinatos: 431 Violencia intrafamiliar: 256 Condiciones socioeconómicas adversas: 224</p>
<p>Conclusión: Ambos años, los asesinatos fueron las causas principales de muerte.</p>
<p><strong>Análisis de regresión temporal: Relación entre el mes y los desaparecidos</strong></p>
<p>Se realizó una regresión lineal para los años 2019 y 2021 con el objetivo de evaluar si existe una tendencia en el número de desaparecidos a lo largo del tiempo, utilizando el mes como variable independiente.</p>
<p><strong>Ecuaciones de regresión</strong></p>
<p>2019: - Desaparecidos = 80.34 + 10.44 × (Mes) - Pendiente: 10.44 - Intercepto: 80.24</p>
<p>2021: - Desaparecidos = 164.03 + 7.17 × (Mes) - Pendiente: 7.17 - Intercepto: 164.03</p>
<p>Interpretación de los resultados</p>
<p>2019: - La pendiente positiva indica que el número de desaparecidos aumentó progresivamente cada mes en 2019, en promedio 10.44 personas más por mes. - La información sugiere un aumento gradual de desaparecidos a lo largo del año, probablemente por el crecimiento debido a los movimientos migratorios y factores estacionales (como el verano en Europa).</p>
<p>2021: - En 2021 también se observa una pendiente positiva, pero más baja (7.17 personas adicionales por mes). - El intercepto más alto (164.03) refleja un número inicial de desaparecidos más alto, lo que podría indicar que la pandemia impactó desde el inicio, con más personas tomando rutas peligrosas a lo largo del año.</p>
</section>
</section>
<section id="construcción-de-fichas-de-resultados" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="construcción-de-fichas-de-resultados"><span class="header-section-number">3.1.2</span> Construcción de fichas de resultados</h3>
<ul>
<li><p><strong>6. Nombre de su hallazgo/resultado: Incidentes totales en 2019 y 2021.</strong></p></li>
<li><p><strong>Resumen en una oración</strong>: Se registraron 1,422 incidentes en 2019 y 1,380 en 2021.</p></li>
<li><p><strong>Principal característica</strong>: Pequeña dismuninución en la cantidad de incidentes entre los dos años.</p></li>
<li><p><strong>Problemas o posibles desafíos</strong>: La diferencia en los incidentes podría estar influenciada por factores externos como la pandemia de COVID, con lo cual se requiere contextualizar los datos.</p></li>
<li><p><strong>Resumen en un párrafo</strong>: En el análisis de los incidentes entre 2019 y 2021, se observa una ligera reducción en la cantidad total. Esto podría estar relacionado con variaciones en patrones migratorios y factores socioeconómicos como los causados por la pandemia. A pesar de la disminución en el total, otros factores muestran tendencias significativas que ameritan un análisis detallado.</p></li>
<li><p><strong>7. Nombre de su hallazgo/resultado: Variables clave en el análisis de incidentes migratorios</strong></p></li>
<li><p><strong>Resumen en una oración</strong>: Se identificaron variables importantes relacionadas con la ubicación, impacto, consecuencias y características de los incidentes migratorios.</p></li>
<li><p><strong>Principal característica</strong>: Las variables recolectaron información detallada sobre la región, estado, nivel de impacto, y consecuencias como muertes, heridos y desempleo, lo cual permite un análisis exhaustivo de cada incidente.</p></li>
<li><p><strong>Problemas o posibles desafíos</strong>: La complejidad de las variables y la variabilidad en los datos podrían tergiversan una información uniforme, especialmente en comparación interanual.</p></li>
<li><p><strong>Resumen en un párrafo</strong>: En el análisis de incidentes migratorios, se definieron variables clave que permiten categorizar y analizar cada caso con detalle. Estas incluyen información sobre la ubicación geográfica (región y estado), el nivel de impacto, la cantidad de incidentes confirmados, y las consecuencias en términos de fallecimientos, heridos y desempleo. También se consideran el sector de trabajo de los afectados, el grupo étnico involucrado, y el tipo de migración, lo cual facilita identificar patrones y diferencias significativas entre los años 2019 y 2021.</p></li>
<li><p><strong>8. Nombre de su hallazgo/resultado: Relación entre el Total de Muertos y Desaparecidos y el Número de Muertos</strong></p></li>
<li><p><strong>Resumen en una oración</strong>: Se encontró una relación positiva entre el total de muertos y desaparecidos y el número de muertos en incidentes migratorios.</p></li>
<li><p><strong>Principal característica</strong>: La pendiente de la regresión indica que, en promedio, por cada persona adicional en el total de muertos y desaparecidos, el número de muertos aumenta en 0.18 personas.</p></li>
<li><p><strong>Problemas o posibles desafíos</strong>: La interpretación del intercepto es sumamente significativa.</p></li>
<li><p><strong>Resumen en un párrafo</strong>: El análisis de regresión entre el total de muertos y desaparecidos y el número de muertos revela una relación positiva esperada, con una pendiente que sugiere que, por cada persona adicional en el total de muertos y desaparecidos, el número de muertos se incrementa en aproximadamente 0.18 personas.</p></li>
<li><p><strong>9. Nombre de su hallazgo/resultado: Relación entre la Región y el Número de Muertos</strong></p></li>
<li><p><strong>Resumen en una oración</strong>: Se observan diferencias leves en el número de muertos entre regiones, pero la relación no es significativa.</p></li>
<li><p><strong>Principal característica</strong>: La pendiente de 0.0774 indica un aumento leve en el número de muertos al pasar de una región a otra.</p></li>
<li><p><strong>Problemas o posibles desafíos</strong>: La pequeña pendiente sugiere que las variaciones en el número de muertos entre regiones no son relevantes, limitando la utilidad del modelo para identificar diferencias significativas.</p></li>
<li><p><strong>Resumen en un párrafo</strong>: El análisis de regresión que relaciona las regiones (codificadas numéricamente) y el número de muertos muestra una pendiente baja (0.0774), lo que sugiere diferencias leves en el número de muertos al cambiar de una región a otra. Aunque el modelo sugiere una ligera variación, esta no es significativa y no refleja una diferencia drástica entre las regiones. El intercepto de 1.31 indica el número esperado de muertos en la primera región codificada. En conclusión, aunque hay una relación entre la región y el número de muertos, esta no es suficiente para ser estadísticamente relevante.</p></li>
</ul>
<hr>
<p><strong>Conclusión del análisis de regresión</strong></p>
<p>Ambos años muestran un aumento mensual en los desaparecidos, pero la magnitud es menor en 2021. Esto podría reflejar que la pandemia cambió los patrones migratorios, haciendo que desde el inicio del año haya un número elevado, aunque el aumento mensual fuera más moderado en comparación con 2019.</p>
</section>
<section id="ordenamiento-de-los-elementos-del-reporte" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="ordenamiento-de-los-elementos-del-reporte"><span class="header-section-number">3.1.3</span> Ordenamiento de los elementos del reporte</h3>
<p>Se dividen los elementos principales de la investigación en primarios y secundarios como se muestra en la siguientes tabla:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 67%">
</colgroup>
<thead>
<tr class="header">
<th>Primarios</th>
<th>Secundarios</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Las medidas de tendencia central</td>
<td>Implicaciones de la desaparición de inmigrantes</td>
</tr>
<tr class="even">
<td>Cómo utilizar el modelo ARIMA</td>
<td>Aspectos psicológicos de la inmigración</td>
</tr>
<tr class="odd">
<td>Análisis de regresión lineal simple</td>
<td>Importancia de los datos migratorios para modelar y formar correctas políticas</td>
</tr>
<tr class="even">
<td>Geografía de la migración</td>
<td>Protección de migrantes de desapariciones forzadas</td>
</tr>
<tr class="odd">
<td>Predicción de muertes de migrantes</td>
<td>Comparación de muertes y rescates de migrantes</td>
</tr>
<tr class="even">
<td>Predicción de sobrevivientes migrantes</td>
<td></td>
</tr>
<tr class="odd">
<td>Predicción de desapariciones de migrantes</td>
<td></td>
</tr>
</tbody>
</table>
<p>Ahora se ordenan los elementos por sección:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 79%">
</colgroup>
<thead>
<tr class="header">
<th>Sección</th>
<th>Temas a tratar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Introducción</td>
<td>1. Geografía de la migración (principal)<br>2. Importancia de los datos migratorios para modelar y formar correctas políticas (secundario)<br>3. Aspectos psicológicos de la inmigración (secundario)<br>4. Protección de migrantes de desapariciones forzadas (secundario)</td>
</tr>
<tr class="even">
<td>Metodología</td>
<td>1. Las medidas de tendencia central (principal)<br>2. Análisis de regresión lineal simple (principal)<br>3. Cómo utilizar el modelo ARIMA (principal)</td>
</tr>
<tr class="odd">
<td>Resultados</td>
<td>1. Predicción de muertes de migrantes (principal)<br>2. Predicción de sobrevivientes migrantes (principal)<br>3. Predicción de desapariciones de migrantes (principal)<br>4. Comparación de muertes y rescates de migrantes (secundario)<br>5. Implicaciones de la desaparición de inmigrantes (secundario)</td>
</tr>
</tbody>
</table>
<div class="page-break">

</div>
</section>
</section>
<section id="parte-de-escritura" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="parte-de-escritura"><span class="header-section-number">3.2</span> Parte de Escritura</h2>
<p>Se ha realizado un estudio sobre las desapariciones de migrantes hacia otro país donde se analizan los casos reportados en los últimos 10 años, donde se han determinado ciertos patrones, tendencias y posibles motivos o factores que influyen en que ocurran dichos sucesos. La importancia de esta investigación recae en un problema social en el cuál los migrantes se encuentran en situaciones vulnerables donde se dan abusos, explotación, violencia, entre otras que conllevan a la desaparición de millones de personas o incluso que enfrenten la muerte. Tener conciencia sobre dicha problemática permite visualizar las violaciones contra los derechos humanos y empezar a protegerlos. Además se puede indagar acerca de que eventos generan estas migraciones como situaciones de pobreza, persecución, conflictos, entre otros y comprender las necesidades humanitarias que deben ser atentidas con urgencia.</p>
<p><span class="citation" data-cites="Todd">David Dorrell (<a href="#ref-Todd" role="doc-biblioref">2024</a>)</span> en <strong>“Introduction to Human Geography”</strong> se dedica a explicar la relación entre los migrantes y los factores geográficos. Por ejemplo: el autor explica por qué los migrantes eligen unos países y no otros, qué tienen que ver las rutas con los destinos de estas personas, y cómo fenómenos naturales y/o meteorológicos afectan a quienes se embarcan en dichas odiseas. Los geógrafos han identificado tendencias generales en la migración global, también conocida como migración Norte-Sur, en la que la mayoría de los emigrantes provienen de países más pobres y en desarrollo, mientras que la mayoría de los destinos han sido tradicionalmente países más ricos y desarrollados. Para la mayoría de los estadounidenses y canadienses, este patrón es muy familiar, ya que en las últimas décadas se ha visto un número sin precedentes de latinos inmigrar a Estados Unidos en busca de empleos mejor remunerados y mejores oportunidades, además de escapar de la pobreza estructural en el mundo en desarrollo. De manera similar, los patrones recientes en Europa han mostrado un número récord de europeos del Este mudándose al oeste y norte para ganar salarios más altos que los disponibles en sus países de origen. El cambio climático y el desplazamiento por desastres son las crisis definitorias de nuestro tiempo. Países enteros ya están sufriendo los impactos de emergencias relacionadas con el clima, pero las personas vulnerables que viven en las regiones más frágiles y pobres son las más afectadas de manera desproporcionada y se ven obligadas a moverse.</p>
<p>Gracias a <span class="citation" data-cites="migrationdataportal">Migration Data Portal (<a href="#ref-migrationdataportal" role="doc-biblioref">2024</a>)</span> se tiene el Proyecto Migrantes Desaparecidos de la OIM es la única base de datos que recopila datos sobre muertes de migrantes. Las fuentes de datos que se emplean varían según la disponibilidad en cada región. Por ejemplo, en la región del Mediterráneo, el personal local de la OIM transmite datos cuando asiste a los sobrevivientes en los puntos de desembarco en Libia. En la frontera entre Estados Unidos y México, los datos se compilan en base a datos de los médicos forenses y las oficinas de los alguaciles de los condados de Estados Unidos, las agencias de búsqueda y rescate (SAR) mexicanas y fuentes de los medios de comunicación. En la Encuesta sobre la travesía del desierto del Sahara, se incluyen datos de la Matriz de Seguimiento de Desplazamientos (DTM) de la OIM. Las estimaciones en otras regiones se basan en una combinación de fuentes oficiales, datos de la OIM y otros organismos de las Naciones Unidas, datos de organizaciones de la sociedad civil y, principalmente, informes de los medios de comunicación.</p>
<p>Así <span class="citation" data-cites="UN">Nations (<a href="#ref-UN" role="doc-biblioref">2022</a>)</span> en <strong>“More than 50,000 migrants ‘die in search of a better life’”</strong> expone que más de la mitad de las 50.000 muertes individuales documentadas ocurrieron en rutas hacia y dentro de Europa, y las rutas mediterráneas se cobraron al menos 25.104 vidas. Las rutas europeas también representan el mayor número y la mayor proporción de migrantes desaparecidos o presuntamente muertos, con al menos 16.032 desaparecidos en el mar y cuyos restos nunca se han recuperado. África es la segunda región más mortal para las personas en movimiento, con más de 9.000 muertes relacionadas con la migración documentadas desde 2014. Las encuestas regionales de hogares indican que estas cifras son casi con certeza muy inferiores a las reales.</p>
<p>También <span class="citation" data-cites="MinneapolisFed">Minneapolis (<a href="#ref-MinneapolisFed" role="doc-biblioref">2023</a>)</span> discute la gran problemática que acarrea la inmigración, no el hecho de que se dé, sino más bien los efectos negativos que implican que en los últimos años haya cada vez menos migración, principalmente en los incidentes ocurridos en Norteamérica el congreso legislativo estadounidense no ha estado activo en lo que políticas de inmigración se refiere. En cambio, es el poder ejecutivo el que estado dándole más forma a esta área social; el problema radica en que quien está en la presidencia posee un gran número de limitaciones; generando así un incierto acerca de la política de inmigración. Esencialmente, la autora explica en qué afecta que cada vez menos personas emigren a los Estados Unidos. A diferencia de lo que se cree, los inmigrantes no son causa directa del crimen, la saturación de plazas de trabajo, o cualquier otro elemento disuasorio. Más bien, que haya menos migrantes en los Estados Unidos ha significado un debilitamiento en su economía, lo cual ya está mostrando signos. La autora finalmente hace un llamado para que se pongan en marcha legislaciones que favorezcan el paso de migrantes a Estados Unidos. Dado que problemas como inflación y aumento de la pobreza son implicaciones de la falta de migración, es imperativo manejar esta problemática.</p>
<p>Entre algunas de las principales causas de la migración, según <span class="citation" data-cites="Duhaime">Bernard Duhaime (<a href="#ref-Duhaime" role="doc-biblioref">2018</a>)</span>, es tiene la existencia de agentes del Estado que pueden ser ellos mismos contrabandistas o traficantes, organizando el tráfico o trata de migrantes, facilitando la migración indocumentada o posibilitando la estancia de migrantes irregulares. En otras ocasiones, participan indirectamente en actividades de tráfico y trata de migrantes llevadas a cabo por actores privados, facilitando operaciones, permitiendo la entrada de migrantes indocumentados, proporcionando documentos fraudulentos o simplemente haciendo la vista gorda. Las actividades de tráfico y trata de migrantes a menudo se llevan a cabo con la participación o colaboración de funcionarios estatales corruptos, y la corrupción y la colusión son generalmente una parte crítica de dichas operaciones. Además <span class="citation" data-cites="Brito">Renata Brito (<a href="#ref-Brito" role="doc-biblioref">2024</a>)</span> en <strong>““A decade of documenting more than 63,000 migrant deaths shows that fleeing is more lethal than ever”“</strong> indica que los guardacostas libios, formados y financiados por la UE, han sido vinculados con traficantes de personas que explotan a migrantes que son interceptados y devueltos a precarios centros de detención. Un grupo de expertos respaldado por la ONU ha concluido que los abusos cometidos contra los migrantes en el Mediterráneo y en Libia pueden constituir crímenes contra la humanidad.</p>
<p>Por otro lado <span class="citation" data-cites="APA">Association (<a href="#ref-APA" role="doc-biblioref">2024</a>)</span> en <strong>“Psychology of Immigration”</strong> presenta una serie de información médica y psicológica en aras de apoyar a servicios de apoyo a personas migrantes. La mayor parte del artículo consiste -además de proporcionar información precisa sobre trastornos mentales que pueden padecer personas inmigrantes- en señalar y enfatizar el tenso ambiente que pueden sufrir las personas que se enmarcan en la migración, ambiente que puede incluir: discriminación, xenofobia y violencia. Curiosamente, aporta también datos y desmiente mitos acerca de lo que significa la migración mundialmente hoy en día. Uno de estos mitos sería que la migración está en alza, lo cual no es cierto; sucede lo contrario. La <span class="citation" data-cites="WHO">Organization (<a href="#ref-WHO" role="doc-biblioref">2022</a>)</span> en <strong>““Act now to save lives and prevent migrants from going missing”“</strong> expone la importancia y/o necesidad de proteger a las personas migrantes de los peligros a los que se enfrentan a diario. No es solo una invitación ligera, sino una crítica directa a la situación actual, exigiendo mayor justicia por parte de los gobiernos y organizaciones sin fines de lucro. También expresa que existen práctica, conocimientos y orientación que pueden orientar los esfuerzos coordinados para hacer realidad los compromisos contraídos en virtud del derecho internacional y los objetivos del Pacto Mundial para la Migración. Los organismos internacionales, regionales y subregionales pueden desempeñar un papel importante para facilitar esos esfuerzos, junto con los agentes y las comunidades locales.</p>
<p>Para la metodología, inicialmente en <strong>“Introducción a la Estadística”</strong> aunque se presenta un estilo sumamente didáctico, se prioriza su contenido relativo a la exposición de conceptos de la matemática y estadística. Las medidas de centralización (o medidas de posición central) son métricas estadísticas que se encargan de mostrar el valor central distributivo. Por lo cual, se dedican a rastrear valores representativos del centro de un conjunto de datos. Las medidas a utilizar son:</p>
<ul>
<li><p>Media: Es el promedio de todos los datos de la muestra.</p></li>
<li><p>Mediana: Es el valor del medio de todos los datos ordenados de menor a mayor.</p></li>
<li><p>Moda: Valor más repetido del conjunto de datos.</p></li>
</ul>
<p>Desglosadas individualmente:</p>
<dl>
<dt>Media</dt>
<dd>
<p>Para calcular la media se deben sumar todos los valores y luego dividir entre el número total de datos. La media también se conoce como media aritmética o promedio. Además, la media de una distribución estadística es equivalente a su esperanza matemática.</p>
</dd>
<dt>Mediana</dt>
<dd>
<p>La mediana es el valor del medio de todos los datos ordenados de menor a mayor. Es decir, la mediana divide todo el conjunto de datos ordenados en dos partes iguales. El cálculo de la mediana depende de si el número total de datos es par o impar:</p>
</dd>
</dl>
<ul>
<li><p>Si el número total de datos es impar, la mediana será el valor que está justo en el medio de los datos. Es decir, el valor que está en la posición (n+1)/2 de los datos ordenados.</p></li>
<li><p>Si el número total de datos es par, la mediana será la media de los dos datos que están en el centro. Esto es, la media aritmética de los valores que están en la posiciones n/2 y n/2+1 de los datos ordenados.</p></li>
</ul>
<dl>
<dt>Moda</dt>
<dd>
<p>La moda (o moda estadística o valor modal) es el valor del conjunto de datos que tiene una mayor frecuencia absoluta, esto es, el valor que más se repite de un conjunto de datos. Así que, para calcular la moda de un conjunto de datos estadísticos basta con contar el número de veces que aparece cada dato en la muestra. Se pueden distinguir tres tipos de modas según el número de valores que están más repetidos:</p>
</dd>
</dl>
<ul>
<li><p>Moda unimodal: solo hay un valor con el máximo número de repeticiones. Por ejemplo, <span class="math display">\[1, 4, 2, 4, 5, 3\]</span>.</p></li>
<li><p>Moda bimodal: el máximo número de repeticiones se produce en dos valores diferentes y ambos valores se repiten el mismo número de veces. Por ejemplo, <span class="math display">\[2, 6, 7, 2, 3, 6, 9\]</span>.</p></li>
</ul>
<p>Moda multimodal: tres o más valores tienen el mismo número máximo de repeticiones. Por ejemplo, <span class="math display">\[3, 3, 4, 1, 3, 4, 2, 1, 4, 5, 2, 1\]</span>.</p>
<p>Al realizar una comparación entre el total de muertes en 2019 y 2021, se obtiene que en el 2019 el número total de incidentes migratorios fue de 1,422, con un total de 324 muertes reportadas. En contraste, para el año 2021, se documentaron 1,380 incidentes y 238 muertes. Aunque el número de incidentes no cambió sustancialmente, se subraya la información.</p>
<p>El descenso en el número de muertes en 2021 podría deberse a varios factores. Por ejemplo: medidas adoptadas debido a la pandemia que hayan afectado el comportamiento de los flujos migratorios. Por otro lado, el número de personas desempleadas aumentó de 1,777 en 2019 a 2,206 en 2021, lo que indica una mayor precarización de las condiciones laborales y sociales en los países de origen.</p>
<p>En este punto se observan patrones distintos entre los dos años. En 2019, las regiones con mayor número de incidentes fueron el Área Oeste/Central, la Zona del Norte y la Región del Este, con 489, 288, y 259 incidentes, respectivamente. En cuanto al 2021, los incidentes mostraron marcas en áreas metropolitanas, con 417 incidentes en la capital y 409 en el Norte del Norte, seguido por el Mediterráneo con 353 incidentes.</p>
<p>Como es también reflejado en las fichas bibliográficas, este tipo de problemáticas puede que signifique la intensificación de ciertos conflictos y condiciones socioeconómicas adversas en áreas urbanas, que atraen a más migrantes o son zonas de paso forzoso. Además de que usualmente estás áreas son tanto las más pobladas como las que suelen presentar eventos sociopolíticos. La elección de las rutas migratorias en 2021 podría haber sido impulsada por la búsqueda de empleo y seguridad.</p>
<p>En el 2019, las causas de muerte principales fueron asesinatos y accidentes vehiculares, con 213 y 208 casos respectivamente. Para 2021, las principales causas de muerte incluyeron asesinatos (431 casos), violencia intrafamiliar (256 casos), y condiciones socioeconómicas adversas (224 casos).</p>
<p>En 2019, como se describe, los accidentes vehiculares fueron una causa mayoritaria; con alta probabilidad podría determinarse que se debería a los medios de trasporte ilegales de los migrantes, (que carecen de poca seguridad), o accidentes de tránsito derivados de persecuciones. Para 2021, el aumento en casos de violencia intrafamiliar y condiciones socioeconómicas adversas podría estar relacionado con el impacto de la pandemia, que exacerbó las desigualdades y aumentó la vulnerabilidad de los migrantes.</p>
<p>Se observan unas tendencias en el número de migrantes desaparecidos, para comprender la variación en el número de desaparecidos a lo largo del tiempo, se llevó a cabo una regresión con el mes como variable independiente en los años 2019 y 2021.</p>
<p>En 2019, la pendiente positiva de 10.44 indica que el número de desaparecidos aumentaba en promedio en 10.44 personas cada mes, quizás impulsado por los flujos migratorios estacionales, como el verano en Europa. En 2021, aunque la pendiente fue menor (7.17 personas adicionales por mes), el número inicial de desaparecidos era considerablemente más alto (164.03), lo que sugiere que la pandemia podría haber incrementado la cifra base de desaparecidos.</p>
<p>Por lo que se generan ciertas implicaciones de las diferencias en causas de muerte y desaparecidos, los cambios en las causas de muerte entre el 2019 y 2021, especialmente el incremento en violencia intrafamiliar y condiciones socioeconómicas adversas, muestran una triste metamorfosis en los riesgos que enfrentan los migrantes en sus países de origen y durante su tránsito.</p>
<p>Estos fenómenos complejos pueden ser intensificados en contextos de crisis económica y social. Los migrantes suelen enfrentar situaciones de gran precariedad, que los exponen a una doble vulnerabilidad: por un lado, los riesgos inherentes a las rutas migratorias y, por otro, la posibilidad de enfrentar situaciones de violencia doméstica tanto en su país de origen como al país en que se trasladaron. Esto pone de relieve la importancia de las políticas públicas para la prevención de la violencia intrafamiliar y el apoyo psicosocial a migrantes en tránsito, en especial en tiempos de crisis.</p>
<p>Además, el incremento en el número de desaparecidos en los primeros meses de 2021 sugiere que, aunque se redujeron las muertes, los migrantes pueden estar enfrentando más riesgos asociados con el tráfico de personas o meramente la ilegalidad con la que se mueven.</p>
</section>
<section id="parte-de-reflexión" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="parte-de-reflexión"><span class="header-section-number">3.3</span> Parte de reflexión</h2>
<p>El análisis de regresión lineal simple utilizado para explorar la relación entre el total de muertos y desaparecidos y el número de muertos, así como entre la región y el número de muertos, ha permitido identificar patrones básicos en los datos migratorios. Sin embargo, estos modelos lineales presentan numerosas limitaciones, ya que los procesos migratorios y sus riesgos son fenómenos altamente multifactoriales que interactúan con diversas variables sociales, económicas y políticas.</p>
<p>Estos hallazgos invitan a considerar la aplicación de modelos de regresión múltiple o análisis de varianza que incorporen factores adicionales, como políticas de control fronterizo, nivel socioeconómico, y condiciones climáticas, para obtener una perspectiva más robusta. A nivel social, la implementación de estos modelos puede contribuir a la creación de políticas que protejan a los migrantes y minimicen los riesgos inherentes a sus trayectorias.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-APA" class="csl-entry" role="listitem">
Association, American Psychological. 2024. <span>«Psychology of Immigration 101»</span>. <a href="https://www.apa.org/topics/immigration/immigration-psychology">https://www.apa.org/topics/immigration/immigration-psychology</a>.
</div>
<div id="ref-Duhaime" class="csl-entry" role="listitem">
Bernard Duhaime, Andréanne Thibault. 2018. <span>«Protection of migrants from enforced disappearance: A human rights perspective»</span>. <em>International Review of the Red Cross</em> 99 (2): 569-87. <a href="https://doi.org/10.1017/S1816383118000097">https://doi.org/10.1017/S1816383118000097</a>.
</div>
<div id="ref-Todd" class="csl-entry" role="listitem">
David Dorrell, Joseph Henderson, Georgeta Connor. 2024. <span>«Capítulo 3: Migration»</span>. En <em>Introduction to Human Geography</em>, editado por LOUIS: The Louisiana Library Network, 57-82. <a href="https://louis.pressbooks.pub/humangeography/chapter/3/">https://louis.pressbooks.pub/humangeography/chapter/3/</a>.
</div>
<div id="ref-SanidadMilitar" class="csl-entry" role="listitem">
Gallego-Nicasio Moraleda, Mínguez Novella, Rodríguez Aranda. 2018. <span>«Modelos ARIMA para la predicción del gasto conjunto de oxígeno de vuelo y otros gases en el Ejército del Aire»</span>. <em>Madrid</em> 74 (4): 1887-8571. <a href="https://doi.org/10.4321/s1887-85712018000400002">https://doi.org/10.4321/s1887-85712018000400002</a>.
</div>
<div id="ref-migrationdataportal" class="csl-entry" role="listitem">
Migration Data Portal. 2024. <span>«Muertes y Desapariciones de Migrantes»</span>. <a href="https://www.migrationdataportal.org/es/themes/muertes-y-desapariciones-de-migrantes">https://www.migrationdataportal.org/es/themes/muertes-y-desapariciones-de-migrantes</a>.
</div>
<div id="ref-MinneapolisFed" class="csl-entry" role="listitem">
Minneapolis, Federal Reserve Bank of. 2023. <span>«The Causes and Consequences of the Missing Immigrants»</span>. <a href="https://www.minneapolisfed.org/article/2023/the-causes-and-consequences-of-the-missing-immigrants">https://www.minneapolisfed.org/article/2023/the-causes-and-consequences-of-the-missing-immigrants</a>.
</div>
<div id="ref-UN" class="csl-entry" role="listitem">
Nations, United. 2022. <span>«More than 50,000 migrants ’die in search of a better life’»</span>. <a href="https://news.un.org/en/story/2022/11/1130997">https://news.un.org/en/story/2022/11/1130997</a>.
</div>
<div id="ref-WHO" class="csl-entry" role="listitem">
Organization, World Health. 2022. <span>«Act now to save lives and prevent migrants from going missing»</span>. <a href="https://www.who.int/news/item/07-03-2022-act-now-to-save-lives-and-prevent-migrants-from-going-missing">https://www.who.int/news/item/07-03-2022-act-now-to-save-lives-and-prevent-migrants-from-going-missing</a>.
</div>
<div id="ref-Brito" class="csl-entry" role="listitem">
Renata Brito, Kerstin Sopke. 2024. <span>«A decade of documenting more than 63,000 migrant deaths shows that fleeing is more lethal than ever»</span>. <a href="https://apnews.com/article/migration-global-deaths-united-nations-9fba1b7019e6b1113b7e3e9ce751c0bb">https://apnews.com/article/migration-global-deaths-united-nations-9fba1b7019e6b1113b7e3e9ce751c0bb</a>.
</div>
<div id="ref-Saadeddin" class="csl-entry" role="listitem">
Saadeddin, Zaina. 2024. <span>«ARIMA para la previsión de series temporales: Guía completa»</span>. <a href="https://www.datacamp.com/es/tutorial/arima">https://www.datacamp.com/es/tutorial/arima</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("google\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./bitacora-2.html" class="pagination-link" aria-label="Bitácora 2">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bitácora 2</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./bitacora-4.html" class="pagination-link" aria-label="Bitacora 4">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bitacora 4</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/CisarUli/Bitacoras-Grupo-6-CA-0204-II-2024-/blob/main/bitacora-3.qmd" class="toc-action"><i class="bi bi-github"></i>Ver el código</a></li></ul></div></div></div></footer></body></html>
