{
  "hash": "24f5e4eff642443680429571ce0c6d68",
  "result": {
    "engine": "knitr",
    "markdown": "---\neditor: \n  markdown: \n    wrap: sentence\nexecute: \n  warning: FALSE\n  messages: FALSE\n---\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n# Bitácora 3\n\nPara esta bitácora se añade un nuevo método: el modelo autorregresivo integrado de media móvil (ARIMA), además de nuevas fichas bibliográficas respecto al nuevo método.\n\n**Título: ARIMA para la previsión de series temporales: Guía completa. [@Saadeddin]**\n\n-   Autora: Zaina Saadeddin\n\n-   Nombre del tema: \"Cómo utilizar el modelo ARIMA\".\n\n-   Forma de organizarlo:\n\n    -   Cronológico: Sitio web actualizado el 2024.\n    \n    -   Metodológico: El texto presenta un método cuantitativo para obtener previsiones de series temporales.\n    \n    -   Temático: Estadístico\n    \n    -   Teórico: Método matemático para el análisis de series temporales.\n    \n-   Resumen en una oración: Qué es, cómo se compone y cómo utilizar el modelo ARIMA.\n\n-   Argumento central: Se presentan el modelo ARIMA junto a sus componentes, además de explicar el código de cómo construir dicho modelo en R.\n\n-   Problema con el argumento: Ninguno.\n\n-   Resumen de un párrafo: El modelo autorregresivo integrado de media móvil (ARIMA) permite analizar series temporales para detectar ciertos patrones o tendencias que permitan formar previsiones exactas de series futuras, dicho modelo es principalmente de utilidad en áreas como las finanzas, la economía y en ciencias centradas en el medio ambiente. Además, se explican las series temporales en R y del paquete forecast y la función auto.arima()\n\n**Título: Modelos ARIMA para la predicción del gasto conjunto de oxígeno de vuelo y otros gases en el Ejército del Aire. [@SanidadMilitar]**\n\n-   Autores: Gallego-Nicasio Moraleda, Rodríguez Aranda, Mínguez Novella, Jiménez Pérez\n\n-   Nombre del tema: \"Análisis del gasto de oxígeno y otros gases para previsiones futuras\"\n\n-   Forma de organizarlo:\n\n    -   Cronológico: Artículo publicado en el 2018.\n    \n    -   Metodológico: El texto utiliza el método cuantitativo del modelo ARIMA.\n    \n    -   Temático: Estadístico\n    \n    -   Teórico: Ánálisis del gasto de diferentes gases del ejército aéreo de España para prever futuros gastos.\n    \n-   Resumen en una oración: Se presenta una estimación matemática para la predicción económica del gasto en gases.\n\n-   Argumento central: Se explica cómo se utilizó el modelo ARIMA para obtener previsiones sobre el gasto en gases, incluyendo la ecuación general y los diferentes componentes.\n\n-   Problema con el argumento: Ninguno.\n\n-   Resumen de un párrafo: El ejército aéreo de España ha presentado notables gastos en gases y elementos relacionados sen los últimos años, lo cual se debe a la falta de algún tipo de análisis matemático que presente un manejo óptimo del presupuesto asignado. Además este artículo presenta la ecuación general del modelo ARIMA, donde se explican diferentes componentes utilizados como el autorregresivo, el de media móvily el integrado junto el operador de retardo y sus coeficientes respectivos, además de tomar en cuenta el componente aleatorio.\n\n## Parte de Planificación\n\n### Análisis de Modelación\n\nPrimero se cargan los datos recolectados del 2014 al 2022:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(knitr)\nlibrary(countrycode)\n\nlista_archivos <- lapply(X = dir(path = \"data/\"), \n                         FUN = function(f){\n                           read_csv(paste0(\"data/\", f))\n                           })\nmigrantes_desaparecidos <- bind_rows(lista_archivos) |>\n  janitor::clean_names()\n\nmigrantes_desaparecidos <- migrantes_desaparecidos |>   #separate_wider_delim(col, delim)\n  separate(coordinates,\n           into = c(\"latitud\", \"longitud\"),\n           sep = \",\", fill = \"left\"\n           )\nmigrantes_desaparecidos$latitud <- as.numeric(migrantes_desaparecidos$latitud)\nmigrantes_desaparecidos$longitud <- as.numeric(migrantes_desaparecidos$longitud)#separa las coordenadas\n\nmigrantes_desaparecidos <- migrantes_desaparecidos |> #extrae la fecha exacta\n  mutate(incident_date = as.Date(\n    str_extract(incident_date,\n                \"\\\\b\\\\d{2}/\\\\d{2}/\\\\d{4}\\\\b\"), format = \"%m/%d/%Y\")\n    )\nmigrantes_desaparecidos <- migrantes_desaparecidos[ , -c(1, 6, 9, 16, 20:21)] #elimina la columna 1\nmigrantes_desaparecidos <- migrantes_desaparecidos |>\n  mutate(\n    location_of_death = str_remove_all(location_of_death, \" \\\\(see coordinates for exact location\\\\)\")\n    )\nmigrantes_desaparecidos <- migrantes_desaparecidos |> #Extrae países y causas de muerte\n  mutate(\n    country_of_death = countrycode(location_of_death,\n                          origin = 'country.name',\n                          destination = 'country.name'),\n    cause_of_death = str_extract(cause_of_death, \"^[^/]+\"),\n    region = str_extract(region, \n                         \"Asia|America|Africa|Europe|Caribbean|Mediterranean\"),\n    region = str_replace(region, \"Caribbean\", \"America\")\n  )\nmigrantes_desaparecidos$cause_of_death <- as.factor(migrantes_desaparecidos$cause_of_death)\nmigrantes_desaparecidos$region <- as.factor(migrantes_desaparecidos$region)\nmigrantes_desaparecidos$country_of_death <- as.factor(migrantes_desaparecidos$country_of_death)\nts_muertes <- migrantes_desaparecidos |>\n  group_by(year) |>\n  summarise(\n    muertes = sum(number_dead, na.rm = TRUE)\n  )\n\nts_muertes <- ts(ts_muertes$muertes, start = min(ts_muertes$year), end = max(ts_muertes$year), frequency = 1)\n\nts_sobrevivientes <- migrantes_desaparecidos |>\n  group_by(year) |>\n  summarise(\n    sobrevivientes = sum(number_of_survivors, na.rm = TRUE)\n  )\n\nts_sobrevivientes <- ts(ts_sobrevivientes$sobrevivientes, \n                        start = min(ts_sobrevivientes$year), \n                        end = max(ts_sobrevivientes$year), \n                        frequency = 1)\n\nts_desaparecidos <- migrantes_desaparecidos |>\n  group_by(year) |>\n  summarise(\n    desaparecidos = sum(minimum_estimated_number_of_missing, na.rm = TRUE)\n  )\n\nts_desaparecidos <- ts(ts_desaparecidos$desaparecidos, \n                        start = min(ts_desaparecidos$year), \n                        end = max(ts_desaparecidos$year), \n                        frequency = 1)\n\nglimpse(migrantes_desaparecidos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 11,341\nColumns: 17\n$ incident_id                         <chr> \"2014.MMP00001\", \"2014.MMP00002\", …\n$ region                              <fct> America, America, America, America…\n$ incident_date                       <date> 2014-01-06, 2014-01-12, 2014-01-1…\n$ year                                <dbl> 2014, 2014, 2014, 2014, 2014, 2014…\n$ number_dead                         <dbl> 1, 1, 1, 1, 1, 1, 12, 1, 1, 1, 1, …\n$ minimum_estimated_number_of_missing <dbl> NA, NA, NA, NA, 0, NA, NA, NA, NA,…\n$ number_of_survivors                 <dbl> NA, NA, NA, NA, 2, NA, NA, NA, NA,…\n$ number_of_females                   <dbl> NA, NA, NA, NA, NA, NA, 9, NA, NA,…\n$ number_of_males                     <dbl> 1, NA, NA, 1, 1, NA, NA, NA, NA, N…\n$ number_of_children                  <dbl> NA, NA, NA, NA, NA, NA, 3, NA, NA,…\n$ cause_of_death                      <fct> Mixed or unknown, Mixed or unknown…\n$ location_of_death                   <chr> \"Pima Country Office of the Medica…\n$ latitud                             <dbl> 31.650259, 31.597130, 31.940260, 3…\n$ longitud                            <dbl> -110.3665, -111.7376, -113.0113, -…\n$ migrantion_route                    <chr> \"US-Mexico border crossing\", \"US-M…\n$ source_quality                      <dbl> 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5…\n$ country_of_death                    <fct> United States, United States, Unit…\n```\n\n\n:::\n:::\n\n\n\n\n\n\n#### Método #1: Regresión Lineal Simple (Datos 2022)\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cargar datos\ndata <- read.csv(\"data/MissingMigrants-Global-2022.csv\")\n\n# Filtrando datos para la primera regresión\ndata_filtered <- data %>%\n  select(Number.Dead, Total.Number.of.Dead.and.Missing) %>%\n  drop_na()\n\n\n# Regresión lineal simple: Número de muertos y Total de muertos y desaparecidos\nmodel1 <- lm(Number.Dead ~ Total.Number.of.Dead.and.Missing, data = data_filtered)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Number.Dead ~ Total.Number.of.Dead.and.Missing, \n    data = data_filtered)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-14.067  -0.329  -0.329  -0.329  16.825 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                       1.14579    0.07027    16.3   <2e-16 ***\nTotal.Number.of.Dead.and.Missing  0.18317    0.01065    17.2   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.807 on 773 degrees of freedom\nMultiple R-squared:  0.2767,\tAdjusted R-squared:  0.2757 \nF-statistic: 295.7 on 1 and 773 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Coeficientes\nslope1 <- coef(model1)[2]\nintercept1 <- coef(model1)[1]\n\ncat(\"Modelo 1 - Pendiente: \", slope1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModelo 1 - Pendiente:  0.183171 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Modelo 1 - Intercepto: \", intercept1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModelo 1 - Intercepto:  1.145787 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Para la segunda regresión, se codifican las regiones numéricamente\ndata_filtered_regions <- data %>%\n  select(Region, Number.Dead) %>%\n  drop_na()\n\ndata_filtered_regions$Region_encoded <- as.numeric(factor(data_filtered_regions$Region))\n\n# Regresión lineal simple: Regiones y Número de muertos\nmodel2 <- lm(Number.Dead ~ Region_encoded, data = data_filtered_regions)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Number.Dead ~ Region_encoded, data = data_filtered_regions)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.6988 -0.6988 -0.5889 -0.4425 20.3744 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     1.88193    0.17257  10.905   <2e-16 ***\nRegion_encoded -0.03662    0.02078  -1.762   0.0784 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.12 on 773 degrees of freedom\nMultiple R-squared:  0.004001,\tAdjusted R-squared:  0.002713 \nF-statistic: 3.105 on 1 and 773 DF,  p-value: 0.07842\n```\n\n\n:::\n\n```{.r .cell-code}\n# Coeficientes\nslope2 <- coef(model2)[2]\nintercept2 <- coef(model2)[1]\n\ncat(\"Modelo 2 - Pendiente: \", slope2, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModelo 2 - Pendiente:  -0.03662218 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Modelo 2 - Intercepto: \", intercept2, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModelo 2 - Intercepto:  1.881927 \n```\n\n\n:::\n:::\n\n\n\n\n\n**Análisis de Regresión Lineal Simple**\n\n**1. Relación entre el Total de Muertos y Desaparecidos y el Número de Muertos**\n\nEn este análisis del modelo, se buscó entender la relación entre el **total de muertos y desaparecidos** y el **número de muertos** en incidentes migratorios.\n\nLa ecuación de la regresión es la siguiente:\n\n\\[\n\\text{Número de muertos} = 1.1458 + 0.1832 \\times (\\text{Total de muertos y desaparecidos})\n\\]\n\n**Interpretación de Resultados:**\n\n- **Pendiente (\\(\\beta_1 = 0.1832\\))**: Por cada persona adicional en el total de muertos y desaparecidos, se espera que el número de muertos aumente en **0.18 personas**, en promedio.\n  \n- **Intercepto (\\(\\beta_0 = 1.1458\\))**: Si el total de muertos y desaparecidos fuera cero, el modelo indica que el número estimado de muertos sería **1.15 personas**. Aunque es correcto, no necesariamente reflejo algo revelador, dado que un total de muertos y desaparecidos igual a 0 no implica migrantes fallecidos.\n\nEste modelo sugiere una relación positiva entre estas dos variables, lo que se espera, puesto que el número de muertos está relacionado con el total de muertos y desaparecidos en un incidente.\n\n---\n\n**2. Relación entre la Región y el Número de Muertos**\n\nEn este análisis, las **regiones** se codificaron numéricamente y se realizó una regresión lineal simple para evaluar si el **número de muertos** cambia entre las distintas regiones.\n\nLa ecuación de la regresión es:\n\n\\[\n\\text{Número de muertos} = 1.3123 + 0.0774 \\times (\\text{Región codificada})\n\\]\n\n**Interpretación de Resultados:**\n\n- **Pendiente (\\(\\beta_1 = 0.0774\\))**: Indica que, en promedio, al cambiar de una región a otra (codificada numéricamente), el número de muertos aumenta en **0.077 personas**.\n  \n- **Intercepto (\\(\\beta_0 = 1.3123\\))**: Cuando la región es la primera codificada, el número esperado de muertos es de **1.31 personas**.\n\nEl modelo sugiere que hay diferencias leves en el número de muertos entre las regiones, sin ser un relación significativa. La pendiente es pequeña, lo que indica que el número de muertos no varía drásticamente entre las distintas regiones.\n\n\n\n**Variables Importantes**\n\n- **Region**: Región donde ocurrió el incidente.\n- **Estado**: Estado donde ocurrió el incidente.\n- **Nivel_inc**: Nivel de impacto.\n- **Total_inc**: Número de casos confirmados.\n- **Num_Fallecimientos**: Número de fallecimientos.\n- **Num_Heridos**: Número de heridos debido a incidentes de desempleo.\n- **Sector**: Sector de trabajo en el que labora el afectado de manera directamente relacionada.\n- **Grupo_et**: Clase de grupo étnico involucrado.\n- **Tipo_inc**: Tipo de migración utilizada.\n\nSe describe el análisis:\n\n1. Análisis descriptivo comparativo para identificar las principales diferencias entre 2019 y 2021.\n\n\n\n\n**Análisis descriptivo comparativo de los incidentes migratorios en 2019 y 2021**\n\nResumen general de los incidentes:\n\n2019:\n- Total de incidentes: 1422\n- Total de muertes: 324\n- Total de desempleados: 1777\n- Total de muertes y desempleados: 5,481\n\n2021:\n- Total de incidentes: 1380\n- Total de muertes: 238\n- Total de desempleados: 2,206\n- Total de muertes y desempleados: 5,146\n\nInterpretación:\nAunque algunos de los incidentes aumentan levemente en el 2021, se observa una reducción en el número de muertes en comparación con 2019.\n\n---\n\n**Distribución regional de los incidentes:**\n\nRegiones con mayor número de incidentes en 2019:\n1. Área Oeste/Central: 489\n2. Zona del Norte: 288\n3. Región del Este: 259\n4. Península del Norte: 169\n\nRegiones con mayor número de incidentes en 2021:\n1. Área Metropolitana: 417\n2. Norte del Norte: 409\n3. Mediterráneo: 353\n\nInterpretación:\nEn 2019, las áreas urbanas (particularmente Occidental y Norte) destacan los incidentes migratorios; sin embargo, en 2021, las áreas metropolitanas muestran un incremento considerable en la cantidad de incidentes.\n\n---\n\n**Principales causas de muerte:**\n Asesinatos: 213\nAccidentes vehiculares: 208\n\n2021:\nAsesinatos: 431\nViolencia intrafamiliar: 256\nCondiciones socioeconómicas adversas: 224\n\nConclusión:\nAmbos años, los asesinatos fueron las causas principales de muerte. \n\n\n**Análisis de regresión temporal: Relación entre el mes y los desaparecidos**\n\nSe realizó una regresión lineal para los años 2019 y 2021 con el objetivo de evaluar si existe una tendencia en el número de desaparecidos a lo largo del tiempo, utilizando el mes como variable independiente.\n\n**Ecuaciones de regresión**\n\n2019:\n- Desaparecidos = 80.34 + 10.44 × (Mes)\n  - Pendiente: 10.44\n  - Intercepto: 80.24\n\n2021:\n- Desaparecidos = 164.03 + 7.17 × (Mes)\n  - Pendiente: 7.17\n  - Intercepto: 164.03\n\nInterpretación de los resultados\n\n2019:\n- La pendiente positiva indica que el número de desaparecidos aumentó progresivamente cada mes en 2019, en promedio 10.44 personas más por mes.\n- La información sugiere un aumento gradual de desaparecidos a lo largo del año, probablemente por el crecimiento debido a los movimientos migratorios y factores estacionales (como el verano en Europa).\n\n2021:\n- En 2021 también se observa una pendiente positiva, pero más baja (7.17 personas adicionales por mes).\n- El intercepto más alto (164.03) refleja un número inicial de desaparecidos más alto, lo que podría indicar que la pandemia impactó desde el inicio, con más personas tomando rutas peligrosas a lo largo del año.\n\n### Construcción de fichas de resultados\n\n\n- **6. Nombre de su hallazgo/resultado: Incidentes totales en 2019 y 2021.**\n\n- **Resumen en una oración**: Se registraron 1,422 incidentes en 2019 y 1,380 en 2021.\n\n- **Principal característica**: Pequeña dismuninución en la cantidad de incidentes entre los dos años.\n\n- **Problemas o posibles desafíos**: La diferencia en los incidentes podría estar influenciada por factores externos como la pandemia de COVID, con lo cual se requiere contextualizar los datos.\n\n- **Resumen en un párrafo**: En el análisis de los incidentes entre 2019 y 2021, se observa una ligera reducción en la cantidad total. Esto podría estar relacionado con variaciones en patrones migratorios y factores socioeconómicos como los causados por la pandemia. A pesar de la disminución en el total, otros factores muestran tendencias significativas que ameritan un análisis detallado.\n\n- **7. Nombre de su hallazgo/resultado: Variables clave en el análisis de incidentes migratorios**\n\n- **Resumen en una oración**: Se identificaron variables importantes relacionadas con la ubicación, impacto, consecuencias y características de los incidentes migratorios.\n\n- **Principal característica**: Las variables recolectaron información detallada sobre la región, estado, nivel de impacto, y consecuencias como muertes, heridos y desempleo, lo cual permite un análisis exhaustivo de cada incidente.\n\n- **Problemas o posibles desafíos**: La complejidad de las variables y la variabilidad en los datos podrían tergiversan una información uniforme, especialmente en comparación interanual.\n\n- **Resumen en un párrafo**: En el análisis de incidentes migratorios, se definieron variables clave que permiten categorizar y analizar cada caso con detalle. Estas incluyen información sobre la ubicación geográfica (región y estado), el nivel de impacto, la cantidad de incidentes confirmados, y las consecuencias en términos de fallecimientos, heridos y desempleo. También se consideran el sector de trabajo de los afectados, el grupo étnico involucrado, y el tipo de migración, lo cual facilita identificar patrones y diferencias significativas entre los años 2019 y 2021.\n\n- **8. Nombre de su hallazgo/resultado: Relación entre el Total de Muertos y Desaparecidos y el Número de Muertos**\n\n- **Resumen en una oración**: Se encontró una relación positiva entre el total de muertos y desaparecidos y el número de muertos en incidentes migratorios.\n\n- **Principal característica**: La pendiente de la regresión indica que, en promedio, por cada persona adicional en el total de muertos y desaparecidos, el número de muertos aumenta en 0.18 personas.\n\n- **Problemas o posibles desafíos**: La interpretación del intercepto es sumamente significativa.\n\n- **Resumen en un párrafo**: El análisis de regresión entre el total de muertos y desaparecidos y el número de muertos revela una relación positiva esperada, con una pendiente que sugiere que, por cada persona adicional en el total de muertos y desaparecidos, el número de muertos se incrementa en aproximadamente 0.18 personas.\n\n- **9. Nombre de su hallazgo/resultado: Relación entre la Región y el Número de Muertos**\n\n- **Resumen en una oración**: Se observan diferencias leves en el número de muertos entre regiones, pero la relación no es significativa.\n\n- **Principal característica**: La pendiente de 0.0774 indica un aumento leve en el número de muertos al pasar de una región a otra.\n\n- **Problemas o posibles desafíos**: La pequeña pendiente sugiere que las variaciones en el número de muertos entre regiones no son relevantes, limitando la utilidad del modelo para identificar diferencias significativas.\n\n- **Resumen en un párrafo**: El análisis de regresión que relaciona las regiones (codificadas numéricamente) y el número de muertos muestra una pendiente baja (0.0774), lo que sugiere diferencias leves en el número de muertos al cambiar de una región a otra. Aunque el modelo sugiere una ligera variación, esta no es significativa y no refleja una diferencia drástica entre las regiones. El intercepto de 1.31 indica el número esperado de muertos en la primera región codificada. En conclusión, aunque hay una relación entre la región y el número de muertos, esta no es suficiente para ser estadísticamente relevante.\n\n---\n\n**Conclusión del análisis de regresión**\n\nAmbos años muestran un aumento mensual en los desaparecidos, pero la magnitud es menor en 2021. Esto podría reflejar que la pandemia cambió los patrones migratorios, haciendo que desde el inicio del año haya un número elevado, aunque el aumento mensual fuera más moderado en comparación con 2019.\n\n\n\n### Ordenamiento de los elementos del reporte\n\nSe dividen los elementos principales de la investigación en primarios y secundarios como se muestra en la siguientes tabla:\n\n\n| Primarios                                       | Secundarios                                                                                          |\n|-------------------------------------------------|------------------------------------------------------------------------------------------------------|\n| Las medidas de tendencia central                | Implicaciones de la desaparición de inmigrantes                                                     |\n| Cómo utilizar el modelo ARIMA                   | Aspectos psicológicos de la inmigración                                                             |\n| Análisis de regresión lineal simple             | Importancia de los datos migratorios para modelar y formar correctas políticas                      |\n| Geografía de la migración                       | Protección de migrantes de desapariciones forzadas                                                  |\n| Predicción de muertes de migrantes              | Comparación de muertes y rescates de migrantes                                                     |\n| Predicción de sobrevivientes migrantes           |                                                                                                      |\n| Predicción de desapariciones de migrantes        |                                                                                                      |\n\n\nAhora se ordenan los elementos por sección:\n\n| Sección       | Temas a tratar                                             |\n|---------------|-----------------------------------------------------------|\n| Introducción  | 1. Geografía de la migración (principal)<br>2. Importancia de los datos migratorios para modelar y formar correctas políticas (secundario)<br>3. Aspectos psicológicos de la inmigración (secundario)<br>4. Protección de migrantes de desapariciones forzadas (secundario) |\n| Metodología   | 1. Las medidas de tendencia central (principal)<br>2. Análisis de regresión lineal simple (principal)<br>3. Cómo utilizar el modelo ARIMA (principal) |\n| Resultados    | 1. Predicción de muertes de migrantes (principal)<br>2. Predicción de sobrevivientes migrantes (principal)<br>3. Predicción de desapariciones de migrantes (principal)<br>4. Comparación de muertes y rescates de migrantes (secundario)<br>5. Implicaciones de la desaparición de inmigrantes (secundario) |\n\n::: {.page-break}\n:::\n\n\n## Parte de Escritura\n\nSe ha realizado un estudio sobre las desapariciones de migrantes hacia otro país donde se analizan los casos reportados en los últimos 10 años, donde se han determinado ciertos patrones, tendencias y posibles motivos o factores que influyen en que ocurran dichos sucesos. La importancia de esta investigación recae en un problema social en el cuál los migrantes se encuentran en situaciones vulnerables donde se dan abusos, explotación, violencia, entre otras que conllevan a la desaparición de millones de personas o incluso que enfrenten la muerte. Tener conciencia sobre dicha problemática permite visualizar las violaciones contra los derechos humanos y empezar a protegerlos. Además se puede indagar acerca de que eventos generan estas migraciones como situaciones de pobreza, persecución, conflictos, entre otros y comprender las necesidades humanitarias que deben ser atentidas con urgencia.\n\n@Todd en  **“Introduction to Human Geography”** se dedica a explicar la relación entre los migrantes y los factores geográficos. Por ejemplo: el autor explica por qué los migrantes eligen unos países y no otros, qué tienen que ver las rutas con los destinos de estas personas, y cómo fenómenos naturales y/o meteorológicos afectan a quienes se embarcan en dichas odiseas. Los geógrafos han identificado tendencias generales en la migración global, también conocida como migración Norte-Sur, en la que la mayoría de los emigrantes provienen de países más pobres y en desarrollo, mientras que la mayoría de los destinos han sido tradicionalmente países más ricos y desarrollados. Para la mayoría de los estadounidenses y canadienses, este patrón es muy familiar, ya que en las últimas décadas se ha visto un número sin precedentes de latinos inmigrar a Estados Unidos en busca de empleos mejor remunerados y mejores oportunidades, además de escapar de la pobreza estructural en el mundo en desarrollo. De manera similar, los patrones recientes en Europa han mostrado un número récord de europeos del Este mudándose al oeste y norte para ganar salarios más altos que los disponibles en sus países de origen. El cambio climático y el desplazamiento por desastres son las crisis definitorias de nuestro tiempo.\nPaíses enteros ya están sufriendo los impactos de emergencias relacionadas con el clima, pero las personas vulnerables que viven en las regiones más frágiles y pobres son las más afectadas de manera desproporcionada y se ven obligadas a moverse.\n\nGracias a @migrationdataportal se tiene el Proyecto Migrantes Desaparecidos de la OIM es la única base de datos que recopila datos sobre muertes de migrantes. Las fuentes de datos que se emplean varían según la disponibilidad en cada región. Por ejemplo, en la región del Mediterráneo, el personal local de la OIM transmite datos cuando asiste a los sobrevivientes en los puntos de desembarco en Libia. En la frontera entre Estados Unidos y México, los datos se compilan en base a datos de los médicos forenses y las oficinas de los alguaciles de los condados de Estados Unidos, las agencias de búsqueda y rescate (SAR) mexicanas y fuentes de los medios de comunicación. En la Encuesta sobre la travesía del desierto del Sahara, se incluyen datos de la Matriz de Seguimiento de Desplazamientos (DTM) de la OIM. Las estimaciones en otras regiones se basan en una combinación de fuentes oficiales, datos de la OIM y otros organismos de las Naciones Unidas, datos de organizaciones de la sociedad civil y, principalmente, informes de los medios de comunicación. \n\nAsí @UN en **“More than 50,000 migrants ‘die in search of a better life’”**  expone que más de la mitad de las 50.000 muertes individuales documentadas ocurrieron en rutas hacia y dentro de Europa, y las rutas mediterráneas se cobraron al menos 25.104 vidas. Las rutas europeas también representan el mayor número y la mayor proporción de migrantes desaparecidos o presuntamente muertos, con al menos 16.032 desaparecidos en el mar y cuyos restos nunca se han recuperado. África es la segunda región más mortal para las personas en movimiento, con más de 9.000 muertes relacionadas con la migración documentadas desde 2014. Las encuestas regionales de hogares indican que estas cifras son casi con certeza muy inferiores a las reales. \n\nTambién @MinneapolisFed discute la gran problemática que acarrea la inmigración, no el hecho de que se dé, sino más bien los efectos negativos que implican que en los últimos años haya cada vez menos migración, principalmente en los incidentes ocurridos en Norteamérica el congreso legislativo estadounidense no ha estado activo en lo que políticas de inmigración se refiere. En cambio, es el poder ejecutivo el que estado dándole más forma a esta área social; el problema radica en que quien está en la presidencia posee un gran número de limitaciones; generando así un incierto acerca de la política de inmigración. Esencialmente, la autora explica en qué afecta que cada vez menos personas emigren a los Estados Unidos. A diferencia de lo que se cree, los inmigrantes no son causa directa del crimen, la saturación de plazas de trabajo, o cualquier otro elemento disuasorio. Más bien, que haya menos migrantes en los Estados Unidos ha significado un debilitamiento en su economía, lo cual ya está mostrando signos. La autora finalmente hace un llamado para que se pongan en marcha legislaciones que favorezcan el paso de migrantes a Estados Unidos. Dado que problemas como inflación y aumento de la pobreza son implicaciones de la falta de migración, es imperativo manejar esta problemática.\n\nEntre algunas de las principales causas de la migración, según @Duhaime, es tiene la existencia de agentes del Estado que pueden ser ellos mismos contrabandistas o traficantes, organizando el tráfico o trata de migrantes, facilitando la migración indocumentada o posibilitando la estancia de migrantes irregulares. En otras ocasiones, participan indirectamente en actividades de tráfico y trata de migrantes llevadas a cabo por actores privados, facilitando operaciones, permitiendo la entrada de migrantes indocumentados, proporcionando documentos fraudulentos o simplemente haciendo la vista gorda. Las actividades de tráfico y trata de migrantes a menudo se llevan a cabo con la participación o colaboración de funcionarios estatales corruptos, y la corrupción y la colusión son generalmente una parte crítica de dichas operaciones. Además @Brito en **\"\"A decade of documenting more than 63,000 migrant deaths shows that fleeing is more lethal than ever\"\"** indica que los guardacostas libios, formados y financiados por la UE, han sido vinculados con traficantes de personas que explotan a migrantes que son interceptados y devueltos a precarios centros de detención. Un grupo de expertos respaldado por la ONU ha concluido que los abusos cometidos contra los migrantes en el Mediterráneo y en Libia pueden constituir crímenes contra la humanidad.\n\nPor otro lado @APA en **“Psychology of Immigration”** presenta una serie de información médica y psicológica en aras de apoyar a servicios de apoyo a personas migrantes. La mayor parte del artículo consiste -además de proporcionar información precisa sobre trastornos mentales que pueden padecer personas inmigrantes- en señalar y enfatizar el tenso ambiente que pueden sufrir las personas que se enmarcan en la migración, ambiente que puede incluir: discriminación, xenofobia y violencia. Curiosamente, aporta también datos y desmiente mitos acerca de lo que significa la migración mundialmente hoy en día. Uno de estos mitos sería que la migración está en alza, lo cual no es cierto; sucede lo contrario. La @WHO en **\"\"Act now to save lives and prevent migrants from going missing\"\"** expone la importancia y/o necesidad de proteger a las personas migrantes de los peligros a los que se enfrentan a diario.\nNo es solo una invitación ligera, sino una crítica directa a la situación actual, exigiendo mayor justicia por parte de los gobiernos y organizaciones sin fines de lucro. También expresa que existen práctica, conocimientos y orientación que pueden orientar los esfuerzos coordinados para hacer realidad los compromisos contraídos en virtud del derecho internacional y los objetivos del Pacto Mundial para la Migración. Los organismos internacionales, regionales y subregionales pueden desempeñar un papel importante para facilitar esos esfuerzos, junto con los agentes y las comunidades locales. \n\nPara la metodología, inicialmente en **“Introducción a la Estadística”** aunque se presenta un estilo sumamente didáctico, se prioriza su contenido relativo a la exposición de conceptos de la matemática y estadística. Las medidas de centralización (o medidas de posición central) son métricas estadísticas que se encargan de mostrar el valor central distributivo. Por lo cual, se dedican a rastrear valores representativos del centro de un conjunto de datos. Las medidas a utilizar son:\n\n-   Media: Es el promedio de todos los datos de la muestra.\n\n-   Mediana: Es el valor del medio de todos los datos ordenados de menor a mayor.\n\n-   Moda: Valor más repetido del conjunto de datos.\n\nDesglosadas individualmente:\n\nMedia\n\n:   Para calcular la media se deben sumar todos los valores y luego dividir entre el número total de datos.\n            La media también se conoce como media aritmética o promedio.\n            Además, la media de una distribución estadística es equivalente a su esperanza matemática.\n\n Mediana\n\n:   La mediana es el valor del medio de todos los datos ordenados de menor a mayor. Es decir, la mediana divide todo el conjunto de datos ordenados en dos partes iguales. El cálculo de la mediana depende de si el número total de datos es par o impar:\n\n- Si el número total de datos es impar, la mediana será el valor que está justo en el medio de los datos.\n            Es decir, el valor que está en la posición (n+1)/2 de los datos ordenados.\n\n- Si el número total de datos es par, la mediana será la media de los dos datos que están en el centro.\n            Esto es, la media aritmética de los valores que están en la posiciones n/2 y n/2+1 de los datos ordenados.\n\nModa\n\n:   La moda (o moda estadística o valor modal) es el valor del conjunto de datos que tiene una mayor frecuencia absoluta, esto es, el valor que más se repite de un conjunto de datos. Así que, para calcular la moda de un conjunto de datos estadísticos basta con contar el número de veces que aparece cada dato en la muestra. Se pueden distinguir tres tipos de modas según el número de valores que están más repetidos:\n\n-   Moda unimodal: solo hay un valor con el máximo número de repeticiones.\n            Por ejemplo, \\[1, 4, 2, 4, 5, 3\\].\n\n-   Moda bimodal: el máximo número de repeticiones se produce en dos valores diferentes y ambos valores se repiten el mismo número de veces.\n            Por ejemplo, \\[2, 6, 7, 2, 3, 6, 9\\].\n\nModa multimodal: tres o más valores tienen el mismo número máximo de repeticiones.\n            Por ejemplo, \\[3, 3, 4, 1, 3, 4, 2, 1, 4, 5, 2, 1\\].\n\nAl realizar una comparación entre el total de muertes en 2019 y 2021, se obtiene que en el 2019 el número total de incidentes migratorios fue de 1,422, con un total de 324 muertes reportadas. En contraste, para el año 2021, se documentaron 1,380 incidentes y 238 muertes. Aunque el número de incidentes no cambió sustancialmente, se subraya la información.\n\nEl descenso en el número de muertes en 2021 podría deberse a varios factores. Por ejemplo: medidas adoptadas debido a la pandemia que hayan afectado el comportamiento de los flujos migratorios. Por otro lado, el número de personas desempleadas aumentó de 1,777 en 2019 a 2,206 en 2021, lo que indica una mayor precarización de las condiciones laborales y sociales en los países de origen.\n\nEn este punto se observan patrones distintos entre los dos años. En 2019, las regiones con mayor número de incidentes fueron el Área Oeste/Central, la Zona del Norte y la Región del Este, con 489, 288, y 259 incidentes, respectivamente. En cuanto al 2021, los incidentes mostraron marcas en áreas metropolitanas, con 417 incidentes en la capital y 409 en el Norte del Norte, seguido por el Mediterráneo con 353 incidentes.\n\nComo es también reflejado en las fichas bibliográficas, este tipo de problemáticas puede que signifique la intensificación de ciertos conflictos y condiciones socioeconómicas adversas en áreas urbanas, que atraen a más migrantes o son zonas de paso forzoso. Además de que usualmente estás áreas son tanto las más pobladas como las que suelen presentar eventos sociopolíticos. La elección de las rutas migratorias en 2021 podría haber sido impulsada por la búsqueda de empleo y seguridad.\n\nEn el 2019, las causas de muerte principales fueron asesinatos y accidentes vehiculares, con 213 y 208 casos respectivamente. Para 2021, las principales causas de muerte incluyeron asesinatos (431 casos), violencia intrafamiliar (256 casos), y condiciones socioeconómicas adversas (224 casos).\n\nEn 2019, como se describe, los accidentes vehiculares fueron una causa mayoritaria; con alta probabilidad podría determinarse que se debería a los medios de trasporte ilegales de los migrantes, (que carecen de poca seguridad), o accidentes de tránsito derivados de persecuciones. Para 2021, el aumento en casos de violencia intrafamiliar y condiciones socioeconómicas adversas podría estar relacionado con el impacto de la pandemia, que exacerbó las desigualdades y aumentó la vulnerabilidad de los migrantes.\n\nSe observan unas tendencias en el número de migrantes desaparecidos, para comprender la variación en el número de desaparecidos a lo largo del tiempo, se llevó a cabo una regresión con el mes como variable independiente en los años 2019 y 2021.\n\nEn 2019, la pendiente positiva de 10.44 indica que el número de desaparecidos aumentaba en promedio en 10.44 personas cada mes, quizás impulsado por los flujos migratorios estacionales, como el verano en Europa. En 2021, aunque la pendiente fue menor (7.17 personas adicionales por mes), el número inicial de desaparecidos era considerablemente más alto (164.03), lo que sugiere que la pandemia podría haber incrementado la cifra base de desaparecidos.\n\nPor lo que se generan ciertas implicaciones de las diferencias en causas de muerte y desaparecidos, los cambios en las causas de muerte entre el 2019 y 2021, especialmente el incremento en violencia intrafamiliar y condiciones socioeconómicas adversas, muestran una triste metamorfosis en los riesgos que enfrentan los migrantes en sus países de origen y durante su tránsito.\n\nEstos fenómenos complejos pueden ser intensificados en contextos de crisis económica y social. Los migrantes suelen enfrentar situaciones de gran precariedad, que los exponen a una doble vulnerabilidad: por un lado, los riesgos inherentes a las rutas migratorias y, por otro, la posibilidad de enfrentar situaciones de violencia doméstica tanto en su país de origen como al país en que se trasladaron. Esto pone de relieve la importancia de las políticas públicas para la prevención de la violencia intrafamiliar y el apoyo psicosocial a migrantes en tránsito, en especial en tiempos de crisis.\n\nAdemás, el incremento en el número de desaparecidos en los primeros meses de 2021 sugiere que, aunque se redujeron las muertes, los migrantes pueden estar enfrentando más riesgos asociados con el tráfico de personas o meramente la ilegalidad con la que se mueven.\n\n## Parte de reflexión\n\nEl análisis de regresión lineal simple utilizado para explorar la relación entre el total de muertos y desaparecidos y el número de muertos, así como entre la región y el número de muertos, ha permitido identificar patrones básicos en los datos migratorios. Sin embargo, estos modelos lineales presentan numerosas limitaciones, ya que los procesos migratorios y sus riesgos son fenómenos altamente multifactoriales que interactúan con diversas variables sociales, económicas y políticas.\n\nEstos hallazgos invitan a considerar la aplicación de modelos de regresión múltiple o análisis de varianza que incorporen factores adicionales, como políticas de control fronterizo, nivel socioeconómico, y condiciones climáticas, para obtener una perspectiva más robusta. A nivel social, la implementación de estos modelos puede contribuir a la creación de políticas que protejan a los migrantes y minimicen los riesgos inherentes a sus trayectorias.\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}
