{
  "hash": "47c85d511ebfd6f0c37bfbc0fd1754c6",
  "result": {
    "engine": "knitr",
    "markdown": "---\neditor: \n  markdown: \n    wrap: sentence\nexecute: \n  warning: FALSE\n  messages: FALSE\n---\n\n\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n# Bitácora 3\n\nPara esta bitácora se añade un nuevo método: el modelo autorregresivo integrado de media móvil (ARIMA), además de nuevas fichas bibliográficas respecto al nuevo método.\n\n**Título: ARIMA para la previsión de series temporales: Guía completa. [@Saadeddin]**\n\n-   Autora: Zaina Saadeddin\n\n-   Nombre del tema: \"Cómo utilizar el modelo ARIMA\".\n\n-   Forma de organizarlo:\n\n    -   Cronológico: Sitio web actualizado el 2024.\n    \n    -   Metodológico: El texto presenta un método cuantitativo para obtener previsiones de series temporales.\n    \n    -   Temático: Estadístico\n    \n    -   Teórico: Método matemático para el análisis de series temporales.\n    \n-   Resumen en una oración: Qué es, cómo se compone y cómo utilizar el modelo ARIMA.\n\n-   Argumento central: Se presentan el modelo ARIMA junto a sus componentes, además de explicar el código de cómo construir dicho modelo en R.\n\n-   Problema con el argumento: Ninguno.\n\n-   Resumen de un párrafo: El modelo autorregresivo integrado de media móvil (ARIMA) permite analizar series temporales para detectar ciertos patrones o tendencias que permitan formar previsiones exactas de series futuras, dicho modelo es principalmente de utilidad en áreas como las finanzas, la economía y en ciencias centradas en el medio ambiente. Además, se explican las series temporales en R y del paquete forecast y la función auto.arima()\n\n**Título: Modelos ARIMA para la predicción del gasto conjunto de oxígeno de vuelo y otros gases en el Ejército del Aire. [@SanidadMilitar]**\n\n-   Autores: Gallego-Nicasio Moraleda, Rodríguez Aranda, Mínguez Novella, Jiménez Pérez\n\n-   Nombre del tema: \"Análisis del gasto de oxígeno y otros gases para previsiones futuras\"\n\n-   Forma de organizarlo:\n\n    -   Cronológico: Artículo publicado en el 2018.\n    \n    -   Metodológico: El texto utiliza el método cuantitativo del modelo ARIMA.\n    \n    -   Temático: Estadístico\n    \n    -   Teórico: Ánálisis del gasto de diferentes gases del ejército aéreo de España para prever futuros gastos.\n    \n-   Resumen en una oración: Se presenta una estimación matemática para la predicción económica del gasto en gases.\n\n-   Argumento central: Se explica cómo se utilizó el modelo ARIMA para obtener previsiones sobre el gasto en gases, incluyendo la ecuación general y los diferentes componentes.\n\n-   Problema con el argumento: Ninguno.\n\n-   Resumen de un párrafo: El ejército aéreo de España ha presentado notables gastos en gases y elementos relacionados sen los últimos años, lo cual se debe a la falta de algún tipo de análisis matemático que presente un manejo óptimo del presupuesto asignado. Además este artículo presenta la ecuación general del modelo ARIMA, donde se explican diferentes componentes utilizados como el autorregresivo, el de media móvily el integrado junto el operador de retardo y sus coeficientes respectivos, además de tomar en cuenta el componente aleatorio.\n\n## Parte de Planificación\n\n### Análisis de Modelación\n\nPrimero se cargan los datos recolectados del 2014 al 2022:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(knitr)\nlibrary(countrycode)\n\nlista_archivos <- lapply(X = dir(path = \"data/\"), \n                         FUN = function(f){\n                           read_csv(paste0(\"data/\", f))\n                           })\nmigrantes_desaparecidos <- bind_rows(lista_archivos) |>\n  janitor::clean_names()\n\nmigrantes_desaparecidos <- migrantes_desaparecidos |>   #separate_wider_delim(col, delim)\n  separate(coordinates,\n           into = c(\"latitud\", \"longitud\"),\n           sep = \",\", fill = \"left\"\n           )\nmigrantes_desaparecidos$latitud <- as.numeric(migrantes_desaparecidos$latitud)\nmigrantes_desaparecidos$longitud <- as.numeric(migrantes_desaparecidos$longitud)#separa las coordenadas\n\nmigrantes_desaparecidos <- migrantes_desaparecidos |> #extrae la fecha exacta\n  mutate(incident_date = as.Date(\n    str_extract(incident_date,\n                \"\\\\b\\\\d{2}/\\\\d{2}/\\\\d{4}\\\\b\"), format = \"%m/%d/%Y\")\n    )\nmigrantes_desaparecidos <- migrantes_desaparecidos[ , -c(1, 6, 9, 16, 20:21)] #elimina la columna 1\nmigrantes_desaparecidos <- migrantes_desaparecidos |>\n  mutate(\n    location_of_death = str_remove_all(location_of_death, \" \\\\(see coordinates for exact location\\\\)\")\n    )\nmigrantes_desaparecidos <- migrantes_desaparecidos |> #Extrae países y causas de muerte\n  mutate(\n    country_of_death = countrycode(location_of_death,\n                          origin = 'country.name',\n                          destination = 'country.name'),\n    cause_of_death = str_extract(cause_of_death, \"^[^/]+\"),\n    region = str_extract(region, \n                         \"Asia|America|Africa|Europe|Caribbean|Mediterranean\"),\n    region = str_replace(region, \"Caribbean\", \"America\")\n  )\nmigrantes_desaparecidos$cause_of_death <- as.factor(migrantes_desaparecidos$cause_of_death)\nmigrantes_desaparecidos$region <- as.factor(migrantes_desaparecidos$region)\nmigrantes_desaparecidos$country_of_death <- as.factor(migrantes_desaparecidos$country_of_death)\nts_muertes <- migrantes_desaparecidos |>\n  group_by(year) |>\n  summarise(\n    muertes = sum(number_dead, na.rm = TRUE)\n  )\n\nts_muertes <- ts(ts_muertes$muertes, start = min(ts_muertes$year), end = max(ts_muertes$year), frequency = 1)\n\nts_sobrevivientes <- migrantes_desaparecidos |>\n  group_by(year) |>\n  summarise(\n    sobrevivientes = sum(number_of_survivors, na.rm = TRUE)\n  )\n\nts_sobrevivientes <- ts(ts_sobrevivientes$sobrevivientes, \n                        start = min(ts_sobrevivientes$year), \n                        end = max(ts_sobrevivientes$year), \n                        frequency = 1)\n\nts_desaparecidos <- migrantes_desaparecidos |>\n  group_by(year) |>\n  summarise(\n    desaparecidos = sum(minimum_estimated_number_of_missing, na.rm = TRUE)\n  )\n\nts_desaparecidos <- ts(ts_desaparecidos$desaparecidos, \n                        start = min(ts_desaparecidos$year), \n                        end = max(ts_desaparecidos$year), \n                        frequency = 1)\n\nglimpse(migrantes_desaparecidos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 11,341\nColumns: 17\n$ incident_id                         <chr> \"2014.MMP00001\", \"2014.MMP00002\", ~\n$ region                              <fct> America, America, America, America~\n$ incident_date                       <date> 2014-01-06, 2014-01-12, 2014-01-1~\n$ year                                <dbl> 2014, 2014, 2014, 2014, 2014, 2014~\n$ number_dead                         <dbl> 1, 1, 1, 1, 1, 1, 12, 1, 1, 1, 1, ~\n$ minimum_estimated_number_of_missing <dbl> NA, NA, NA, NA, 0, NA, NA, NA, NA,~\n$ number_of_survivors                 <dbl> NA, NA, NA, NA, 2, NA, NA, NA, NA,~\n$ number_of_females                   <dbl> NA, NA, NA, NA, NA, NA, 9, NA, NA,~\n$ number_of_males                     <dbl> 1, NA, NA, 1, 1, NA, NA, NA, NA, N~\n$ number_of_children                  <dbl> NA, NA, NA, NA, NA, NA, 3, NA, NA,~\n$ cause_of_death                      <fct> Mixed or unknown, Mixed or unknown~\n$ location_of_death                   <chr> \"Pima Country Office of the Medica~\n$ latitud                             <dbl> 31.650259, 31.597130, 31.940260, 3~\n$ longitud                            <dbl> -110.3665, -111.7376, -113.0113, -~\n$ migrantion_route                    <chr> \"US-Mexico border crossing\", \"US-M~\n$ source_quality                      <dbl> 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5~\n$ country_of_death                    <fct> United States, United States, Unit~\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n#### Método #2: Regresión Lineal Simple (Datos 2022)\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cargar datos\ndata <- read.csv(\"data/MissingMigrants-Global-2022.csv\")\n\n# Filtrando datos para la primera regresión\ndata_filtered <- data %>%\n  select(Number.Dead, Total.Number.of.Dead.and.Missing) %>%\n  drop_na()\n\n\n# Regresión lineal simple: Número de muertos y Total de muertos y desaparecidos\nmodel1 <- lm(Number.Dead ~ Total.Number.of.Dead.and.Missing, data = data_filtered)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Number.Dead ~ Total.Number.of.Dead.and.Missing, \n    data = data_filtered)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-14.067  -0.329  -0.329  -0.329  16.825 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                       1.14579    0.07027    16.3   <2e-16 ***\nTotal.Number.of.Dead.and.Missing  0.18317    0.01065    17.2   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.807 on 773 degrees of freedom\nMultiple R-squared:  0.2767,\tAdjusted R-squared:  0.2757 \nF-statistic: 295.7 on 1 and 773 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Coeficientes\nslope1 <- coef(model1)[2]\nintercept1 <- coef(model1)[1]\n\ncat(\"Modelo 1 - Pendiente: \", slope1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModelo 1 - Pendiente:  0.183171 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Modelo 1 - Intercepto: \", intercept1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModelo 1 - Intercepto:  1.145787 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Para la segunda regresión, se codifican las regiones numéricamente\ndata_filtered_regions <- data %>%\n  select(Region, Number.Dead) %>%\n  drop_na()\n\ndata_filtered_regions$Region_encoded <- as.numeric(factor(data_filtered_regions$Region))\n\n# Regresión lineal simple: Regiones y Número de muertos\nmodel2 <- lm(Number.Dead ~ Region_encoded, data = data_filtered_regions)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Number.Dead ~ Region_encoded, data = data_filtered_regions)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.6988 -0.6988 -0.5889 -0.4425 20.3744 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     1.88193    0.17257  10.905   <2e-16 ***\nRegion_encoded -0.03662    0.02078  -1.762   0.0784 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.12 on 773 degrees of freedom\nMultiple R-squared:  0.004001,\tAdjusted R-squared:  0.002713 \nF-statistic: 3.105 on 1 and 773 DF,  p-value: 0.07842\n```\n\n\n:::\n\n```{.r .cell-code}\n# Coeficientes\nslope2 <- coef(model2)[2]\nintercept2 <- coef(model2)[1]\n\ncat(\"Modelo 2 - Pendiente: \", slope2, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModelo 2 - Pendiente:  -0.03662218 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Modelo 2 - Intercepto: \", intercept2, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModelo 2 - Intercepto:  1.881927 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n**Análisis de Regresión Lineal Simple**\n\n**1. Relación entre el Total de Muertos y Desaparecidos y el Número de Muertos**\n\nEn este análisis del modelo, se buscó entender la relación entre el **total de muertos y desaparecidos** y el **número de muertos** en incidentes migratorios.\n\nLa ecuación de la regresión es la siguiente:\n\n\\[\n\\text{Número de muertos} = 1.1458 + 0.1832 \\times (\\text{Total de muertos y desaparecidos})\n\\]\n\n**Interpretación de Resultados:**\n\n- **Pendiente (\\(\\beta_1 = 0.1832\\))**: Por cada persona adicional en el total de muertos y desaparecidos, se espera que el número de muertos aumente en **0.18 personas**, en promedio.\n  \n- **Intercepto (\\(\\beta_0 = 1.1458\\))**: Si el total de muertos y desaparecidos fuera cero, el modelo indica que el número estimado de muertos sería **1.15 personas**. Aunque es correcto, no necesariamente reflejo algo revelador, dado que un total de muertos y desaparecidos igual a 0 no implica migrantes fallecidos.\n\nEste modelo sugiere una relación positiva entre estas dos variables, lo que se espera, puesto que el número de muertos está relacionado con el total de muertos y desaparecidos en un incidente.\n\n---\n\n**2. Relación entre la Región y el Número de Muertos**\n\nEn este análisis, las **regiones** se codificaron numéricamente y se realizó una regresión lineal simple para evaluar si el **número de muertos** cambia entre las distintas regiones.\n\nLa ecuación de la regresión es:\n\n\\[\n\\text{Número de muertos} = 1.3123 + 0.0774 \\times (\\text{Región codificada})\n\\]\n\n**Interpretación de Resultados:**\n\n- **Pendiente (\\(\\beta_1 = 0.0774\\))**: Indica que, en promedio, al cambiar de una región a otra (codificada numéricamente), el número de muertos aumenta en **0.077 personas**.\n  \n- **Intercepto (\\(\\beta_0 = 1.3123\\))**: Cuando la región es la primera codificada, el número esperado de muertos es de **1.31 personas**.\n\nEl modelo sugiere que hay diferencias leves en el número de muertos entre las regiones, sin ser un relación significativa. La pendiente es pequeña, lo que indica que el número de muertos no varía drásticamente entre las distintas regiones.\n\n#### Método #3: Modelo autorregresivo integrado de media móvil (ARIMA)\n\nComo se tienen los incidentes reportados por año y a su vez la suma de muertes, sobrevivientes y desaparecidos se puede proyectar el futuro número migrantes muertos, rescatados o desaparecidos en los próximos años. \n\nRecuerde que el modelo ARIMA, según @SanidadMilitar, requiere de tres componentes (Autorregresivos(AR), Integrado(I) y Media Móvil(MA)) que dependen de tres parámetros definidos como:\n\n- p: Es el número de observaciones de retraso en el modelo.\n\n- d: Es el número de datos anteriores que se resta a cada valor conocido también como grado de diferenciación.\n\n- q: Es el tamaño de datos que se utiliza para la media móvil.\n\nY utiliza la siguiente ecuación:\n\n\\[\n(1 - a_1 L^1 - a_2 L^2 - \\dots - a_p L^p)(1 - L)^d Y_t = (1 - b_1 L^1 - b_2 L^2 - \\dots - b_q L^q) \\varepsilon_t\n\\]\n\nDonde:\n\n- \\( Y_t \\): valor de la variable en el momento \\( t \\).\n- \\( L \\): operador de retardos (por ejemplo, \\( Y_{t-1} = Y_t \\cdot L \\)).\n- \\( a_p \\): coeficientes para el componente autorregresivo.\n- \\( b_q \\): coeficientes para el componente de medias móviles.\n- \\( \\varepsilon_t \\): componente aleatoria.\n\n**Análisis de ARIMA**\n\n**1. Predicción de muertes de migrantes en los próximos 5 años**\n\nPrimero se observan algunos patrones o tendencias:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(ts_muertes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 2014 \nEnd = 2019 \nFrequency = 1 \n[1] 1752 4077 4071 3664 3176 3624\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(ts_muertes, main=\"Muertes por año\", xlab=\"Año\", ylab=\"Muertes\", col=\"darkred\", type=\"l\")\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\nUtilizando la prueba de Dickey-Fuller aumentada se observa si la serie temporal es estacionaria:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tseries)\nadf.test(ts_muertes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  ts_muertes\nDickey-Fuller = -2.9157, Lag order = 2, p-value = 0.2236\nalternative hypothesis: stationary\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nNote que la serie no es estacionaria, pues p-value > 0.05, entonces se procede a diferenciarla:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiff_muertes <- diff(ts_muertes)\nplot(diff_muertes, main = \"Serie temporal diferenciada\", col = \"darkred\")\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\nAhora se ajusta el modelo ARIMA, donde se utilizará la función auto.arima() del parquete **forecast** para un mejor manejo de los parámetros AR, I y MA de la serie:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(forecast)\nmodelo_arima <- auto.arima(ts_muertes)\nsummary(modelo_arima)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: ts_muertes \nARIMA(0,0,0) with non-zero mean \n\nCoefficients:\n           mean\n      3027.6667\ns.e.   323.9503\n\nsigma^2 = 1062543:  log likelihood = -74.68\nAIC=153.37   AICc=155.37   BIC=153.76\n\nTraining set error measures:\n                       ME     RMSE      MAE      MPE     MAPE      MASE\nTraining set 6.063545e-13 971.8449 851.5556 -16.6233 38.94371 0.8189018\n                   ACF1\nTraining set -0.0912454\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\nFinalmente utilizamos la función forecast() para realizar las predicciones en los próximos 5 años sobre las muertes de migrantes desaparecidos:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprediccion_muertes <- forecast(modelo_arima, h=5)\nhead(prediccion_muertes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$method\n[1] \"ARIMA(0,0,0) with non-zero mean\"\n\n$model\nSeries: ts_muertes \nARIMA(0,0,0) with non-zero mean \n\nCoefficients:\n           mean\n      3027.6667\ns.e.   323.9503\n\nsigma^2 = 1062543:  log likelihood = -74.68\nAIC=153.37   AICc=155.37   BIC=153.76\n\n$level\n[1] 80 95\n\n$mean\nTime Series:\nStart = 2023 \nEnd = 2027 \nFrequency = 1 \n[1] 3027.667 3027.667 3027.667 3027.667 3027.667\n\n$lower\nTime Series:\nStart = 2023 \nEnd = 2027 \nFrequency = 1 \n          80%      95%\n2023 1706.647 1007.341\n2024 1706.647 1007.341\n2025 1706.647 1007.341\n2026 1706.647 1007.341\n2027 1706.647 1007.341\n\n$upper\nTime Series:\nStart = 2023 \nEnd = 2027 \nFrequency = 1 \n          80%      95%\n2023 4348.686 5047.992\n2024 4348.686 5047.992\n2025 4348.686 5047.992\n2026 4348.686 5047.992\n2027 4348.686 5047.992\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(prediccion_muertes, main=\"Predicción de muertes de migrantes para los próximos 5 años\")\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\n\n**2. Predicción de sobrevivientes migrantes en los próximos 5 años**\n\nAl igual que con las muertes de migrantes, se observan algunos patrones o tendencias:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(ts_sobrevivientes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 2014 \nEnd = 2019 \nFrequency = 1 \n[1]  6122  8099 17112  6888  8321  4925\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(ts_sobrevivientes, main=\"Sobrevivientes por año\", xlab=\"Año\", ylab=\"Sobrevivientes\", col=\"darkblue\", type=\"l\")\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\nUtilizando la prueba de Dickey-Fuller aumentada se observa si la serie temporal es estacionaria:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tseries)\nadf.test(ts_sobrevivientes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  ts_sobrevivientes\nDickey-Fuller = -1.4007, Lag order = 2, p-value = 0.8007\nalternative hypothesis: stationary\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nAl igual que con las muertes, note que la serie no es estacionaria, pues p-value > 0.05, entonces se procede a diferenciarla:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiff_sobrevivientes <- diff(ts_sobrevivientes)\nplot(diff_sobrevivientes, main = \"Serie temporal diferenciada\", col = \"darkblue\")\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-pdf/unnamed-chunk-10-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\nAhora se ajusta el modelo ARIMA, donde se utilizará la función auto.arima() del parquete **forecast** para un mejor manejo de los parámetros AR, I y MA de la serie:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(forecast)\nmodelo_arima <- auto.arima(ts_sobrevivientes)\nsummary(modelo_arima)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: ts_sobrevivientes \nARIMA(0,0,0) with non-zero mean \n\nCoefficients:\n          mean\n      8011.111\ns.e.  1157.820\n\nsigma^2 = 13572881:  log likelihood = -86.15\nAIC=176.29   AICc=178.29   BIC=176.69\n\nTraining set error measures:\n                       ME    RMSE      MAE       MPE     MAPE      MASE\nTraining set 8.084397e-13 3473.44 2298.123 -13.41378 28.41677 0.5435004\n                    ACF1\nTraining set -0.09825737\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\nFinalmente utilizamos la función forecast() para realizar las predicciones en los próximos 5 años sobre los sobrevivientes migrantes desaparecidos:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprediccion_sobrevivientes <- forecast(modelo_arima, h=5)\nhead(prediccion_sobrevivientes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$method\n[1] \"ARIMA(0,0,0) with non-zero mean\"\n\n$model\nSeries: ts_sobrevivientes \nARIMA(0,0,0) with non-zero mean \n\nCoefficients:\n          mean\n      8011.111\ns.e.  1157.820\n\nsigma^2 = 13572881:  log likelihood = -86.15\nAIC=176.29   AICc=178.29   BIC=176.69\n\n$level\n[1] 80 95\n\n$mean\nTime Series:\nStart = 2023 \nEnd = 2027 \nFrequency = 1 \n[1] 8011.111 8011.111 8011.111 8011.111 8011.111\n\n$lower\nTime Series:\nStart = 2023 \nEnd = 2027 \nFrequency = 1 \n          80%      95%\n2023 3289.697 790.3312\n2024 3289.697 790.3312\n2025 3289.697 790.3312\n2026 3289.697 790.3312\n2027 3289.697 790.3312\n\n$upper\nTime Series:\nStart = 2023 \nEnd = 2027 \nFrequency = 1 \n          80%      95%\n2023 12732.53 15231.89\n2024 12732.53 15231.89\n2025 12732.53 15231.89\n2026 12732.53 15231.89\n2027 12732.53 15231.89\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(prediccion_sobrevivientes, main=\"Predicción de sobrevivientes migrantes para los próximos 5 años\")\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\n\n**3. Predicción de desapariciones de migrantes en los próximos 5 años**\n\nAl igual que en los casos anteriores, se observan algunos patrones o tendencias:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(ts_desaparecidos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 2014 \nEnd = 2019 \nFrequency = 1 \n[1] 3566 2637 4013 2620 1811 1777\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(ts_desaparecidos, main=\"Desaparecidos por año\", xlab=\"Año\", ylab=\"Desaparecidos\", col=\"purple\", type=\"l\")\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\nUtilizando la prueba de Dickey-Fuller aumentada se observa si la serie temporal es estacionaria:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tseries)\nadf.test(ts_desaparecidos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  ts_desaparecidos\nDickey-Fuller = -2.3603, Lag order = 2, p-value = 0.4351\nalternative hypothesis: stationary\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nIgualmente la serie no es estacionaria, pues p-value > 0.05, entonces se procede a diferenciarla:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiff_desaparecidos <- diff(ts_desaparecidos)\nplot(diff_desaparecidos, main = \"Serie temporal diferenciada\", col = \"purple\")\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\nAhora se ajusta el modelo ARIMA, donde se utilizará la función auto.arima() del parquete **forecast** para un mejor manejo de los parámetros AR, I y MA de la serie:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(forecast)\nmodelo_arima <- auto.arima(ts_desaparecidos)\nsummary(modelo_arima)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: ts_desaparecidos \nARIMA(0,1,0) \n\nsigma^2 = 921593:  log likelihood = -66.29\nAIC=134.57   AICc=135.24   BIC=134.65\n\nTraining set error measures:\n                   ME     RMSE      MAE       MPE     MAPE      MASE       ACF1\nTraining set -259.826 905.0933 733.2851 -19.44727 34.22342 0.8893694 -0.4340032\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\nFinalmente utilizamos la función forecast() para realizar las predicciones en los próximos 5 años sobre los sobrevivientes migrantes desaparecidos:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprediccion_desaparecidos <- forecast(modelo_arima, h=5)\nhead(prediccion_desaparecidos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$method\n[1] \"ARIMA(0,1,0)\"\n\n$model\nSeries: ts_desaparecidos \nARIMA(0,1,0) \n\nsigma^2 = 921593:  log likelihood = -66.29\nAIC=134.57   AICc=135.24   BIC=134.65\n\n$level\n[1] 80 95\n\n$mean\nTime Series:\nStart = 2023 \nEnd = 2027 \nFrequency = 1 \n[1] 1224 1224 1224 1224 1224\n\n$lower\nTime Series:\nStart = 2023 \nEnd = 2027 \nFrequency = 1 \n             80%        95%\n2023    -6.28489  -657.5584\n2024  -515.88558 -1436.9254\n2025  -906.91594 -2034.9547\n2026 -1236.56978 -2539.1167\n2027 -1527.00065 -2983.2924\n\n$upper\nTime Series:\nStart = 2023 \nEnd = 2027 \nFrequency = 1 \n          80%      95%\n2023 2454.285 3105.558\n2024 2963.886 3884.925\n2025 3354.916 4482.955\n2026 3684.570 4987.117\n2027 3975.001 5431.292\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(prediccion_desaparecidos, main=\"Predicción de desapariciones de migrantes para los próximos 5 años\")\n```\n\n::: {.cell-output-display}\n![](bitacora-3_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\n\n### Construcción de fichas de resultados\n\n**6. Nombre del hallazgo: Predicción de muertes de migrantes en los próximos 5 años.**\n\n**Resumen en una oración: **Se espera que del 2023 al 2027 se reporten 3.028 muertes.\n\n**Principal característica: **El resultado presenta el número de muertes probable que ocurra en los próximos 5 años.\n\n**Problemas o posibles desafíos: **Se basa en eventos pasados, incluidos eventos catastróficos como la pandemia de COVID-19, que no ocurren en un horizonte de 5 años.\n\n**Resumen en un párrafo: **Se puede observar una preddicción puntual de que mueran 3.028 migrantes por año. También se tiene una incertidumbre donde existe un 80% de probabilidad de que el número de muertes de los próximos años se encuentre entre 1.707 y 4.349 muertes por año, que se diferencia en promedio en 1.321 muertes a la predicción central. Por otro lado existe un 95% de que el número de muertes se encuentre entre 1.007 y 5.047, que se diferencia en promedio en 2.020 muertes a la predicción central.\n\n**7. Nombre del hallazgo: Predicción de sobrevivientes de migrantes en los próximos 5 años.**\n\n**Resumen en una oración: **Se espera que del 2023 al 2027 se reporten 8.011 muertes.\n\n**Principal característica: **El resultado presenta el número de sobrevivientes migrantes más probable que ocurra en los próximos 5 años.\n\n**Problemas o posibles desafíos: **Se basa en eventos pasados, incluidos eventos catastróficos como la pandemia de COVID-19, que no ocurren en un horizonte de 5 años.\n\n**Resumen en un párrafo: **Se puede observar una predicción puntual de que sobrevivan o sean rescatados 8.011 migrantes por año. También se tiene una incertidumbre donde existe un 80% de probabilidad de que el número de sobrevivientes migrantes en los próximos años se encuentre entre 3.289 y 12.732 por año, que se diferencia en promedio en 4.721 a la predicción central. Por otro lado existe un 95% de que el número de muertes se encuentre entre 790 y 15.231, que se diferencia en promedio en 7.220 muertes a la predicción central.\n\n**8. Nombre del hallazgo: Predicción de desapariciones de migrantes en los próximos 5 años.**\n\n**Resumen en una oración: **Se espera que del 2023 al 2027 sean reportados 1.224 migrantes como desaparecidos cada año\n\n**Principal característica: **El resultado presenta el número de migrantes desaparecidos más probable que ocurra en los próximos 5 años.\n\n**Problemas o posibles desafíos: **Se basa en eventos pasados, incluidos eventos catastróficos como la pandemia de COVID-19, que no ocurren en un horizonte de 5 años.\n\n**Resumen en un párrafo: **A diferencia de los casos de muerte y sobrevivencia, la predicción puntual del número de dsaparecidos varía por año como se muestra anteriormente, donde existe una incertidumbre con un 80% de probabilidad  de que el menor número esperado es -1527, esto podría indicar que es probable que en vez de reportar migrantes como desaparecidos se puede presenter la certeza de si el migrante ha muerto o ha sobrevivido a los diferentes incidentes o por otro lado se recolecte menos información sobre desaparecidos en los últimos años.\n\n**9. Nombre del hallazgo: Más sobrevivientes que muertos**\n\n**Resumen en una oración: ** Se espera que se rescaten 4.983 más migrantes que los que no logran sobrevivir.\n\n**Principal característica: **El hallazgo compara los resultados 7 y 8 y presente un mayor número de sobrevivientes al número de muertes en un futuro.\n\n**Problemas o posibles desafíos: **No se toma en cuenta los desaparecidos, debido a que podría tratarse de posibles sobrevivientes o de muertos.\n\n**Resumen en un párrafo: **Se puede observar que al utilizar el mismo modelo ARIMA para la predicción de la muerte de migrantes y sobrevivientes, la predicción puntual de los sobrevivientes se encuentra 4.983 por encima que la de muertes futuras, lo cual indica que la mayoría de incidentes son reportados al realizar rescates o por lo menos presentan algún sobreviviente.\n\n\n\n## Parte de Escritura\n## Parte de reflexión\n\n---\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}